### ISSUE TITLE
discovery capabilites

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-connector-mongodb#101]
looking at http://docs.strongloop.com/display/public/LB/Database+discovery+API, it seems that mongo does not have discovery capabilites.

whilst I can understand that mongo is a document-orientated db, would it not be possible to runt hrough the collections (thereby giving you the models) and sampling say 10 records to grab the top-level properties as a helpful start ?

Or is there something like this already ?

**Comment by raymondfeng** [comment]
We have the utility to reverse-engineer a JSON object for the model definition. But it's not integrated with mongodb yet. Do you want to give a try?

**Comment by jmls** [comment]
more than happy to play with it

thanks!

On 18 February 2015 at 17:04, Raymond Feng <notifications@github.com> wrote:

> We have the utility to reverse-engineer a JSON object for the model
> definition. But it's not integrated with mongodb yet. Do you want to give a
> try?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/strongloop/loopback-connector-mongodb/issues/101#issuecomment-74902631>
> .
>



-- 
Julian Lyndon-Smith
IT Director,
dot.r
http://www.dotr.com
