### ISSUE TITLE
If a value is 'undefined' for a 'where' condition, the condition is skipped

### ISSUE THREAD

**Issue by moguelator** [strongloop/loopback-connector-mongodb#102]
I upgraded to version 1.7.0 and a lot of my queries are not working. When an undefined value is passed to a condition, this condition is just skipped.

For example, if I want to get a post with authorId:1 and groupId:undefined, the result is that I get all of the post for author with id 1, instead of bringing the posts for this author that do not have a groupId defined.

```javascript
var group;

Post.findOne({
        where: {
          and: [
            {groupId: group},
            {authorId: ctx.req.accessToken.userId}
          ]
        }}, function (err, post) { ...
```

makes sense?

**Comment by Terekhov** [comment]
Use the operators mentioned here, that's what they're for. https://github.com/strongloop/loopback/issues/1009#issuecomment-85567830

**Comment by Amir-61** [comment]
Hey @moguelator,

Could you please let us know if `$exist` like the following usage worked for you, if so please let us know so we can close this ticket.

The example usage for `$exist`:

```
{
  where: {
    myProp: {
      $exist: true
    }
  }
}
```

If it does not work, please create a sample repo using our [loopback-sandbox](https://github.com/sharkinsspatial/loopback-sandbox) so we can look into it.

Thanks!

**Comment by moguelator** [comment]
Thanks, it worked.

**Comment by Amir-61** [comment]
@moguelator,

Glad that your problem is solved.

Thank you!
