### ISSUE TITLE
Indexes are not created when declared in Model JSON

### ISSUE THREAD

**Issue by ilianaza** [strongloop/loopback-connector-mongodb#103]
I just want to check whether creating indexes feature has been implemented or not. I followed documentation on http://docs.strongloop.com/display/public/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Indexes and tried to declare the following index in my model json file:
```
...
"base": "PersistedModel",
  "indexes": {
    "unique_registration_index": {
      "keys": {
        "playerId": 1,
        "eventId": 1
      },
      "options": {
        "unique": true
      }
    }
  },
...
```
But when I check MongoDB, I don't see this index being generated.
1. Has that feature been implemented?
2. If not, what's the best way for me to restrict uniqueness for combination of fields (like playerId and eventId in my case)?

**Comment by raymondfeng** [comment]
You'll have to run `automigrate` (drop and recreate collections/indexes) or `autoupdate` (ensureIndexes).

**Comment by ilianaza** [comment]
@raymondfeng Thanks for the quick response. Saved my day!

**Comment by uzyn** [comment]
@raymondfeng If that is the case shouldn't it be included as one of the boot scripts by default?

**Comment by nvcken** [comment]
I tried automigrate and autoupdate at boot scripts
```
module.exports = function(server) {
	var ds = server.dataSources.mongodb;
        ds.automigrate('Product')
	ds.autoupdate('Product', function () {
         });
```
Then all data of Product lost without preserve

**Comment by raymondfeng** [comment]
Use autoupdate, NOT automigrate.

**Comment by nvcken** [comment]
Thanks :+1:

**Comment by thaiat** [comment]
for what it worth here is my autoupdate script:
```js
'use strict';
global.Promise = require('bluebird');

module.exports = function(server) {

    Promise.each(server.models(), function(model) {

        if (model.dataSource) {
            var autoupdate = Promise.promisify(model.dataSource.autoupdate);
            if (autoupdate) {
                return autoupdate.call(model.dataSource, model.modelName);
            }
        }
    });
};

```

**Comment by 0candy** [comment]
Closing this issue as its been resolved.

**Comment by michaelfreund** [comment]
@thaiat thanks for the script. works like a charm. but what if you remove an index definition from a model.json? I recognized that indexes are not removed from db.

**Comment by shashank008** [comment]
@thaiat I'm getting this error when the script is executed. But the indexes are being created.
MongoError: collection already exists

**Comment by akvaliya** [comment]
@michaelfreund have you found solution for remove an index from db when remove from model.json?
