### ISSUE TITLE
Where conditional inconsistent with docs

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-connector-mongodb#105]
Docs say conditional where (gt, lt) should look like this

```js
query = {
  where: {
    points: {
      gt: 58
   }
 };
```
This throws mongoDB error `unknown command: $points` 
this works but is not how it is stated in the docs

```js 
query = {
  where: {
    gt: {
      points: 58
    }
  }
}
```

loopback-connector-mongodb 1.8.0

**Comment by raymondfeng** [comment]
You had a wrong argument for `count()` which only takes the `where` instead of the whole `filter`.

**Comment by BerkeleyTrue** [comment]
I see. thanks! @raymondfeng to the rescue again!
