### ISSUE TITLE
Support mongoose-paginate

### ISSUE THREAD

**Issue by mamboer** [strongloop/loopback-connector-mongodb#106]
it will be cool if loopback-connector-mongodb integrate mongoose-paginate, and then loopback can expose a paginate api

**Comment by raymondfeng** [comment]
LoopBack already supports pagination, see:

http://docs.strongloop.com/display/LB/Limit+filter
http://docs.strongloop.com/display/LB/Skip+filter

**Comment by mamboer** [comment]
but it's not friendly for client side paging, most javascript pagination components expect  a data structure like {"total":200,"items":[]}
