### ISSUE TITLE
Depth issue when using complex queries with mongo db operators.

### ISSUE THREAD

**Issue by shyambalu-sellaco** [strongloop/loopback-connector-mongodb#107]
Range queries are not supported, have to do more verbose. But in general more than one level of depth is not supported for complex queries, using mongodb operators.

```
{"where":{"financials.revenue":{"gt":60,"lt":245}}
```

Only the `gt` arrives at the database. It has to be translated to 

```
{"where":{"and": [{"financials.revenue":{"gt":60}}, {"financials.revenue":{"lt":245}}]}}
```

**Comment by srguiwiz** [comment]
Sounds related to issue #99 for which there is a workaround/fix in pull request #100.

**Comment by shyambalu-sellaco** [comment]
Ah yep that would be it. Great thanks.

**Comment by srguiwiz** [comment]
until the fix has been merged this should remain open

**Comment by ssh24** [comment]
Similar to #99.

Closing this as a result. Feel free to reopen if needed.
