### ISSUE TITLE
Cannot do simple case insensitive where like

### ISSUE THREAD

**Issue by srguiwiz** [strongloop/loopback-connector-mongodb#108]
This is a problem description.  A second comment will describe one workaround/fix, which might be less than ideal.  A third comment will describe a hopefully more acceptable workaround/fix.

Background fact: JavaScript regular expressions don't support flags, modes, modifiers.  I.e. not `(?i)` for case insensitive. JavaScript regular expressions are used in MongoDB.

A problem if trying to enable end-users to find *Jones, Matthew* by searching for *mat*.

If on the server in Node.js you try to give `find` a `new RegExp("mat","i")` that gets garbled into something useless by `dao.js` function `DataAccessObject._coerce` making it a string that doesn't translate back into the same regular expression for `loopback-connector-mongodb`'s `like`.

Apparently impossible to make it work without a change to source code.

For completeness I will describe a proven fix in `dao.js`, but don't think that is ideal, because I cannot be certain of its impact on other database connectors.  Also that fix is limited to Node.js and doesn't work with RESTful.

Then I will describe supporting `(?i)` within `loopback-connector-mongodb`, which will work on the server in Node.js as well as from RESTful.

**Comment by srguiwiz** [comment]
Here is a proven workaround/fix in `dao.js`.  As I do *not* suggest using it, I do not provide a pull request for this one.

In `DataAccessObject._coerce` name the `for` loop:

```javascript
  whereLoop: for (var p in where) {
```

and for `like` do:

```javascript
            case 'like':
            case 'nlike':
              if (val instanceof RegExp) {
                continue whereLoop;
              }
              if (!(typeof val === 'string')) {
```

After which in Node.js you can pass in e.g. to `find` for a `like` a `new RegExp("mat","i")` and get a case insensitive match.

Doesn't solve the problem for RESTful.  And compatibility with other database connectors isn't known.  Not good, but at least nice to know.

**Comment by srguiwiz** [comment]
Better fix here in `loopback-connector-mongodb`'s `lib/mongodb.js` insert:

```javascript
// make { like: "(?i)whatever" } a case insensitive version of { like: "whatever" }
function newRegExp(cond) {
  if (typeof cond === 'string') {
    if (cond.indexOf('(?i)') !== 0) {
      return new RegExp(cond);
    } else {
      return new RegExp(cond.substring(4), 'i');
    }
  } else {
    return new RegExp(cond);
  }
}
```

and change to:

```javascript
      } else if (spec === 'like') {
        query[k] = {$regex: newRegExp(cond)};
      } else if (spec === 'nlike') {
        query[k] = {$not: newRegExp(cond)};
```

then you can `like: "(?i)whatever"` either from Node.js or via RESTful API.

Submitting pull request.

**Comment by srguiwiz** [comment]
pull request #109 has been opened

**Comment by srguiwiz** [comment]
This implementation provides a standard syntax `(?i)` for case insensitive regular expressions.  Same as Python, Java, PCRE, Perl.  Seems a reasonable way to "sneak in" this missing feature.

**Comment by BerkeleyTrue** [comment]
I believe this issue is resolved and can be closed.

**Comment by Amir-61** [comment]
I believe this has already been solved and closing it.

```
var pattern = new RegExp('.*'+query+'.*', "i"); /* case-insensitive RegExp search */ 
Post.find({ where: {title: { like: pattern} } }, 
```
Via the REST API - see strongloop/loopback-connector-mongodb#86
```
?filter={"where":{"title":{"like":"someth.*","options":"i"}}}
```
