### ISSUE TITLE
Validation issue when put is used (tested with User model) on Windows

### ISSUE THREAD

**Issue by bkniffler** [strongloop/loopback-connector-mongodb#123]
Steps to reproduce:
- Use Windows (issue won't appear on Mac)
- Load Loopback-Sandbox
- npm install loopback-connector-mongodb
- Set "Users" datasource to MongoDB
- Post a new user
- Put /api/users/..id, e.g. with data {realm: "xxx"} (using a matching access token of course)

Result: ValidationError 402, "The `User` instance is not valid. Details: `email` Email already exists.." etc.
Expected: It should work as we only post a changed property via put.

**Comment by bkniffler** [comment]
Here is the full response body
```
{
  "error": {
    "name": "ValidationError",
    "status": 422,
    "message": "The `User` instance is not valid. Details: `email` Email already exists (value: \"bkniffler@me.com\"); `username` User already exists (value: \"bkniffler\").",
    "statusCode": 422,
    "details": {
      "context": "User",
      "codes": {
        "email": [
          "uniqueness"
        ],
        "username": [
          "uniqueness"
        ]
      },
      "messages": {
        "email": [
          "Email already exists"
        ],
        "username": [
          "User already exists"
        ]
      }
    },
    "stack": "ValidationError: The `User` instance is not valid. Details: `email` Email already exists (value: \"bkniffler@me.com\"); `username` User already exists (value: \"bkniffler\").\n    at C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:2072:12\n    at ModelConstructor.<anonymous> (C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:471:13)\n    at ModelConstructor.next (C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\hooks.js:75:12)\n    at done (C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:468:25)\n    at C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:542:7\n    at ModelConstructor.<anonymous> (C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\validations.js:354:5)\n    at allCb (C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-datasource-juggler\\lib\\dao.js:1256:7)\n    at C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-connector-mongodb\\lib\\mongodb.js:597:7\n    at handleCallback (C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-connector-mongodb\\node_modules\\mongodb\\lib\\utils.js:95:12)\n    at C:\\Users\\Administrator\\Downloads\\loopback-sandbox-master\\node_modules\\loopback-connector-mongodb\\node_modules\\mongodb\\lib\\cursor.js:571:16"
  }
}
```

**Comment by bkniffler** [comment]
Here is a Debug Screenshot
![error](https://cloud.githubusercontent.com/assets/4349324/7049812/0957c3a4-de1d-11e4-82d9-628c6b1adc79.jpg)

**Comment by mariohmol** [comment]
This is really strange. I had an app using mysql and it worked. Then i resolve to port it to mongodb and after that login stop working, giving me this email already exists error.

After removing coding and testing i could see that this problems happens when i have something like that:

````
user.afterRemote('create', function(context, user, next) {
    user.verify(options, function(err, response) {} );
````

When i remove the verify function it works as normal.

So it looks like a bug in the connector.

**Comment by mariohmol** [comment]
Just to let you know, i'm using Mac OS with:

strongloop v6.0.0 (node v4.2.2)
├── strong-arc@1.8.5 (d01942e)
├── strong-build@2.0.6 (d008a3e)
├── strong-deploy@3.1.2 (be6180a)
├── strong-mesh-models@8.1.0 (62e539b)
├── strong-pm@5.0.1 (b96f806)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.3.2 (1327018)
├─┬ strong-supervisor@3.3.1 (1e39220)
│ └── strong-agent@2.0.2 (4ea7ee9)
├── generator-loopback@1.13.0 (a884c0b)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3

**Comment by mariohmol** [comment]
i found out my problem.. I had my user.json from mysql and i changed some attributes to make it working in mongodb.. but i forgot to remove the identity from on.. example:

````
"id": {
      "type": "Number",
      "id": true,
      "_selectable": true
    }
`````
Its necessary to remove the "id": true to make mongodb find the correct object in user.save used inside verify function.

**Comment by smartmouse** [comment]
@bkniffler  Do you still have the issue?  
Does @mariohmol  solution works for you?  Thanks @mariohmol . 
Please let us know.

**Comment by bkniffler** [comment]
Hey, sorry, but I've moved away from loopback in the meantime, so I can't really help on this matter.

**Comment by dhmlau** [comment]
@bkniffler , in this case, can I close this issue?  Thanks.
