### ISSUE TITLE
Disable to explicitly set _id when posting an object.

### ISSUE THREAD

**Issue by peterwilli** [strongloop/loopback-connector-mongodb#131]
Hi,

When trying to post an object I can set the underlying model's _id property by explicitly setting it.

The POST JSON:

```
{
    ... other object data..
    "id": "myid"
}
```

This is ok for 1 time but then an error about duplicate key shows up obviously ;)
I know that if I omit the "id"-key it makes a random id.
The point is I dont want my users to make their own id, just always random.
I "sort-of" made a ductape solution, using the read-only mixin (https://www.npmjs.com/package/loopback-ds-readonly-mixin) and setting "id" as readonly. But I have to set this for each and every model.

Does someone have a better solution? I spend a lot of time searching a solution but can't find it :( Thanks!

**Comment by raymondfeng** [comment]
You can use `defaultFn` for the property, see http://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Generalpropertyproperties

**Comment by peterwilli** [comment]
@raymondfeng I'm sorry, but I fail to see how that's an easier solution than what I have above :) But thanks for responding!
