### ISSUE TITLE
Ignore properties that are not in the model schema

### ISSUE THREAD

**Issue by peterwilli** [strongloop/loopback-connector-mongodb#134]
Hi,

In the API explorer, I can send trough any property, even the ones that arent in my schema.
What I expect to happen is that those variables get ignored.

See the 2 screenshots. The first one I enter some extra properties in the explorer.
![schermafbeelding 2015-05-19 om 11 31 24](https://cloud.githubusercontent.com/assets/1212814/7699779/af630a8e-fe1a-11e4-8abe-7a73b563ea18.png)

In the second, I show you the entry in my mongodb:

![schermafbeelding 2015-05-19 om 11 31 14](https://cloud.githubusercontent.com/assets/1212814/7699781/b38af7b6-fe1a-11e4-9879-f5b678dacc13.png)

Is there any easy way to ignore those "out of model" properties? I can't seem to find it. Thanks!

My Model:

    {
      "name": "PublicUser",
      "plural": "public_users",
      "base": "PersistedModel",
      "idInjection": true,
      "options": {
        "validateUpsert": true
      },
      "properties": {
        "displayName": {
          "type": "string",
          "required": true
        },
        "avatar": {
          "type": "string",
          "required": true
        }
      },
      "validations": [],
      "relations": {
        "userIdentity": {
          "type": "hasOne",
          "model": "userIdentity",
          "foreignKey": "ownerId"
        }
      },
      "acls": [],
      "methods": []
    }

**Comment by raymondfeng** [comment]
You can configure the behavior using ‘strict’ for your model. See http://docs.strongloop.com/display/LB/Model+definition+JSON+file#ModeldefinitionJSONfile-Top-levelproperties. In your case, the value can be `true` (ignore), `validate` (report as validation error), or `throw` (throw).

**Comment by peterwilli** [comment]
Thanks @raymondfeng !!

**Comment by jmwohl** [comment]
Sorry to bring up a closed issue, but it seems loopback 3 [no longer includes the 'ignore without validation error' option](http://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#top-level-properties) — is there any way to ignore extra properties in loopback 3?

**Comment by jordymeow** [comment]
Same here. It seems it can be set to "filter", but even I am trying that the model goes through strict validation anyway and gets rejected.

**Comment by chunkbro** [comment]
I was facing this issue in Loopback 4. I had to remove the openApi spec that uses json schema generated from the model, to get it working.
