### ISSUE TITLE
Mongodb connectors getting crashed

### ISSUE THREAD

**Issue by mailmevenkat** [strongloop/loopback-connector-mongodb#140]
MongoDB connection is getting crashed when executing any operation. I have attached the screenshot below.

I have checked through the source code, seems like notifyObserversAround is not defined. 
![screenshot from 2015-06-03 12 51 12](https://cloud.githubusercontent.com/assets/9083583/7968129/5fc5ac46-0a4c-11e5-87ea-a266c07bc244.png)

**Comment by raymondfeng** [comment]
Please run `npm up` to upgrade the version for loopback-datasource-juggler.

Thanks,

---
Raymond Feng
Co-Founder and Architect @ StrongLoop, Inc.

StrongLoop <http://strongloop.com/> makes it easy to develop APIs <http://strongloop.com/mobile-application-development/loopback/> in Node, plus get DevOps capabilities <http://strongloop.com/node-js-performance/strongops/> like monitoring, debugging and clustering.

**Comment by mailmevenkat** [comment]
It's working now :+1:  

Thanks
