### ISSUE TITLE
How to get distinct of a collection from mongodb 

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback-connector-mongodb#144]
I am using mongodb connectot with strongloop.I have a cities collection.I want to get the distinct data from the city collection.How can i do that

**Comment by raymondfeng** [comment]
You have to use the mongodb driver to get distinct data directly. There is no aggregation based query supported by LB yet.

**Comment by raymondfeng** [comment]
I'm closing this issue as questions are better posted to https://groups.google.com/forum/#!forum/loopbackjs.
