### ISSUE TITLE
Default sort order overwrite the $nearSphere criteria

### ISSUE THREAD

**Issue by kwiky** [strongloop/loopback-connector-mongodb#147]
When i use the $nearSphere criteria, the default order on id overwrite the location order :(

Here : 
https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L653

**Comment by mazesoul** [comment]
+1

**Comment by jskrzypek** [comment]
+1

**Comment by ssh24** [comment]
Related to https://github.com/strongloop/loopback-connector-mongodb/issues/55. Closing this. Feel free to reopen if needed.
