### ISSUE TITLE
Bug: 'like' query should check if 'cond' is a regex in disguise.

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-connector-mongodb#151]
Docs state that a regex can be used with a `like` query to provide flags without needing to use options prop.
![mongodb_connector_-_loopback_-_documentation](https://cloud.githubusercontent.com/assets/6775919/8268953/7b262a2e-1749-11e5-940c-333c7ebd0d1b.png)

however, [this line](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L594) simply passes the condition argument directly to the regex constructor.

![loopback-connector-mongodb_mongodb_js_at_master_ _strongloop_loopback-connector-mongodb](https://cloud.githubusercontent.com/assets/6775919/8269020/f8f3a1aa-174b-11e5-9479-e37923204c5c.png)

Somewhere along the line that condition is transformed from a regex to a string value.

so `/foo/i` when it gets to this point is actually `'/foo/i'` and after the Regex constructor spits it out it ends up as `/\/foo\/i/` and mongo is looking for a string to match '/foo/i' instead of a case insensitive 'foo'.

Solution: Check if string is actually a regex before using a passing it into the constructor. Not exactly sure how to accomplish this at the moment.

**Comment by ssh24** [comment]
@BerkeleyTrue You can pass in an option along with the `like` operator to state that you would like an case insensitive search.

Here is a sample code snippet:

**model-definition.json**
```json
{
  "name": "Post",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "title": {
      "type": "string"
    },
    "createdAt": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');
var _ = require('lodash');

module.exports = function(app) {
    var db = app.datasources.mongoDs;
    var Post = app.models.Post;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Post.create([{
            title: 'Hello World'
        }, {
            title: 'Liverpool Football Club'
        }, {
            title: 'hello world'
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            Post.find({where: {title: {like: 'H.', options: 'i'}}}, function(err, result) {
                if (err) throw err;
                console.log('\nFound instance: ' + util.inspect(result));
            });
        });
    });
};
```

**output**
```bash
sakibs-mac:mongodb-151 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { title: 'Hello World', id: 59496926e2586955235f9327 },
  { title: 'Liverpool Football Club',
    id: 59496926e2586955235f9328 },
  { title: 'hello world', id: 59496926e2586955235f9329 } ]

Found instance: [ { title: 'Hello World', id: 59496926e2586955235f9327 },
  { title: 'hello world', id: 59496926e2586955235f9329 } ]
```

Closing this issue as resolved. Feel free to reopen if needed.

**Comment by BerkeleyTrue** [comment]
> You can pass in an option along with the like operator to state that you would like an case insensitive search

@ssh24 The issue is not "I can't make case insensitive search". The issue is: I can't pass a regex to the like query as stated in the docs. The example given is a trivial example demonstrating the fact that a regex cannot be passed through to the monodb query as stated in the loopback docs.

> Closing this issue as resolved. Feel free to reopen if needed.

Once a mod closes an issue it cannot be reopened by the original poster.

**Comment by ssh24** [comment]
@BerkeleyTrue Where is the docs that you are referring to? This is the official [LoopBack doc on MongoDB](https://loopback.io/doc/en/lb3/MongoDB-connector.html) and I can't find your example in there.

**Comment by BerkeleyTrue** [comment]
@ssh24 Looks like in the two years since I opened this issue that feature has been removed from the doc's.

Seems like this issue can be closed as this is something that is not supported and no longer explicitly stated in the docs.

Although, I'd like to see this turned into a feature request.

The line still exists in the connector:
https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L738

It could be turned into:
```js
} else if (spec === 'like') {
   if (cond instanceof RegExp) {
     query[k] = { $regex: cond };
   } else {
     query[k] = { $regex: new RegExp(cond, options) };
   }
}
```

If memory serves me right, we got around this by using the monogdb driver instance exposed by the connector directly instead of going through loopbacks ORM.

**Comment by ssh24** [comment]
@BerkeleyTrue The fix is on master. Should be released with the upcoming release version of the connector.

Closing this issue as a result.

**Comment by BerkeleyTrue** [comment]
@ssh24 Wow! Thanks so much!

**Comment by ssh24** [comment]
You are welcome. Thank you for using LoopBack and making us better.
