### ISSUE TITLE
Is not creating index creation when collection doesn't exist

### ISSUE THREAD

**Issue by kuskov** [strongloop/loopback-connector-mongodb#153]
We have defined a model and then emptied the collections in the MongoDB. When we start the server, loopback creates the collection, but it doesn't create the index on the fields specified in the model. For example:

```
"businessProductCategoryId": {
      "type": "string",
      "required": true,
      "description": "ObjectId of the model",
      "maxLength": 40,
      "index": true
    },
    "title": {
      "type": "object",
      "properties": {
        "de": {
          "type": "string",
          "maxLength": 100,
          "index": true
        }
      }
    },
```

When i check the collection, there is only one index called "_id" the standard one. Is there a solution/fix?

**Comment by raymondfeng** [comment]
The indexes are created with dataSource.autoupdate or automigrate. See http://docs.strongloop.com/display/LB/Implementing+auto-migration
