### ISSUE TITLE
Proposition Bug Mongodb conector

### ISSUE THREAD

**Issue by josepe36** [strongloop/loopback-connector-mongodb#154]
Hi
After long time with relational problems with mongodb conector, i 've found a way to fix this problem.

The problem is than when we are using mongodb conector, the rolemapping does not work, the relations are not followed.
Because the principalId is recorded as a string and not as ObjectId the orm does not match.

So i looked in the file :
node_modules/loopback-connector-mongodb/lib/mongodb.js
On the line number 26 and add || /^[0-9a-fA-F]{12}$/.test(id).
try {
    // MongoDB's ObjectID constructor accepts number, 12-byte string or 24-byte
    // hex string. For LoopBack, we only allow 24-byte hex string, but 12-byte
    // string such as 'line-by-line' should be kept as string
    if(/^[0-9a-fA-F]{24}$/.test(id) || /^[0-9a-fA-F]{12}$/.test(id)) {
      return new mongodb.ObjectID(id);
    } else {
      return id;
    }
  } catch (e) {
    return id;
  }

Appearly my mongo version use 12-byte hex string, so why do not create an ObjectId ?
This way i get the relational rolemapping working fine now.

Regards

**Comment by ssh24** [comment]
Related to https://github.com/strongloop/loopback-connector-mongodb/issues/302.

Closing this. Feel free to reopen if needed.
