### ISSUE TITLE
updateAttributes() ignores values wihtout operators if any operators are specified for other values

### ISSUE THREAD

**Issue by voitau** [strongloop/loopback-connector-mongodb#156]
These are the working examples: 
- `updateAttributes({description: 'v1', version: 1}, ...)`
- `updateAttributes({'$set': {description: 'v1', version: 1}}, ...)`
- `updateAttributes({'$set': {description: 'v1'}, '$inc': {version: 1}}, ...)`

This does not work, although seems like a combination of the examples above:
- `updateAttributes({description: 'v1', '$inc': {version: 1}}, ...)`.

Complete example: https://github.com/voitau/loopback-examples/blob/master/mongo-connector/test/petition.test.js#L29-L40

**Comment by satyadeepk** [comment]
I am seeing this too. If I include any other property along with `$inc`, it is ignored.

**Comment by zanemcca** [comment]
+1
I am using the alternative provided by @voitau for now.
```updateAttributes({'$set': {description: 'v1'}, '$inc': {version: 1}}, ...)```
