### ISSUE TITLE
can not get correct object when contains "result" key in document

### ISSUE THREAD

**Issue by williamchang73** [strongloop/loopback-connector-mongodb#160]
### "loopback-connector-mongodb": "1.5.0" ~ "1.11.3"
mongo version : 3.0.4
"loopback-datasource-juggler" : "2.33.1"

##### if contains result in document, it will return wrong objecct

{ "deviceID" : "empty", "type" : 2, "command" : 1, "progress" : 5, "routerID" : "12345", "result" : [ { "test1" : 1 }, { "test2" : 1 }, { "test3" : 1 }, { "test4" : 1 } ], "createdByDeviceID" : "12345", "executeStatus" : 1, "params" : { "type" : "Fast", "extra" : [ "DefaultPwd" ], "excludeVulScanTypes" : [ 0, 4, 5 ] }, "created" : ISODate("2015-07-14T14:00:27.605Z"), "modified" : ISODate("2015-07-14T14:00:27.605Z"), "_id" : ObjectId("55a515fb5b888c7cdf6897bd") }

http://127.0.0.1:3000/api/v1/commands/55a515fb5b888c7cdf6897bd

{"test1":1}

##### if change the key from result to result2, the object is correct

{ "deviceID" : "empty", "type" : 2, "command" : 1, "progress" : 5, "routerID" : "12345", "result2" : [ { "test1" : 1 }, { "test2" : 1 }, { "test3" : 1 }, { "test4" : 1 } ], "createdByDeviceID" : "12345", "executeStatus" : 1, "params" : { "type" : "Fast", "extra" : [ "DefaultPwd" ], "excludeVulScanTypes" : [ 0, 4, 5 ] }, "created" : ISODate("2015-07-14T14:03:25.783Z"), "modified" : ISODate("2015-07-14T14:03:25.783Z"), "_id" : ObjectId("55a516ade25adfc7dfe31f52") }

http://127.0.0.1:3000/api/v1/commands/55a516ade25adfc7dfe31f52

{"deviceID":"empty","type":2,"command":1,"executeStatus":1,"progress":5,"params":{"type":"Fast","extra":["DefaultPwd"],"excludeVulScanTypes":[0,4,5]},"created":"2015-07-14T14:03:25.783Z","modified":"2015-07-14T14:03:25.783Z","id":"55a516ade25adfc7dfe31f52","result2":[{"test1":1},{"test2":1},{"test3":1},{"test4":1}]}

==

##### version before 1.4.5 without this issue

{ "deviceID" : "empty", "type" : 2, "command" : 1, "progress" : 5, "routerID" : "12345", "result" : [ { "test1" : 1 }, { "test2" : 1 }, { "test3" : 1 }, { "test4" : 1 } ], "createdByDeviceID" : "12345", "executeStatus" : 1, "params" : { "type" : "Fast", "extra" : [ "DefaultPwd" ], "excludeVulScanTypes" : [ 0, 4, 5 ] }, "created" : ISODate("2015-07-14T14:00:27.605Z"), "modified" : ISODate("2015-07-14T14:00:27.605Z"), "_id" : ObjectId("55a515fb5b888c7cdf6897bd") }

http://127.0.0.1:3000/api/v1/commands/55a515fb5b888c7cdf6897bd

{"deviceID":"empty","type":2,"command":1,"executeStatus":1,"progress":5,"result":[{"test1":1},{"test2":1},{"test3":1},{"test4":1}],"params":{"type":"Fast","extra":["DefaultPwd"],"excludeVulScanTypes":[0,4,5]},"created":"2015-07-14T14:00:27.605Z","modified":"2015-07-14T14:00:27.605Z","id":"55a515fb5b888c7cdf6897bd"}

**Comment by raymondfeng** [comment]
Good catch. I was able to reproduce it and opened an issue against mongodb driver 2.x (which we use starting from loopback-connector-mongodb@1.5.0). 

https://jira.mongodb.org/browse/NODE-505.

**Comment by christkv** [comment]
pushed 2.0.38 to npm with fix.

**Comment by christkv** [comment]
sorry 2.0.39

**Comment by raymondfeng** [comment]
@christkv Thank you for the quick fix!

**Comment by williamchang73** [comment]
Thanks for the fix !
