### ISSUE TITLE
How to encrypt mongodb database credentials in data-sources?

### ISSUE THREAD

**Issue by bharathkontham** [strongloop/loopback-connector-mongodb#161]
Is it possible to encrypt mongodb credentials and load them into data-sources? If so how to do it?

**Comment by raymondfeng** [comment]
You can use server/datasources.local.js to programmatically export an object representing the DS config. See http://docs.strongloop.com/display/LB/datasources.json#datasources.json-Environment-specificconfiguration.

```
var username = decrypt(...);
var password = decrypt(...);
module.exports = {
  username: username,
  password: password
}
```
