### ISSUE TITLE
belongsTo with redis connector model

### ISSUE THREAD

**Issue by behrad** [strongloop/loopback-connector-mongodb#162]
I'm trying to build a `belongsTo` from my mongo model to a redis model, but nothing seems to work!
Can anyone point me somewhere I can debug it !?

**Comment by smartmouse** [comment]
@behrad  Do you still have the issues? What node version , npm version, OS and LB version did you use? 
May be retried with the latest Loopback 3 and let us know if that works for you?
 Thank you.

**Comment by ssh24** [comment]
@behrad You cannot create relationships between two models that exist in two distinct datasources. You need to discover and migrate either one of the model to one of the datasource (mongo or redis in this case), and once you have both the models in the same datasource, you can create [loopback relations](https://loopback.io/doc/en/lb2/Creating-model-relations.html).

Closing this story as the question has been answered. Feel free to reopen if needed.
