### ISSUE TITLE
Honor type 'number' for auto-generated ids

### ISSUE THREAD

**Issue by simoami** [strongloop/loopback-connector-mongodb#165]
the documented type number doesn't work if the inserted record doesn't have an id. The generated id is a string in the form: `55bef3c66b07d5602d1b93f6`. The presence hex characters prevents the type number from working.

The example from the LB [documentation](http://docs.strongloop.com/display/public/LB/MongoDB+connector) implies that this is possible:

```
    _id: { type: Number, id: true }
```

Same thing in [id.test.js](https://github.com/strongloop/loopback-connector-mongodb/blob/master/test/id.test.js):

```
var Customer = ds.createModel('customer', {seq: {type: Number, id: true}, name: String, emails: [String], age: Number});

Customer.create({
      // seq: 1, // do not pass a seq, to let mongodb generate a number
      name: 'John1',
      emails: ['john@x.com', 'john@y.com'],
      age: 30
    }, function(err, customer) {

      // asset `customer.seq` is of type number
      ...
    });

```

The source code for [create()](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L253) clearly doesn't handle this properly.

```
    } else if (idType === Number) {
      var num = Number(idValue);

      if (!isNaN(num)) { <<<<< This part gives up on auto-generated ids like `55bef3c66b07d5602d1b93f6`
        idValue = num; <<<<<< ends up returning a string, thus violating the Number type
      }

    }
```

**Comment by simoami** [comment]
For reference the [mongoose-auto-increment](https://github.com/codetunnel/mongoose-auto-increment) module can add this functionality and can be used here for ids of type number.

**Comment by raymondfeng** [comment]
Unfortunately, mongodb doesn't support DB-generated number ids. To allow client-side number ids, you need to do two things:

1. Disable the DB auto generation by setting `generated` to `false`, for example: `{id: {type: 'number', id: true, generated: false}`.

2. Use `defaultFn` to generate number ids on the client side.

**Comment by simoami** [comment]
Thanks @raymondfeng, but I see that MongoDB actually have a way of supporting it. See the official documentation: http://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/

This is btw, the same technique used by mongoose-auto-increment and mongoose-simpledb. See [want to get rid of objectid altogether and use a simple incrementing number _id](https://github.com/codetunnel/mongoose-simpledb#want-to-get-rid-of-objectid-altogether-and-use-a-simple-incrementing-number-_id)

**Comment by raymondfeng** [comment]
In the future, we could use the technique from http://docs.mongodb.org/manual/tutorial/create-an-auto-incrementing-field/ to implement the auto-incrementing ids. That requires a bit change in how connector decides the generated id type and enforce the id generation as part of `create`. Patches are welcome.

**Comment by simoami** [comment]
Thanks for clarifying. Maybe if I get sometime, I can look into it. but for now I ended up using objectid which can have architectural advantages over number-based increments.

**Comment by simoami** [comment]
I found another problem with loopback in the HttpContext process of [coercing arguments of type 'any'](https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L200). All [shared methods](https://github.com/strongloop/loopback/blob/0f9dd93abacf451f09fff9a6d99ec4d13d1c2a29/lib/persisted-model.js#L583) define `id` as type 'any', which leads to [converting](https://github.com/strongloop/strong-remoting/blob/master/lib/http-context.js#L293) data ids such as  `id: '237'` to `id: 237`. 

This is obviously a problem with MongoDB's object ids. They are represented in hexadecimal like `55bd99e665abcf4f243c3014`, but a hexadecimal number can be composed of pure digits. If such case is possible, the coercion will mess up queries. MongoDB is type sensitive, and findById(2) and findById('2') are not equivalent.

Any thoughts?

**Comment by ssh24** [comment]
@simoami I am not sure I understand your last post correctly. The connector does not coerce string types to numerical value for any query. Hence `findById(2)` and `findById('2')` are two completely different queries.

The original issue has been resolved. To allow client-side numerical id, do the following:
```
1. Disable the DB auto generation by setting `generated` to `false`, for example: `{id: {type: 'number', id: true, generated: false}`.
2. Use `defaultFn` to generate number ids on the client side.
```

Closing this story as a result. Feel free to reopen if needed.

**Comment by simoami** [comment]
@ssh25 After 2 years, the LOC links I referenced from the master branch are no longer accurate. Was I was trying to say is that mongodb ids are strings in nature. But strong-remoting will continuously attempt to convert an id to a number if it sees an opportunity. That is if your were in bad luck and stored an id that is all digits as string, it will be  queried as number because of the coercion which produces no results.
