### ISSUE TITLE
Add the ability to perform bulk updates

### ISSUE THREAD

**Issue by pulkitsinghal** [strongloop/loopback-connector-mongodb#170]
1. I imagine that first, juggler and/or connectors would need to expose an abstract methodName/API for bulk updates ... that individual connectors may or may not implement.
2. Then mongodb connector could reuse something like the following (not exactly ofcourse) as a base for bulk updates: https://gist.github.com/pulkitsinghal/5e9df647366f1b5e4d32 ... My code:
   1. does not address what happens to operation hooks (ignores it)
   2. does not reuse the auto-cast magic of loopback from strings to objectids (manually omits them)

cc @kamal0808 @aquid

**Comment by pulkitsinghal** [comment]
@superkhau - is there an internal roadmap for this maybe?

**Comment by superkhau** [comment]
hi pulkit, long time to talk. ;)

Bulk operations is definitely something I will bring up during our discussions this week. It is definitely somewhere on the roadmap, but I'm not sure how high it is in terms of priority.

**Comment by jaime-franco** [comment]
Any news on this guys?

**Comment by pulkitsinghal** [comment]
@jaime-franco - part of my team was a bit under the weather on thu/fri
we are hoping to get this out the door by this week *fingers crossed*

**Comment by BoLaMN** [comment]
i needed this functionality as well so i wrote a mixin to help https://github.com/BoLaMN/loopback-mongodb-bulk-mixin see readme on how to use

cheers
