### ISSUE TITLE
Slow creation of access tokens

### ISSUE THREAD

**Issue by faustomorales** [strongloop/loopback-connector-mongodb#173]
For some reason, when Loopback creates access tokens in my application, they take a really, really long time. It happens when I run the application from a server, but not from my laptop (both are connected to MongoLab). Once the login takes place, performance is the same between the two. Any idea what the cause may be? An example log is provided below.

````
loopback:connector:mongodb create +58s AccessToken { id: 'BDvH79mPtrYOs3xF65AYEyJiWsjYefbt8n52WHnWlDFZWBi518kKzJZs0ZQdgyNv',
  ttl: 1209600,
  created: Sat Aug 22 2015 23:08:54 GMT-0500 (CDT),
  userId: 55c92d0ed1af5d1fb40af658 }
````

**Comment by ainesophaur** [comment]
Is the OS the same between the laptop and server? From what I can tell if
you have build tools and compilers available it'll try to compile bson from
c++

Try setting some debug strings and see if it hints to anything

https://docs.strongloop.com/display/public/LB/Setting+debug+strings

**Comment by faustomorales** [comment]
OS is not the same. The laptop is OS X Yosemite. The server is Raspian (it's a Raspberry Pi). I tried setting the mongodb connector strings but the only thing I see different is the time to complete requests. Is there another set of debug strings I should try for comparison?

**Comment by ainesophaur** [comment]
I believe it's more related to the hardware vs software. When it creates
the access token it generates a bson encrypted token which wouldn't be too
fast at 750 MHz

**Comment by faustomorales** [comment]
You are so, so right. Turns out that, in order to avoid a binary dependency, there was a switch to use bcryptjs by default unless native bcrypt was available. This is the subject of strongloop/loopback#892, though, of course, I didn't know that until you made your observation. All of my problems were solved in one line at the terminal (explained in the referenced issue, and below for convenience).

```
npm install bcrypt --save
````
