### ISSUE TITLE
Between dates

### ISSUE THREAD

**Issue by victorhqc** [strongloop/loopback-connector-mongodb#176]
I'm trying to filter a query using two dates, I've read that in MongoDB you can use something like this:

```
db.Collection.find({
  date_field: {
    $gte: ISODate('2015-01-01'),
    $lt: ISODate('2015-01-02')
  }
});
```

It does work in a noramal MongoDB query, but when I try to adapt this in Loopback I get a weird result as if it was ignoring the second parameter.

```
Collection.find({
  where: {
    date_field: {
      gte: new Date('2015-01-01'),
      lt: new Date('2015-01-01')
    }
  }
});
```

I also read that Loopback has a method called `between` and it does what I want but it seems weird that I can't get it properly done with a regular where query. Am I doing something wrong?

**Comment by ssuarezbe** [comment]
Hi, I have the same problem.

Then I checked the code and I realized that the loopback-connector-mongodb do not support $gte or $lte by date.

I suppose that a regular expression must be added to check if the parameter could be a Date or not, to solve the problem. Right now I do not have time to solve the problem but I could offer you a solution:


Just create a native mongodb connection, add a new Remote method and execute the query via this new native connection.

Here is the code:

```javascript
/* server/server.js */

/*
  Because the loopback-mongo-connector DO NOT support all the expected operations,
  then a native mongo connection is created to be used when is needed.
*/
var create_native_mongo_connection = function(){
  var MongoClient = require('mongodb').MongoClient;
  // Connection URL
  var url = 'mongodb://localhost:27017/your-db';
  // Use connect method to connect to the Server
  MongoClient.connect(url, function(err, db) {
    console.log("Connected correctly to Mongo server");

    app['mongo-native-conn'] = db;
    //db.close(); // WARNING must be closed correctly
  });
}

app.start = function() {
  // start the web server
  return app.listen(function() {
    app.emit('started');
    console.log('Web server listening at: %s', app.get('url'));
    // Custom Function calling for native_mongo_connection
    create_native_mongo_connection();
  });
};
```

Because I add the connection to the GLOBAL var **app**, you can use it anywhere, for example:

```javascript
/* common/models/test_model.js */
module.exports = function(TestModel) {

  TestModel.native_query = function(params, cb){

   var mongo_conn = TestModel.app['mongo-native-conn'];
   var collection = mongo_conn.collection('your-collection');
   // Find some documents 
   collection.find({}).toArray(function(err, docs) {
     cb(null, docs);
   };
  }

  TestModel.remoteMethod (
    'native_query',
    {
      http: {path: '/native_query', verb: 'post'},
      accepts: {arg: 'params', type: 'Object', http: { source: 'body' } },
      returns: {arg: 'results', type: 'object'}
    }
  ); 

};
```

**Comment by ssuarezbe** [comment]
Related tickets:
https://github.com/strongloop/loopback/issues/303

**Comment by joeauty** [comment]
I'm having this same problem, and for me it looks like neither ISO date strings nor timestamps work, e.g.:

{"where":{"dateStart":{"gt":1446953123185},"dateExpire":{"lt":1446953123185}}}

**Comment by donratta** [comment]
I seem to be having the same issue too. Anyone with any luck on this?

**Comment by vasanthps-rm** [comment]
Any updates on this issue?

**Comment by yshing** [comment]
It seems that the date compare only works if date is passed as String.
And between filter doesn't works while ```?filter[where][and][0][postDate][lt]=2016-01-27&filter[where][and][1][postDate][gt]=2016-01-26``` returns correct result

**Comment by Josurom** [comment]
I have the same problem.
In mongodb the sentence is:

            "activity.date" : {
                "$gte" : ISODate("2013-06-01T00:00:00.000+0000"), 
                "$lte" : ISODate("2013-06-30T00:00:00.000+0000")
            }

But in loopback I can't use between (I use moment for the dates):

"activity.date" : {
                                   between: [desde.format("YYYY-MM-DDT00:00:00.000Z"),
                                                   hasta.format("YYYY-MM-DDT00:00:00.000Z")]
                          }

Any solution?

Thanks

**Comment by virendra656** [comment]
Solution :  Use between operator of loop back and if you are using third party library like moment or something then do not pass moment dates directly in between operator but rather use new Date() along with moment date object.

 where: {
        dateTime: {
          between:[new Date(sd), new Date(ed)]
        }
      },

**Comment by ssh24** [comment]
You can use the `between` operator for dates or use `gt|gte|lt|lte` operator as well. 

Please note, **between returns true if the value is between the two specified values: greater than or equal to first value and less than or equal to second value.** 

Read more about [between operators](https://loopback.io/doc/en/lb3/Where-filter.html#between).

Here is a sample code snippet:

**model-definition.js**
```json
{
  "name": "PastEmployee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "startDate": {
      "type": "date"
    },
    "endDate": {
      "type": "date"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mongoDs;
  var PastEmployee = app.models.PastEmployee;

  var data = [{
    name: 'Foo',
    startDate: '2012-05-10 10:00',
    endDate: '2014-04-29 17:00',
  }, {
    name: 'Bar',
    startDate: '2010-01-05 10:00',
    endDate: '2016-08-28 17:00',
  }, {
    name: 'Baz',
    startDate: '2013-03-10 10:00',
    endDate: '2014-01-28 17:00',
  }];

  db.automigrate(function(err) {
    if (err) throw err;
    console.log('\nAutomigrate completed');

    PastEmployee.create(data, function(err, result) {
      if (err) throw err;
      console.log('\nCreated instance: ' + util.inspect(result));

      PastEmployee.find({where: {startDate:
          {between: ['2010-01-05 10:00', '2012-05-10 10:00']}}},
      function(err, result) {
        if (err) throw err;
        console.log('\nFound instance: ' + util.inspect(result));
      });
    });
  });
};
```

**output**
```bash
sakibs-mac:mongodb-176 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { name: 'Foo',
    startDate: Thu May 10 2012 10:00:00 GMT-0400 (EDT),
    endDate: Tue Apr 29 2014 17:00:00 GMT-0400 (EDT),
    id: 594804527eaf883d928055f1 },
  { name: 'Bar',
    startDate: Tue Jan 05 2010 10:00:00 GMT-0500 (EST),
    endDate: Sun Aug 28 2016 17:00:00 GMT-0400 (EDT),
    id: 594804527eaf883d928055f2 },
  { name: 'Baz',
    startDate: Sun Mar 10 2013 10:00:00 GMT-0400 (EDT),
    endDate: Tue Jan 28 2014 17:00:00 GMT-0500 (EST),
    id: 594804527eaf883d928055f3 } ]

Found instance: [ { name: 'Foo',
    startDate: Thu May 10 2012 10:00:00 GMT-0400 (EDT),
    endDate: Tue Apr 29 2014 17:00:00 GMT-0400 (EDT),
    id: 594804527eaf883d928055f1 },
  { name: 'Bar',
    startDate: Tue Jan 05 2010 10:00:00 GMT-0500 (EST),
    endDate: Sun Aug 28 2016 17:00:00 GMT-0400 (EDT),
    id: 594804527eaf883d928055f2 } ]
```

Closing this as the issue does not exist anymore. Feel free to reopen if needed.

**Comment by selahattinunlu** [comment]
@virendra656 Thanks man "between" works for me!
