### ISSUE TITLE
Case insensitive queries don't appear to be working anymore

### ISSUE THREAD

**Issue by joncarlson** [strongloop/loopback-connector-mongodb#178]
I have a Tag model and I've added a tag with the name: 'Technology'

In Explorer, if I use the filter {"where":{"name":{"like":"Tech","options":"i"}}}, I get back the above tag.

However, if I change the filter to {"where":{"name":{"like":"tech","options":"i"}}}, there are zero results.

This was previously working until I nuked my node_modules directory and reinstalled.

**Comment by Amir-61** [comment]
Hey @joncarlson,

I just tried your example on my end and there was no problem; I used version `1.13.1` for `loopback-connector-mongodb`. Could you please upgrade your packages and try again; if the problem persists could you please create a sample repo using our [loopback-sandbox](https://github.com/sharkinsspatial/loopback-sandbox) to re-produce the issue?

Also, if your problem gets solved by upgrading packages, please let us know, so we can close this ticket!

Thansk a lot

**Comment by Amir-61** [comment]
Hi @joncarlson,

I tried this issue and it seems it is working, if you still have the same issue, could you please provide a sample repo, re-producing the issue? If the problem does not persist, I will be closing this ticket soon.

Thanks!

**Comment by joncarlson** [comment]
@Amir-61 I just tried the example again and it's working now. One of the upgraded packages must have fixed it. Thanks!

**Comment by Amir-61** [comment]
Glad that the problem is solved! Thanks!
