### ISSUE TITLE
Nested Foreign Keys

### ISSUE THREAD

**Issue by grindfuk** [strongloop/loopback-connector-mongodb#180]
Hi,
Just started using loopback and was wondering:
Can foreign keys be nested in a mongo document? 
For example, can you have

```
{
  "name": "supplier",
 ...
  "relations": {
    "supplier_acct": {
      "type": "hasOne",
      "model": "account",
      "foreignKey": "suppliers.supplierId"
    }
 ...
}
```

**Comment by ainesophaur** [comment]
The foreign key would just be supplierId. If you don't provide a specific
foreign key then loopback will set it to model + "Id"

Your mongo entry should then have just the regular properties along with
the ObjectId of the relation target

If I'm misunderstanding your question please let me know.

**Comment by grindfuk** [comment]
Thanks for the response.
Sorry, I should have clarified the models. I imagine an account document instance would be something like this:
```
{
  "type": "account",  
  "name": "Office Account", 
  "suppliers": {
    "supplierName": "Paper Supplier Inc",
    "supplierId": {{mongo _id}} 
  }
}
```
where the mongo _id is deeply nested inside some json. If you hoist the ref to a first level key, you get the example that you provided which is a nice work-around. I was just wondering whether this was possible since if you could, you could namespace and group refs

**Comment by ainesophaur** [comment]
I don't believe you can do directly what you're trying to. Are you working
with existing data that is already in that format and you're trying to
migrate to strongloop? If so you can just use a hasMany relation and set
the foreignKey to supplierId. The name of the supplier won't be returned
when you query the parent model unless you then query/lazy load the
relation.

**Comment by grindfuk** [comment]
Thanks.
It is how the data is currently formatted but it is not hard to change on MongoDB.
So, the foreign keys *must* be hoisted to the top level?
Maybe something like:
```
{
  "type": "account",  
  "name": "Office Account", 
  "supplierId": {{mongo _id}},
  "supplierName": "Paper Supplier Inc",  
}
```

**Comment by ainesophaur** [comment]
No, the way you currently have the data would be fine. You would need to
create a hasMany/belongsTo or hasAndBelongsToMany relation from the top
level model to the supplier model. The relation name (or using the 'as'
property) is what gets read from the top level keys.

Account model

{
  properties: {
    type: String,
    name: String
  },
  relations: {
    suppliers : {
      foreignKey: "supplierId",
      type : " hasAndBelongsToMany"
    }
  }
}

If you can share the current schema for the two models I can let you know
what to put in loopback.

I also need to know what's the relation between the models. Do Many
suppliers belong to Many different accounts? Do you need a bidirectional
relation where you can access each model in the relation from either side?
