### ISSUE TITLE
Node process crashed /loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:98

### ISSUE THREAD

**Issue by schitransh** [strongloop/loopback-connector-mongodb#181]
Hi 
I am getting error like
/loopback-connector-mongodb/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });

and i my looback find query callback err and response object was null.
also my server run was crashed.

Then i have added console log above  and found mongo was returing this error 2 time 

`{
    [
        MongoError: exception: E11000duplicatekeyerrorindex: lcms.rule.$depid_1_rule_1_priority_1_policy_effective_info.date_1dupkey: {
            : "epttprod",
            : "/(?:.*)sonim\/ XP6700 Blackberry\/4.1.1(?:.*)/",
            : 1,
            : "2015-10-15T00:00:00"
        }
    ]name: 'MongoError',
    message: 'exception: E11000duplicatekeyerrorindex: lcms.rule.$depid_1_rule_1_priority_1_policy_effective_info.date_1dupkey: {
        : "epttprod",
        : "/(?:.*)sonim\\/ XP6700 Blackberry\\/4.1.1(?:.*)/",
        : 1,
        : "2015-10-15T00:00:00"
    }',
    errmsg: 'exception: E11000duplicatekeyerrorindex: lcms.rule.$depid_1_rule_1_priority_1_policy_effective_info.date_1dupkey: {
        : "epttprod",
        : "/(?:.*)sonim\\/ XP6700 Blackberry\\/4.1.1(?:.*)/",
        : 1,
        : "2015-10-15T00:00:00"
    }',
    code: 11000,
    ok: 0
}`

It should come in server callback in error object as per below code. please let me know how i will handle this error?
actually getting 

Error :  null
responseData :  null

```
   this.ruleTbModel.upsert( policyData, function( err , responseData )
    {
        console.log("Error : ", err);
        console.log("responseData : ", responseData);
        if( err )
        {
            callback( err );
            return;
        }
        callback( null , responseData );
    });
```

Thanks
Chitransh

**Comment by ashutoshdev** [comment]
I am also getting the same error .

**Comment by smartmouse** [comment]
What environment do you see the error? What OS and what Node /NPM version?
and which loopback version?

**Comment by ssh24** [comment]
This issue does not exist anymore. Closing the story as a result. Feel free to reopen if needed.
