### ISSUE TITLE
document OptimisedfindOrCreate

### ISSUE THREAD

**Issue by AlmaasAre** [strongloop/loopback-connector-mongodb#185]
![image](https://cloud.githubusercontent.com/assets/1777366/10851697/6f1a4a74-7f24-11e5-87dd-9a17f25d4dfd.png)

Had a hard time making findOrCreate work as i expected, until i noticed this in the connector.. Don't know if this is the correct repo, but this should be documented!

**Comment by Amir-61** [comment]
Hi @AlmaasAre 

Could you please put the link to the code you got the screen shot from? Thanks for helping us to improve the documentation.

Thanks!

**Comment by AlmaasAre** [comment]
https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L90

**Comment by kjdelisle** [comment]
@Amir-61 Since you wrote the feature, please update the documentation accordingly.

**Comment by Amir-61** [comment]
>@Amir-61 Since you wrote the feature, please update the documentation accordingly.

@kjdelisle I did not implement it.

**Comment by ssh24** [comment]
Here is the link for the documentation on the [findOrCreate](https://apidocs.strongloop.com/loopback/#persistedmodel-findorcreate) function.

Closing the issue as resolved. Feel free to reopen if needed.
