### ISSUE TITLE
creating entity with relation stores the foreign key as plaintext instead of ObjectID

### ISSUE THREAD

**Issue by Ijmir** [strongloop/loopback-connector-mongodb#186]
https://github.com/Ijmir/loopback-post-relation
with reproduction steps

I have feed and comment models.
comments belongsTo feeds with foreign key feedRef and relation name feed.
feedRef field is an ObjectID - defined in boot script.

``` json
{
  "name": "comment",
  "base": "PersistedModel",
  "idInjection": true,
  "validations": [],
  "relations": {
    "feed": {
      "type": "belongsTo",
      "model": "feed",
      "foreignKey": "feedRef"
    }
  },
  "acls": [],
  "methods": [] 
}
```
1. When I save a comment with feed object (with _id) attached I see that in mongodb feedRef is stored as plaintext and feed is discarded
2. When I save a comment with feedRef attached I see that in mongodb feedRef is stored as ObjectID

From 1 I understand that create handles the relation because it translates feed to feedRef, but the ObjectID is plaintext. In 2 I can see that ObjectID is stored correctly.

Is it a bug? or create method with relations shouldn't have been working in the first place?
*maybe related to loopback-connector-mongodb or loopback-datasource-juggler

**Comment by ainesophaur** [comment]
What does your feed model look like? I'd imagine you have a hasMany
relation from feed to comments.  From what I see so far it's doing what its
supposed to do.

When you created comment with the feed object it'll just save the objectId
and loopback juggler makes the matching of the comment when you query feed
for its comments.

If you wanted it to actually save comments inside of feed without having to
query the relationship then you'd need to use an embedsMany relation.

**Comment by Ijmir** [comment]
I am not sure that we are on the same page:

1. saving comment with feed object results in feedRef field being saved as a string  
2. saving comment with feedRef field results in feedRef field being saved as an ObjectID
3. I don't query for feed entity nor do I try to save feed with comments

It seems wrong. Is it by design or its a bug?  

You can look at the repo I have created.

**Comment by ainesophaur** [comment]
Would you be able to add a unit test or script file which produces both
results? This way I can understand the end result properly, because I never
get the related object saved as a string.

**Comment by ainesophaur** [comment]
Also what version of mongo and driver are you using?

**Comment by Ijmir** [comment]
It's all in the repo I posted. mongo connector 1.13.0 mongo 2.0.47.
running create commands from node will work, but the bug occurs in the explorer or REST interface.
I posted a reproduction steps in the repo README.md.

**Comment by jjhesk** [comment]
i think i have the same issue.
1++++++++++++++++

please fix.
