### ISSUE TITLE
How to create a database at runtime?

### ISSUE THREAD

**Issue by robinskumar73** [strongloop/loopback-connector-mongodb#187]
I want to create a loopback database at run time for each user that signup. Any help how to?

**Comment by Amir-61** [comment]
I believe we don't have support to create a **database** at runtime; But could you please give me use-cases for this feature?

Thanks!

**Comment by ssh24** [comment]
Not sure how important this is. Creating a database in mongodb is as simple as `use <database_name>`. Still keeping it as a feature request for the product owners to decide.
