### ISSUE TITLE
remoteMethod 'all'

### ISSUE THREAD

**Issue by paulomcnally** [strongloop/loopback-connector-mongodb#194]
Hi.

I have remote method with name **all**.

This remote method have:

```
MyModel.find({
  order: 'name ASC'
}, cb)
```

Order filter dont work, but renaming remote method to **allData** work ok.

This make conflicts? https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L657

**Comment by ssh24** [comment]
You cannot name a remote method with the same name as the prototype functions in the connector. **all** is a prototype function in the [mongodb connector](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L1015).

Closing this issue. Feel free to reopen if needed.
