### ISSUE TITLE
Wrong positioning of db options in lib/mongodb.js#initialize()

### ISSUE THREAD

**Issue by benkroeger** [strongloop/loopback-connector-mongodb#201]
While debugging some other issue, I found that the `initialize` function actually sets database options like `safe` and `w` (`writeConcern`) on the settings that are passed on the the native-mongo-db client's [connect](http://mongodb.github.io/node-mongodb-native/2.0/api/MongoClient.html#.connect) method.  
This method actually would expect **db options** in a hash property of the settings called `db`

``` js
settings = settings || {};
settings.db = settings.db || {};
settings.db.safe = true;
settings.db.w = 1;
```

Also, you can define other options for your MongoClient in the `datasources.json` files  

``` js
"foo": {
    "name": "foo",
    "connector": "mongodb",
    "hostname": "localhost",
    "port": 27017,
    "database": "foo-dev",
    "username": "my-user",
    "password": "shhh it's a secret!!",
    "server": {},
    "mongos": {},
    "replSet": {},
    "db": {}
  }
```

**Comment by Amir-61** [comment]
@benkroeger,

Could you please clarify more if there is something wrong? As far as I can say In [initialize method](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L56-L72) `dataSource.settings.safe` and `dataSource.settings.w` can be undefined and in this case the default values will be set.

Thanks a lot!

**Comment by benkroeger** [comment]
@Amir-61 it is correct, that this module would use default values for the settings `safe` and `w`. However, the way these settings are passed on to the [MongoClient.connect](http://mongodb.github.io/node-mongodb-native/2.0/api/MongoClient.html) method is not correct. The constructor will simply ignore them, since the only valid options are `uri_decode_auth`, `db`, `server`, `replSet`, `mongos` and `promiseLibrary`.
The writeconcern settings you're intending to provide would be a sub-key in  the `db` option. I.e. you would need to provide `dataSource.settings.db.w` for the [writeconcern](https://docs.mongodb.org/v3.0/reference/write-concern/). The `safe` option on the other hand doesn't seem to be a valid option in the [mongodb-native driver](http://mongodb.github.io/node-mongodb-native/2.0/api/index.html) at all.
Might it be, that you had the [mongoose implementation](http://mongoosejs.com/docs/guide.html#safe) in mind? Mongoose uses this `safe` schema option to define [writeconcern](https://docs.mongodb.org/v3.0/reference/write-concern/) default options.

**Comment by Amir-61** [comment]
@benkroeger Would you like to submit a patch?

**Comment by benkroeger** [comment]
PR submitted

**Comment by Amir-61** [comment]
@benkroeger Thanks a lot for the patch; someone will review it soon.
