### ISSUE TITLE
Incompatibility between enableOptimizedFindOrCreate and validatesUniquenessOf

### ISSUE THREAD

**Issue by MichaelDiguet** [strongloop/loopback-connector-mongodb#205]
Hi ,
I am very happy to use the new option 'enableOptimizedFindOrCreate'.

It is very important for my application that findOrCreate operations are atomic. This wasn't the case before enableOptimizedFindOrCreate, it is now the case.

**Unfortunately, there is a big issue related to the usage of enableOptimizedFindOrCreate:**
It does not work with Models using the 'validatesUniquenessOf' to ensure the unicity of one of their properties. This is the case for example of the User built in model.

The first time findOrCreate is called, it works as a charm and create the new instance. However, the second time, it fails (it should just return the existing instance):

`ValidationError: The 'User' instance is not valid. Details: 'email' Email already exists (value: "luckyLuke@yelloan.com")`

**Comment by jamesjjk** [comment]
+1 incompatible function for atomic updates.

**Comment by taoyuan** [comment]
Could set `Model.settings.automaticValidation = false` or in model definition json:

```js
{
  "name": "Customer",
  "automaticValidation": false,
  ...
}
```

**Comment by smartmouse** [comment]
@MichaelDiguet  does @taoyuan  's solution works for you?

**Comment by MichaelDiguet** [comment]
@taoyuan, @smartmouse, thanks guy for your answers !
This is pretty cool that this solution exist. However, it would apply globally to the model, and automatic validation are useful elsewhere in our code. What we did is to deactivate automaticValidation each time we call findOrCreate.
@fabong could you please share the code ?

**Comment by fabong** [comment]
Yes, we set the `validate` option of findOrCreate, like this : https://github.com/fabong/loopback-component-passport/commit/1f76e5f251da0f5ea34eeda638b1a8bf2d07619f
