### ISSUE TITLE
[BREAKING] 0.13.1 Id coercion results in id: 'undefined'

### ISSUE THREAD

**Issue by BerkeleyTrue** [strongloop/loopback-connector-mongodb#206]
Using the static `create` method with a data object will result in an id value equal to `undefined`

This is a breaking change.

Seems that [this](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L237) will coerce id's into strings, but when the id  undefined, it gets coerced into a string `undefined` and saves to the db with that id. Trying to use the create method multiple times now results in duplicate id errors because it will always create the model with id set as `'undefined'`.

The previous behavior was not to coerce the id into a type but to return it as it was if not a string.

**Comment by jjhesk** [comment]
@BerkeleyTrue Does it mean when i pass in a string of 12 hex characters or a string of 24 hex characters it will convert to ObjectId automatically?
