### ISSUE TITLE
Can't get results by using $in as query filter for mongodb datasource

### ISSUE THREAD

**Issue by TidyHuang** [strongloop/loopback-connector-mongodb#217]
The following query filter works well by MogoDBHub and returns several expected entries, but get empty array when using node API to query mongoDB datasource. An '$in' querying example: { services: { '$in': [ 'baidu' ] } }

Any one find the same issue?

**Comment by skalyanapu-mtuity** [comment]
Probably this could solved already , but may useful for new people :
The query has to be like so : {where:{ services: { in: [ 'baidu' ] } }}

**Comment by joneldiablo** [comment]
Hi there!
I have a problem filtering some data, the database is postgree.
there is an array field: `"category": ["string"]`
and I want filter elements which have category named "objectives", example of data:
```
[
....
{
"name": "xxxx",
"yyyyy": "zzzzz",
"category": ["general", "jjjjjj", ...., "objectives"]
}
....]
```

my filter is:
```
{
"where":{"category":{"in": ["objectives"]}}
}
```
I have try to many ways, with `"inq"` instead `"in"`... with the word only after "category", putting as array or without the array (looks like: `["objectives"]`  or `"objectives"` ) but ever gets empty array, how can I filter by the content of an array field? o.O
