### ISSUE TITLE
Race condition (multiple connections created)

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-connector-mongodb#220]
There's a race condition when `connect` is called multiple times. While Juggler keeps track of `dataSource.connecting`, it is not used on a lower-level inside the connector.

Here's a fix:

```
MongoDB.prototype.connect = function (callback) {
  var self = this;
  if (self.db) {
    process.nextTick(function () {
      callback && callback(null, self.db);
    });
  } else if (self.dataSource.connecting) {
    self.dataSource.once('connected', function() {
      process.nextTick(function () {
        callback && callback(null, self.db);
      });
    });
  } else {
    mongodb.MongoClient.connect(self.settings.url, self.settings, function (err, db) {
      if (!err) {
        if (self.debug) {
          debug('MongoDB connection is established: ' + self.settings.url);
        }
        self.db = db;
      } else {
        if (self.debug || !callback) {
          console.error('MongoDB connection is failed: ' + self.settings.url, err);
        }
      }
      callback && callback(err, db);
    });
  }
};
```

@raymondfeng care to take a look? I ran in to this while using Juggler standalone, and the script would not exit, even when properly closing the connection.

**Comment by raymondfeng** [comment]
Does the same problem occur to other connectors too?

**Comment by fabien** [comment]
I'm not 100% sure. It didn't happen with the memory connector - which is no surprise I guess.

In the standalone script I'm explicitly connecting all datasources, before I actually define or use any models. This effectively sets the status to `connecting`. However, as soon as I actually start using models, a connection attempts are made, causing the `db` property to be overwritten, and leaving 'zombie' connections behind. Ultimately, this prevented the script from exiting.

**Comment by raymondfeng** [comment]
Feel free to make a patch as you proposed.

**Comment by fabien** [comment]
@raymondfeng I've created a PR. In case you're interested, I pushed the project I was talking about:

https://github.com/fabien/independent-juggler

It eases some of the steps you'd otherwise have to go through when using Juggler independently from Loopback. In a way, I feel some parts of `loopback-boot` should have been implemented in `loopback-datasource-juggler` instead. Hence this helper module.

**Comment by Amir-61** [comment]
I'm closing this issue as the [PR#221](https://github.com/strongloop/loopback-connector-mongodb/pull/221) fixed this problem
