### ISSUE TITLE
is db.collection.distinct supported?

### ISSUE THREAD

**Issue by cchacons** [strongloop/loopback-connector-mongodb#224]
Hi guys, 

is db.collection.distinct() supported?
https://docs.mongodb.org/manual/reference/method/db.collection.distinct/

I got this error:
{"error":{"name":"TypeError","status":500,"message":"Event.distinct is not a function"

Thanks,
Carlos

**Comment by cchacons** [comment]
Can we get this supported? How difficult is to add support for this?

Thanks,
Carlos

**Comment by ahsanshafiq** [comment]
+1

**Comment by jerowe** [comment]
+1

**Comment by Amir-61** [comment]
AFAIK I don't believe if we have support for `is db.collection.distinct()`. @superkhau could you confirm? Would any of you like to submit a PR for that?

Thanks

**Comment by Amir-61** [comment]
Here is the list of accepted operations at the moment: https://github.com/strongloop/loopback-connector-mongodb/blob/7c717e4446f08210dec628295049835f9206a977/lib/mongodb.js#L469-L476

**Comment by yohanesgultom** [comment]
In case anyone need it, I successfully did it like this using `"loopback-connector-mongodb": "^1.15.2"`:

```
// product.js
Product.getTags = function (ctx, cb) {
    var productCollection = Product.getDataSource().connector.collection(Product.modelName),
        uniqueTags = productCollection.distinct('tags', function (err, items) {
            console.log(items)
            cb(err, items)
        })
}
```

**Comment by yohanesgultom** [comment]
@skalyanapu-mtuity you can add filter by passing it as `distinct` argument. In this example, I'm filtering the products by their `basePrice`:

```
Product.getTags = function (ctx, cb) {
    var productCollection = Product.getDataSource().connector.collection(Product.modelName),
        uniqueTags = productCollection.distinct('tags', {basePrice: {$gt: 50000}, function (err, items) {
            console.log(items)
            cb(err, items)
        })
}
```
In your case, maybe you want to use filter such as `{userId: 100}`. Since `Collection` is actually a part of [mongodb node.js native driver] (http://mongodb.github.io/node-mongodb-native/), I think almost all operators are supported CMIIW.

**Comment by ssh24** [comment]
Closing this issue as it is resolved. Feel free to reopen if needed.

**Comment by Amir-61** [comment]
@ssh24 please put the PR solving issue here. Thanks.

**Comment by ssh24** [comment]
There is no monogdb connector instance method that support this functionality. As specified above, it can be accomplished with something like this:

```js
Product.getTags = function (ctx, cb) {
    var productCollection = Product.getDataSource().connector.collection(Product.modelName),
        uniqueTags = productCollection.distinct('tags', {basePrice: {$gt: 50000}, function (err, items) {
            console.log(items)
            cb(err, items)
        })
}
```

**Comment by JohnHour89** [comment]
How to add the id for them when I separate the topic like this:

[
  "demo",
  "testing",
  "tssb"
]

I want to separate like this:

[
  {"1", "demo"},
  {"2", "testing"},
  {"3", "tssb"}
]
