### ISSUE TITLE
Filtering dates 

### ISSUE THREAD

**Issue by masalinas** [strongloop/loopback-connector-mongodb#225]
I'm using 1.13.3 version mongo connector, I'm trying filtering dates from mongodb configured like ISODate like this:

```javascript

var dateFrom = new Date('2016-01-10T00:00:00.000Z');

 Event.find ({ where: {organizationId: organizationId,
                                 date: {gte: dateFrom} }
            },
            function(err, value) {
                if (err) return cb(err);

                cb(null, value);
            })
```

But any register is recovered, it's a bug of the connector??, what solution I have to filter dates in mongodb.
 
Regards.

**Comment by masalinas** [comment]
I'll resolve the problem the date type was string and must be date

Regards

**Comment by Amir-61** [comment]
Hey @masalinas,

Is this issue good to be closed now?

Thanks!

**Comment by aniljaangra** [comment]
how can it be closed without getting any solution ... how to filter dates ?

**Comment by masalinas** [comment]
For it's good to be closed
Regards

**Comment by superkhau** [comment]
@0candy Can you take a look at this one? Should be a doc issue or a bug.

**Comment by 0candy** [comment]
@aniljaangra @masalinas has resolved his issues. He was using the wrong type for date. Closing this issue. Thanks!
