### ISSUE TITLE
No support for $bitsAnySet?

### ISSUE THREAD

**Issue by charlesdeuter** [strongloop/loopback-connector-mongodb#226]
Hi I'm trying to do a bitmask query, however it looks as if there is no support for the mongoDB $bitsAnySet query operator. 

I'm using a simple call, as such:
'Archive.find({where: {options: { $bitsAnySet: 15}}}, callback);'

the object attribute is configured as such:
'"options": {
    "type": "number",
    "required": true,
    "default": 12
}"'

'Can't canonicalize query: BadValue unknown operator: $$bitsAnySet'

removing the $ just gives the same error with one less dollar sign...

**Comment by ainesophaur** [comment]
That operator is available for mongodb driver 2.1 -- if you check the package.json for loopback-connector-mongodb it uses driver 2.0.35
