### ISSUE TITLE
npm test fails with error " Uncaught TypeError: Cannot read property 'lengthOf' of undefined "

### ISSUE THREAD

**Issue by vserrao** [strongloop/loopback-connector-mongodb#228]
After doing a clone of this repo and "npm install", when I try to do"npm test", I'm getting the error:  "Uncaught TypeError: Cannot read property 'lengthOf' of undefined". 
The console output locates the source of error at "node_modules/loopback-datasource-juggler/test/include.test.js:105:71" . 

Tracing to the above location, I tried to modify line number: 105 from "user.toJSON().should.have.property('posts').and.be.an.Array.with.lengthOf(0);" to "user.toJSON().should.have.property('posts').be.with.lengthOf(0); " . With this change the error goes away.

Please can you comment on this error whether it is a bug and the code change done inline.

Also, please let me know if I'm missing any dependency. 

Regards,
vserrao

**Comment by vserrao** [comment]
hi,

Any updates on this issue ?

**Comment by Amir-61** [comment]
It actually passes on the latest version. Please update your package.

Thanks!

**Comment by Amir-61** [comment]
I'm closing this issue now; please feel free to open a ticket if you run into the same issue.

Thanks!
