### ISSUE TITLE
Debug Strings with MongoDB connector 

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback-connector-mongodb#229]
I am trying to use debug strings filter with DEBUG=loopback:connector:mongodb
to find what could cause one of my queries to fail. However the result has a lot of information, the queries are only outputting 

```
loopback:connector:mongodb MongoDB: model=post command=find +16ms [ { '$and': [ [Object], [Object] ] }, [Function] ]
```

type of strings, which is not elaborate enough.

**Comment by barocsi** [comment]
Anyone who might want to see the latest queries for a collection in mongodb:
```
db.setProfilingLevel(2)
db.system.profile.find({"ns":"yourdatabase.yourcollectionname","op":"query"}).sort({"ts":-1}).pretty()
```

**Comment by 0candy** [comment]
@barocsi Thanks for sharing the debug info. Closing this as its not an issue.
