### ISSUE TITLE
"cannot dropAllIndexes when index builds in progress" during automigrate

### ISSUE THREAD

**Issue by mrfelton** [strongloop/loopback-connector-mongodb#231]
I'm getting the following when running `db.automigrate()` on a database that contains a lot of data.

  loopback:connector:mongodb automigrate +7ms
  loopback:connector:mongodb drop collection Campaign for model Campaign +3ms
  loopback:connector:mongodb create collection Campaign for model Campaign +3ms
  loopback:connector:mongodb drop collection Event for model Event +3ms
  loopback:connector:mongodb Error dropping collection Event for model Event:  +9ms { [MongoError: exception: cannot dropAllIndexes when index builds in progress]
  name: 'MongoError',
  message: 'exception: cannot dropAllIndexes when index builds in progress',
  ns: 'fc-dev.Event',
  nIndexesWas: 2,
  errmsg: 'exception: cannot dropAllIndexes when index builds in progress',
  code: 17348,
  ok: 0 }

**Comment by ssh24** [comment]
@mrfelton Do you have a concrete reproduction for this issue?
