### ISSUE TITLE
allowExtendedOperators documentation could be more clear.

### ISSUE THREAD

**Issue by Freyert** [strongloop/loopback-connector-mongodb#232]
I've been trying to set `allowExtendedOperators` all morning, but I can't seem to place it in the right place, and the documentation has conflicting advice: do I set it in `settings` or  `options`? I can't seem to set it when I call `createOrUpdate(document, options)` either.

**Comment by jmimi** [comment]
It is for mongodb datasources.
In `model.json`, set below block into `options` key
```
 "mongodb": {
      "collection": "models",
      "allowExtendedOperators": true
    }
```

**Comment by Amir-61** [comment]
Hey @Freyert 

Is this still an issue? Or your problem is solved?

Thanks!

**Comment by Amir-61** [comment]
I believe this issue has been resolved as you can set it in `dataSource.settings`; please see https://github.com/strongloop/loopback-connector-mongodb/blob/32d86c586a4904ba0a802dec8ed3dd3db90c816c/test/mongodb.test.js#L617

Closing this issue now...

Thanks!
