### ISSUE TITLE
mongo native GeoJSON and GeoIndex not compatible with loopback GeoPoint

### ISSUE THREAD

**Issue by Freundschaft** [strongloop/loopback-connector-mongodb#234]
I have implemented loopback with GeoPoint, but queries are quite slow due to nonexisting geoindexing.

Now when I use a geoJSON Ponit data structure, the problem is I cant use the GeoPoint feature for the near queries in loopback, is there a solution to bring these two things together?

Cheers

**Comment by Freundschaft** [comment]
apparently theres a pull request for this but it hasnt been merged https://github.com/strongloop/loopback-connector-mongodb/pull/68

**Comment by Amir-61** [comment]
> apparently theres a pull request for this but it hasnt been merged #68

Yes The PR will be merged soon hopefully..

**Comment by etsuo** [comment]
It looks like #68 was merged, and the query appears to be working correctly for simple filters where you're just searching on location... but introducing an `and` operator reverts it back to using a GeoPoint rather than a GeoJSON query... I opened a new issue here: #271

**Comment by 0candy** [comment]
Closing this issue as PR was merged.
