### ISSUE TITLE
record ids are not strings

### ISSUE THREAD

**Issue by Morriz** [strongloop/loopback-connector-mongodb#235]
IMO it is implied that id of type string should be a string.

It's now not possible to test two identical model id's (that have the same string value) by reference.

**Comment by Morriz** [comment]
To add to this, I found that it is now even impossible to test these id's using abstract equality (i.e. ==).
We now have to resort to doing this to circumvent failure:

```
someid + '' == anotherid + ''
```

What is going on here?

**Comment by ssh24** [comment]
By default, MongoDB ids are of type ObjectID. Using loopback you can enforce the id to be of type String and then you can test string equalities on it.

If the id is as it an ObjectID, you can convert it to a string upon a find request and still be able to test string equalities on it. Here is a sample model definition where you explicitly state the id to be of type String:

```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "id": true,
      "required": true
    },
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }, 
    "jobId": {
      "type": "number",
      "required": true,
      "id": true
    }
  },
  "validations": [],
  "relations": {
    "jobs": {
      "type": "hasOne",
      "model": "Job",
      "foreignKey": "jobId"
    }
  },
  "acls": [],
  "methods": {}
}
``` 

Hopefully, this answers your question.

**Comment by ssh24** [comment]
Closing this issue as it has been answered. Feel free to reopen if needed.
