### ISSUE TITLE
near filter not work property because connector not implements buildNearFilter

### ISSUE THREAD

**Issue by oscar-anton** [strongloop/loopback-connector-mongodb#236]
Recently i' ve detected an issue in near filter, when you do something like this:

`Mymodel.find({where:{near:{lat:latitude, lng:longitude}}})`

First, when loopback-datasource-juggler  checks geoSupport by checking buildNearFilter method, detects that mongodb connector not support near filter and executes in memory filter by accessing to all documents of the collection (this causes several performance issues).

Second, if you implements the method by extending the connector like this:

`app.dataSources.mongoDs.connector.buildNearFilter = function (query, near) {}`

The filter then applies the near filter in the right way, but now the order of results are wrong, because internally the query has by default the order field initialized with id (then order field collides with near filter), if you want to solve this:

`app.dataSources.mongoDs.connector.buildNearFilter = function (query, near) {
            query.order=[];
}`

I placed this code in my boot scripts and now all works like a charm!!

**Comment by Amir-61** [comment]
I believe this [PR](https://github.com/strongloop/loopback-connector-mongodb/pull/68/files) solves this problem. We will merge it soon. Thanks :-)

**Comment by oscar-anton** [comment]
Thanks @Amir-61 , nice solution that solves entire issue ;)

**Comment by ahmed-abdulmoniem** [comment]
@Amir-61 This will be merged when please?

**Comment by Amir-61** [comment]
@ahmed-abdulmoniem As you see it is being reviewed by one of the team leads. It will be merged soon. Thanks!

**Comment by ahmed-abdulmoniem** [comment]
Thanks

**Comment by 0candy** [comment]
PR has been merged, closing this issue.
