### ISSUE TITLE
Give a chance to enter the options for each query and remove default options

### ISSUE THREAD

**Issue by Lughino** [strongloop/loopback-connector-mongodb#237]
In database queries the object options is not passed. 
It would be very useful to be able to pass these options at the query level.
For example, if I wanted that for a specific query the `writeConcern` option is equal to 0 I could pass it to the query.

Also enter the default options for some queries, see [https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L317](url), is conceptually wrong, because the mongodb driver overrides the default options with the options passed to the query level.
For example, if I set at the connect level `{w: "majority"}`, the method `save` will always be with `writeConcern` equal to 1.

**Comment by Amir-61** [comment]
Hi @Lughino,

Would you like to submit a patch for this?

Thanks!
