### ISSUE TITLE
Is using a big include object will affect performance specially if collections have a lot of data?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback-connector-mongodb#238]
Hi,

I have a big `include` object:

```
include: ['leads', 'calledBy',
          {
            relation: 'billboard',
            scope: {
              include: ['subscribers']
            }
          },
          {
            relation: 'promotions',
            scope: {
              include: ['likedBy', 'viewedBy', 'clickedBy', 'sharedBy', {
                relation: 'discussions',
                scope: {
                  include: ['comments']
                }
              }]
            }
          }]
```

Actually, 3-5 of those collections/relations are big collections and contains a lot of data.

Is that will affect performance?

Thanks.

**Comment by ahmed-abdulmoniem** [comment]
Any clue guys?

**Comment by ahmed-abdulmoniem** [comment]
Any clue guys?

**Comment by superkhau** [comment]
@ahmed-abdulmoniem Sorry for the late reply. The more data you have, the longer it'll take to query all the items. You also have some nested includes, so there will definitely be a penalty to query the items in the related models.

For future reference, please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Questions for more details.

**Comment by ahmed-abdulmoniem** [comment]
@superkhau I mean it will be slow even with Mongo which is not relational database?

**Comment by superkhau** [comment]
That really depends on how much data you're fetching. "Slow" is also relative, so in general yes it wil take more processing to fetch from multiple collections and combine them into one result set. Please do your own performance testing and see if the speed is adequate for your use case.
