### ISSUE TITLE
Cannot find object by ID for complex ID objects

### ISSUE THREAD

**Issue by jmbegley1968** [strongloop/loopback-connector-mongodb#239]
Cannot find object by ID for complex (non-string) ID objects.  

`buildWhere(model, {"_id": { key1: "val1", key2: "val2"}})`will cause error message from mongo _Invalid Operator $key1._

`MongoDB.prototype.buildWhere` function assumes we have a spec (i.e. lt, gt) which it assumes is the first/only property at the top level of the where parameter.
What I really want to do in my app code is `model.findById(idObj, function)`
I cannot even do the following  `find({where: {"_id": {'eq': objId}}}, function)`as Mongo2 does support eq.

**Comment by Amir-61** [comment]
Could you please provide a sample repo explaining what you are trying to do using our [loopback-sandbox](https://github.com/strongloop/loopback-sandbox); also could you please provide the exact version of you mongDB server? `2.4` or `2.6`?

Thanks!

**Comment by jmbegley1968** [comment]
Thanks for your reply.  Forked sandbox: https://github.com/jmbegley1968/loopback-sandbox
Mongo version 2.4.6
I have MyModel with 2 endpoints.  Executing the endpoints in explorer will show the situation:
GET /MyModels/myFind1:  Gets and displays object with ID:  "string_id"
GET /MyModels/myFind2:  Attempts to get object with ID:  { "key1" : "value1", "key2" : "value2" }
  Error:  "invalid operator: $key1"

Code is in myModels.js
Thanks

**Comment by jmbegley1968** [comment]
Any progress with this?

**Comment by jjhesk** [comment]
it is very important!

**Comment by jmbegley1968** [comment]
We are now using Mongo 3.x and this issue is less important, as you can do following:  
find({where: {"_id": {'eq': objId}}}
However it is very odd that findById still only works with strings.

**Comment by ssh24** [comment]
You can query by id for complex id types such as ObjectID's using the latest connector. This is tested with mongodb connector version `3.1.0`.

Here is a code snippet:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
    var db = app.dataSources.mongoDs;
    var Employee = app.models.Employee;

    db.automigrate(function(err) {
        if (err) throw err;
        console.log('\nAutomigrate completed');

        Employee.create([{
            name: 'Foo',
            age: 1
        }, {
            name: 'Bar',
            age: 2
        }], function(err, result) {
            if (err) throw err;
            console.log('\nCreated instance: ' + util.inspect(result));

            var id1 = result[0].id;
            var id2 = result[1].id;

            Employee.findById(id1, function(err, result) {
                if (err) throw err;
                console.log('\nFindbyid instance: %s %j', id1, result);
            })
        });
    });
};
```

**output**
```bash
sakibs-mac:mongodb-239 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Automigrate completed

Created instance: [ { name: 'Foo', age: 1, id: 59481b582f82cf57d7349502 },
  { name: 'Bar', age: 2, id: 59481b582f82cf57d7349503 } ]

Findbyid instance: 59481b582f82cf57d7349502 {"name":"Foo","age":1,"id":"59481b582f82cf57d7349502"}
```

Hopefully this answers the question regarding this issue. 

Closing the story as a result. Feel free to reopen if needed.
