### ISSUE TITLE
Using extended operators causing non-extended operator update data lost

### ISSUE THREAD

**Issue by mattohoh** [strongloop/loopback-connector-mongodb#245]
If I update a data with some data likes
`{ $addToSet: { set: 1}, updated: date}`

I added the `updated` field in a model operation hook `before save` to let it record the document update time.

The MongoDB.prototype.parseUpdateData will produce the following result
`{ $addToSet: { set: 1}}`

The `updated` field is lost because the `usedOperators` will be 1 and 

``` javascript
// if parsedData is still empty, then we fallback to $set operator
 if (usedOperators === 0) {
      parsedData.$set = data;
 }
```

will let the non-extended operator field lost.

I think it could be fixed like

``` javascript
 if (usedOperators === 0) {
      parsedData.$set = data;
 } else {
     // add each non-extended operator update field to parsedData.$set
}
```

**Comment by Amir-61** [comment]
Hey @mattohoh ,

Could you please send a PR with failing test? Also if in the PR you can fix the issue, you see, it will be perfect.

Thanks
