### ISSUE TITLE
User login ending in a accessToken entry, with an empty userId property

### ISSUE THREAD

**Issue by pierissimo** [strongloop/loopback-connector-mongodb#246]
I'm using:
- Built-in User model
- Built-in AccessToken model

if I hit the route for login (/User/login), I got back a response with token, but an empty userId.
In the AccessToken collection in the database, the userId property is empty as well.
I'm on fresh project, with no logic added.

Not sure if the issue come from loopback-connector-mongodb module.

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report
