### ISSUE TITLE
no mongos proxy available

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback-connector-mongodb#249]
At some point this day, my stronloop api node kept replying 
`{ [MongoError: no mongos
proxy available] name: 'MongoError', message: 'no mongos proxy available' }`
to any request

apparently there have been a bug at some point with the mongodb native driver used by loopback-connector-mongodb : [here](https://github.com/Automattic/mongoose/issues/3945) [there](https://github.com/christkv/mongodb-core/issues/88), but it's normally on version 2.1.14, and my build currently uses mongodb@2.1.20

Did anyone else suffered from such errors?

**Comment by Amir-61** [comment]
It seems this is related to `mongodb` native module; it is better if we follow up there... 

I keep this ticket open for a while. I will close it soon.

Thanks!

**Comment by Amir-61** [comment]
Is this still an issue?

**Comment by PerfectedTech** [comment]
I still experience this issue as well. Has there been any update?
