### ISSUE TITLE
random “MongoError: not authorized on XXX to execute command {YYY}” with mongo 3.2 since loopback upgrade

### ISSUE THREAD

**Issue by ebarault** [strongloop/loopback-connector-mongodb#251]
since my latest loopback upgrade I have random errors like these: 

```
2016-06-06T18:17:55.386Z pid:2458 worker:3 MongoError: not authorized on db to execute command {...someQuery...}
2016-06-06T18:17:55.386Z pid:2458 worker:3     at Function.MongoError.create (/var/lib/strong-pm/svc/1/work/a6e0bde254cbdedde6345bdf94e29e51828c5fa2.1465232211706/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/error.js:31:11)
2016-06-06T18:17:55.386Z pid:2458 worker:3     at queryCallback (/var/lib/strong-pm/svc/1/work/a6e0bde254cbdedde6345bdf94e29e51828c5fa2.1465232211706/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/cursor.js:200:36)
2016-06-06T18:17:55.386Z pid:2458 worker:3     at Callbacks.emit (/var/lib/strong-pm/svc/1/work/a6e0bde254cbdedde6345bdf94e29e51828c5fa2.1465232211706/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/topologies/server.js:119:3)
2016-06-06T18:17:55.386Z pid:2458 worker:3     at null.messageHandler (/var/lib/strong-pm/svc/1/work/a6e0bde254cbdedde6345bdf94e29e51828c5fa2.1465232211706/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/topologies/server.js:397:23)
2016-06-06T18:17:55.387Z pid:2458 worker:3     at Socket.<anonymous> (/var/lib/strong-pm/svc/1/work/a6e0bde254cbdedde6345bdf94e29e51828c5fa2.1465232211706/node_modules/loopback-connector-mongodb/node_modules/mongodb-core/lib/connection/connection.js:302:22)
2016-06-06T18:17:55.387Z pid:2458 worker:3     at emitOne (events.js:90:13)
2016-06-06T18:17:55.387Z pid:2458 worker:3     at Socket.emit (events.js:182:7)
2016-06-06T18:17:55.387Z pid:2458 worker:3     at readableAddChunk (_stream_readable.js:153:18)
2016-06-06T18:17:55.388Z pid:2458 worker:3     at Socket.Readable.push (_stream_readable.js:111:10)
2016-06-06T18:17:55.388Z pid:2458 worker:3     at TCP.onread (net.js:529:20)
```

I'm running mongo 3.2,
using latest nodeJs mongodb driver (node-mongodb-native 2.1.21) and latests strongloop API framework (latest datasource-juggler & related dependancies)

loopback@2.28.0 
loopback-datasource-juggler@2.46.1 
loopback-connector-mongodb@1.15.2
-------mongodb@2.1.21 

Auth schema is SCRAM-SHA-1 over a replicaset of 2(P/S)+1(A)

It is not a connection nor password issue. it's coming out of the blue on an existing pool of connections set up by the strongloop framework

my datasource config is as follows:

```
    "XXX": {
        "name": "XXX",
        "connector": "mongodb",
        "url": "mongodb://user:password@my.server.com:27017,my.second.server.com:27017/mydb?replicaSet=myReplicaSet?authMechanism=SCRAM-SHA-1&authSource=dbAuthSource&readPreference=secondary&maxPoolSize=100",
        "server": {
          "auto_reconnect": true,
          "reconnectTries": 100,
          "reconnectInterval": 5000
        }
    },
```

it seems to happen after a period of inactivity on the api. For example: some user is the first to query the API after say 5 minutes without other user activity on the api). Once retrying, everything runs fine until the next idle time.

Is anyone experiencing something similar?

---

[edit] ok, i can confirm this is following upgrade of loopback to all latest components.
back to our previous setup, the error goes away.

here are the dependencies that work
loopback@2.26.2 
loopback-datasource-juggler@2.44.0 
loopback-connector-mongodb@1.13.2
-----mongodb@2.0.55

**Comment by vgmcglaughlin** [comment]
Seeing the same issue after updating dependencies. Changing from loopback-connector-mongodb@1.15.2 back to loopback-connector-mongodb@1.13.3 resolves the issue for me.

**Comment by ebarault** [comment]
that's strange, because i just updated back to 1.15.2 the mongodb connector while leaving the rest unchanged (older working set) and i do not have the issue right now. It might come from a certain dependency versions sandwich

**Comment by vgmcglaughlin** [comment]
Possibly. If it helps, my loopback dependency versions are below.

Working before dependencies updated:
```
loopback@2.27.0
loopback-boot@2.18.1
loopback-component-explorer@2.4.0
loopback-component-passport@1.6.0
loopback-connector-mongodb@1.13.3
loopback-datasource-juggler@2.44.0
```

Failed with updated dependencies:
```
loopback@2.28.0
loopback-boot@2.18.1
loopback-component-explorer@2.5.0
loopback-component-passport@1.6.0
loopback-connector-mongodb@1.15.2
loopback-datasource-juggler@2.44.0
```

Working after changing loopback-connector-mongodb back to 1.13.3:
```
loopback@2.28.0
loopback-boot@2.18.1
loopback-component-explorer@2.5.0
loopback-component-passport@1.6.0
loopback-connector-mongodb@1.13.3
loopback-datasource-juggler@2.44.0
```

**Comment by ebarault** [comment]
could you confirm your mongodb version (inside loopback-connector-mongodb) (`npm ls mongodb`) when it does not work?

**Comment by vgmcglaughlin** [comment]
Looks like it's mongodb@2.1.21.

**Comment by ebarault** [comment]
ok, seems that they retrofit to 2.1.18 on npm and there is a bug filed for it on their mongodb JIRA
https://jira.mongodb.org/browse/NODE-726
The culprit is mongodb driver 2.1.21. Anyone who recently updated loopback's dependencies and is having this issue should mongodb driver to 2.1.18

@loopback team: maybe you could fix the mongodb driver version inside the mongodb connector package?

**Comment by mrbatista** [comment]
@ebarault same problem. Rollback to mongodb@2.1.18 solved issue.

**Comment by r1b** [comment]
@mrbatista how do you rollback to 2.1.18 since the mongodb dep is "nested" inside loopback-connector-mongodb?

**Comment by ebarault** [comment]
hi @r1b , just go inside de node_modules rep inside loopback-connected-mongodb and force the install ot the version you desire with npm install mongodb@2.1.18

**Comment by myvo** [comment]
I got this error too.
And I resolved after force to use loopback-connector-mongodb@1.15.2 and mongodb@2.2.11.

**Comment by desduvauchelle** [comment]
+1 on the issue with: 

```
    "loopback": "^2.22.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-component-storage": "^1.9.1",
    "loopback-connector-mongodb": "^1.15.2",
    "loopback-datasource-juggler": "^2.39.0",
```

**Comment by padelagani** [comment]
Please update mongodb version to 2.2.11 in loopback-connector-mongodb `https://github.com/strongloop/loopback-connector-mongodb/`

**Comment by desduvauchelle** [comment]
I use heroku to host my apps, so the manual force update mongodb@2.1.18 inside the connector is a bit tricky. 

So I created a git repo here: https://github.com/desduvauchelle/loopback-connector-mongodb 
Where I changed the mongodb@2.1.18 and use that in my package.json 

But I'm still having the issue. 

Here is my current config (based on initial question)

  ```
  "loopback": "^2.26.2",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^2.4.0",
    "loopback-component-storage": "^1.9.1",
    "loopback-connector-mongodb": "git+https://github.com/desduvauchelle/loopback-connector-mongodb.git",
    "loopback-datasource-juggler": "^2.44.0",
```
Any ideas?

**Comment by superkhau** [comment]
@strongloop/fa-db-connectors PTAL

**Comment by jannyHou** [comment]
So based on https://github.com/strongloop/loopback-connector-mongodb/issues/251#issuecomment-258070125 and https://github.com/strongloop/loopback-connector-mongodb/issues/251#issuecomment-258070125 I am updating mongodb to use latest major version in pr https://github.com/strongloop/loopback-connector-mongodb/pull/306
Let's see if that solves the problem.

**Comment by 0candy** [comment]
@ebarault Did @jannyHou 's fix resolve your issue?

**Comment by bappr** [comment]
Any update ? Our applications in production are facing this issue.

**Comment by mrfelton** [comment]
We're also facing this issue using master. The commit from #306 doesn't look to have solved the issue.

The fork that @desduvauchelle created with mongodb pinned to 2.1.18 gives us better results.

**Comment by ebarault** [comment]
@jannyHou : can't confirm with certitude : in production we're still relying on 2.1.18, and in dev, mongodb version is the one shipped with loopback 3 dependancies : 2.1.21. Got no error in dev, but cannot guarantee production wide. 

Wait... i can see [here](https://github.com/mongodb/node-mongodb-native/releases) that there are many releases since 2.1.21. latest on npm is 2.2.12. and npm list gives me 2.1.21 for mongodb, this is not right. OK found the culprit, the fix https://github.com/strongloop/loopback-connector-mongodb/pull/306 was merged in master but no new release was tagged and this npm still serves v.1.7.0 which installs 2.1.21 version of mongodb driver, which was the initial culprit...

@mrfelton, @bappr : could you confirm which mongodb driver version you are using?

**Comment by padelagani** [comment]
@bappr @mrfelton If you want it urgent, downgrade loopback-connector-mongodb version to @1.13.2. It will solve your issue. 

Since this connector is upgraded you can try upgrading version of connector.

You wont get any issue in development mode. I was also facing the same issue. But after downgrading it, issue was solved.

**Comment by gregbanks** [comment]
it should be noted that versions of the mongodb driver < 2.2.12 are *not* compatible with versions of mongodb >=3.2 (https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility).

also, connection leaks were observed in the 2.1 branch (https://jira.mongodb.org/browse/NODE-719).

**Comment by alihalabyah** [comment]
Any new updates on this? I'm still facing the same issue and was on 1.13.x

**Comment by aks0020** [comment]
@jannyHou You have updated driver version on Nov 14 but it was never released on npm so npm is still using old code(last release Oct 17) so please release this fix on npm as well.

**Comment by skyserpent** [comment]
👍

**Comment by jannyHou** [comment]
@aks0020 We have started the development of new major version in mongodb connector, and loopback@3.x is recently officially released. I am confirming the status of each connector, there might be some delay for release, I will update here when new version published 🚢

**Comment by saggiyogesh** [comment]
Even nodejs driver version >=2.2.12 must be used in order to use mongodb 3.2 or 3.4.

https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#node-js-driver-compatibility

**Comment by gregbanks** [comment]
@saggiyogesh this was pointed out several comments ago

**Comment by jannyHou** [comment]
@everyone Does anyone still run into the error with the latest release loopback-connector-mongodb@3.0.0?
I just tried the latest release on my end, but don't see the issue described in the first comment. 

├── loopback@2.38.0
├── loopback-boot@2.23.0
├── loopback-component-explorer@2.7.0
├── loopback-connector-mongodb@3.0.0 extraneous
├── loopback-datasource-juggler@2.54.0

**Comment by bennekrouf** [comment]
@jannyHou Upgrade to loopback-connector-mongodb@3.0.0 definitly solved the issue !!!

**Comment by 0candy** [comment]
Closing this issue as it looks like its been fixed.

**Comment by myvo** [comment]
+-- loopback@2.38.1
+-- loopback-connector-mongodb@3.0.1 invalid
+-- loopback-datasource-juggler@2.54.0
+-- mongodb@2.2.24

It worked well with loopback-connector-mongodb@3.0.1.
But **why was loopback-connector-mongodb@3.0.1 invalid**?
