### ISSUE TITLE
MongoDb maxDistance is not working?

### ISSUE THREAD

**Issue by ahmed-abdulmoniem** [strongloop/loopback-connector-mongodb#252]
Hi Guys,

Trying to make `maxDistance` with `near` work but no luck?

Any clue?

**Comment by husseiny-m** [comment]
+1

**Comment by ahmed-abdulmoniem** [comment]
++++1

**Comment by seanbrookes** [comment]
I could really use this functionality right now as well.  

There is a PR for a potential fix:  https://github.com/strongloop/loopback-connector-mongodb/pull/259

Would be good if it could be landed.

**Comment by jjhesk** [comment]
++++1
