### ISSUE TITLE
MongoError with empty updateAttributes({})

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-connector-mongodb#253]
As commented at https://github.com/strongloop/loopback-datasource-juggler/pull/772 the PR has uncovered a serious issue in how MongoDB treats 'empty' updates (turned into `$set` by `loopback-connector-mongodb`). 

Previously this (or any other error, for that matter) was silently ignored, and I still believe this should be the case with this specific error:  `MongoError: $set is empty. You must specify a field like so: {$mod: {<field>: ...}}`

It's not enough to just check if `data` is empty in `parseUpdateData`, and then omit `$set`; the current document state will not be returned as usual (you'll see undefined or default values instead of the actual existing data from the db).

/cc @raymondfeng

**Comment by Amir-61** [comment]
Connect to https://github.com/strongloop/loopback-connector-mongodb/pull/254

**Comment by Amir-61** [comment]
https://github.com/strongloop/loopback-connector-mongodb/pull/254 fixes the issue
