### ISSUE TITLE
Add a "disabled" property to the datasource configuration

### ISSUE THREAD

**Issue by stephenwil** [strongloop/loopback-connector-mongodb#256]
When having more than one mongo instance in use (e.g. local vs remote), it's annoying that the connector wants to connect on initialisation to all the instances defined in datasources.json.
Ideally, when swapping between the instances, I'd like to be able to add
"disabled" : "true" to the config to disable a particular datasource.

**Comment by superkhau** [comment]
@stephenwil Would you like to submit a PR?

**Comment by ssh24** [comment]
Closing this issue as a similar config property exists. Read the conversation here: https://github.com/strongloop/loopback-connector-mongodb/pull/257
