### ISSUE TITLE
upsert performs updateAttributes

### ISSUE THREAD

**Issue by Ijmir** [strongloop/loopback-connector-mongodb#258]
standard loopback PUT(without id in path) performs update attributes instead of upsert. in the connector the update data params is mapped using $set in parseUpdateData function:
```js
{
  $set:update_data
}
```
the result is updateAttributes on the query even if upsert flag is defined.

**Comment by Amir-61** [comment]
@Ijmir 

>standard loopback PUT(without id in path) performs update attributes instead of upsert.

In LB 2.x PUT(without id in path) performs upset not updateAttributes. Please see:
![screen shot 2016-06-17 at 3 38 37 pm](https://cloud.githubusercontent.com/assets/10672146/16162465/a976820e-34a1-11e6-8cc3-897ef59cecd0.png)

**Comment by Ijmir** [comment]
thats what you expect. but PUT(without id in path) performs update attributes

**Comment by Amir-61** [comment]
Hey @Ijmir 
This does not seem a bug to me! If you do not provide `id` in path, but you provide it in `data` object; that is used as the `id`, so in your examples for  PUT (no id in path), although you are not providing `id` in path, you provide `id` in `data` object, so thats why are they being treated as `update` part of `updateOrCreate`.

Thanks!

**Comment by Ijmir** [comment]
If this is true, this means that I can't do a full update by id. I think that upsert means update(full update by id)/insert.

**Comment by thaiat** [comment]
In version 2.29 it seems that all updates from the REST API are partial updates.
This looks like a bug to me...

**Comment by Amir-61** [comment]
`updateAttributes` does `patch`/`partial update` and we added an alias called [patchAttribute](https://github.com/strongloop/loopback-datasource-juggler/blob/45e14af4a981fcf376276babeb344ceac578186c/lib/dao.js#L2786) recently. To have the full update functionality you should use [replaceById](https://github.com/strongloop/loopback-datasource-juggler/blob/45e14af4a981fcf376276babeb344ceac578186c/lib/dao.js#L2612) the functionality is work in progress for some connectors, but it should work for `loopback-connector-mongodb`. Once it is complete we will add documentation for that as well.

Thanks

**Comment by Amir-61** [comment]
I'm closing this issue since the question has been answered. Please feel free to open the issue, if you see any issues.

Thanks!
