### ISSUE TITLE
Reconnection issue after 1.13.x

### ISSUE THREAD

**Issue by darknos** [strongloop/loopback-connector-mongodb#262]
I have a problem with losted connection to db with version 1.15.2. on Ubuntu

How to reproduce on any loopback project:
1. start server like node serve/server or slc run
2. check access to any api endpoint ti be sure that you get data from db
3. restart mongodb
4. trying to repeat 2. and no result and timeout after 3 minutes.

with version 1.13.0, on step 4. connection restored and it works like charm.

**Comment by demsey2** [comment]
I have the same problem running on AWS ESB, I reverted to 1.13 and works fine, before I was running 1.15.2 for a few weeks and all was fine, now I need to use 1.13 not sure what changed
