### ISSUE TITLE
Causing issue in Loopback Current Context Null

### ISSUE THREAD

**Issue by Malkiat-Singh** [strongloop/loopback-connector-mongodb#265]
Hi 
The fix in this commit causing the current context null issue 
 https://github.com/strongloop/loopback-connector-mongodb/commit/566503842f2c5d80b6bd40f8e7002b3b8859aba0

Please fix this

**Comment by bajtos** [comment]
Hello, the current context feature is known to be broken in many cases. Follow https://github.com/strongloop/loopback-context/issues/21 for updates regarding MongoDB support.
