### ISSUE TITLE
Documentation unclear about "additional settings"

### ISSUE THREAD

**Issue by etsuo** [strongloop/loopback-connector-mongodb#270]
https://github.com/strongloop/loopback-connector-mongodb#additional-settings implies that:
- `enableGeoIndexing` is set in the datasources.json file.
- `allowExtendedOperators` appears to be set in the model's json config file, according to: https://docs.strongloop.com/display/public/LB/MongoDB+connector

The way the README.md file reads, that's not clear.

Also, it's not clear what the debug:true setting does in the datasources.json file (see: https://docs.strongloop.com/display/public/LB/MongoDB+connector) - I've toggled it on and off and tried different things to see if it makes any difference in output, but I'm not even sure where to look... it's not going to stdout as far as I can tell.

I'm happy to help with a PR, but I need guidance as to whether or not I'm right about `allowExtendedOperators` and `enableGeoIndexing`, and it doesn't look like the public can contribute to the Confluence wiki... :/

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
It looks like @timosaikkonen added `enableGeoIndexing` support--can you (or @superkhau) confirm that `enableGeoIndexing` is set in `datasources.json` and  `allowExtendedOperators` is set in the model's json? If so, I can change the README.

Also, I notice that this README still mentions `.loopbackrc`, which I believe has been deprecated for ages and certainly isn't best practice.  I assume I should remove or change this--please confirm @superkhau .

@etsuo You're correct that docs don't currently provide for external contributions, but we're working on changing that: https://github.com/strongloop/loopback/issues/2515 :-)

**Comment by superkhau** [comment]
@crandmck You can still use `.loopbackrc` via https://github.com/strongloop/loopback-connector-mongodb/blob/master/test/init.js#L11. We don't recommend it though. We need to refactor this project to follow a simple clone, npm install, set your mongodb configs and npm test type of flow. That of course is coming in the future (can't say when).

**Comment by etsuo** [comment]
@crandmck `enableGeoIndexing` gets set here: https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L108

I assumed that `settings` represents `datasources.json`, but then I saw that `allowExtendedOperators` appears to be in the `settings` object... but also the `options` object: https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L458

So I just set `enableGeoIndexing` to `false` in my datasources.json and it that broke my app...  :). I'm pretty confident that `enableGeoIndexing` belongs in datasources.json. I'm still not sure about `allowExtendedOperators`.

**Comment by etsuo** [comment]
@crandmck I ended up having to use the `allowExtendedOperators` today - for what it's worth, putting it in the Model's JSON's `options` got it working for me:
```
"options": {
    "validateUpsert": true,
    "mongodb": {
      "allowExtendedOperators": true
    }
  },
```
The documentation says it should go in `settings` in the model. As far as I could tell, that did not work for me... see "Using MongoDB operators in update operations" here: https://docs.strongloop.com/display/public/LB/MongoDB+connector

**Comment by Sequoia** [comment]
# Questions
These are the questions in this ticket, if I'm understanding correctly:

1. Where does `enableGeoIndexing` go? (datasources or model json)?
2. Where does `allowExtendedOperators` go? (datasources or model json)?
3. What does the `debug:true` setting in datasources.json do? ✅ *answered below*

# Observations
From code & discussion on this ticket

1. `enableGeoIndexing`
  * Setting it to `false` in @etsuo’s datasources.json & it broke his app (*was this expected?*)
  * @etsuo pretty confident it belongs in datasources.json
2. `allowExtendedOperators`
  * mongodb.js suggests it can be set using...
    1. [settings](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L458)
    2. [query options](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L460)
    3. [as a model config property](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L462-L463)
    4. [????](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L464-L466)
3. `debug:true`
  * debugs using [debug-module](https://www.npmjs.com/package/debug) logging function. [This function](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L14) is enabled by setting `process.env.DEBUG` to `loopback:connector:mongodb` (or `loopback:*` or `*`, [see docs for more](https://www.npmjs.com/package/debug#conventions)).
  * debug logging function calls are [**wrapped in checks of `settings.debug`**](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L95-L99) (*this is probably redundant: the purpose of the `debug` module is to allow loggers to be enabled/disabled by an ENV var. Requiring debug to be enabled in two ways is, as the question in this ticket proves, confusing*.)

**Comment by Sequoia** [comment]
fdb3448ead26b81a61b7f7fdd0420d3a32da60b1, which introduces this change, includes tests that explain the intended behavior.

* mongodb connector
  * updateAll
    * extended operators
      * should be possible to enable per model settings
      * should not be possible to enable per model settings when globally disabled
      * should not be possible to use when disabled per model settings

@etsuo:
1. Does this clear up your particular questions?
2. What parts of this would you like to see added to the README.md if any?
