### ISSUE TITLE
enableGeoIndexing / GeoJSON Bug with $and operations

### ISSUE THREAD

**Issue by etsuo** [strongloop/loopback-connector-mongodb#271]
I’m having an issue with the Mongo connector and Geo searches when I have the enableGeoIndexing feature turned on…

If I send a REST query over with a simple `near` filter:

```
{
  "include": [
    “organization"
  ],
  "where": {
    "location": {
      "near": {
        "lat": 34.81593,
        "lng": -119.34850000000002
      }
    }
  },
  "limit": 5,
  "skip": 0
}
```

...the proper mongo query gets generated:

```
db.getCollection(‘Member').find({
            "location" : {
                "$near" : {
                    "$geometry" : {
                        "coordinates" : [ 
                            -119.34821, 
                            34.816154
                        ],
                        "type" : "Point"
                    }
                }
            }
        }).limit(5)
```

If, however, I send a more compound type of filter with an `and`:

```

{
  "include": [
    “organization"
  ],
  "where": {
    "and": [
      {
        "location": {
          "near": {
            "lat": 34.8159237,
            "lng": -119.34851069999999
          }
        }
      },
      {
        “organizationId": {
          "inq": [
            "579e9eb6870c068d7293c7cf"
          ]
        }
      }
    ]
  },
  "limit": 5,
  "skip": 0
}
```

… the query generated for mongo is invalid because it expeted a 2d index rather than a 2dsphere index (which is what the first query requires)…:

```
db.getCollection(‘Entity').find({
            "$and" : [ 
                {
                    "location" : {
                        "$near" : {
                            "lat" : 34.816154,
                            "lng" : -119.34821
                        }
                    }
                }, 
                {
                    “organizationId" : {
                        "$in" : [ 
                            ObjectId("579e9eb6870c068d7293c7cf")
                        ]
                    }
                }
            ]
        }).limit(5)
```

Is this a bug in the MongoDB connector?

**Comment by etsuo** [comment]
The problem seems related to the [`hasNearFilter` function](https://github.com/strongloop/loopback-connector-mongodb/blob/a10478bc08270f1890a6b529d69bb174686c6ac8/lib/mongodb.js#L758).

```
function hasNearFilter(where) {
  if (!where) return false;

  for (var k in where) {
    if (where[k] && typeof where[k] === 'object' && where[k].near) {
      return true;
    }
  }

  return false;
}
```
This appears to have been introduced here: 8112ebc720c4dbb74b72db3e44260905ed25128c.

When `and` is encountered, it evaluates to `false`, so the `buildNearFilter` function is never called.

**Comment by etsuo** [comment]
ok, found the root of the problem... `loopback-datasource-juggler`'s [`lib/geo.js:nearFilter`](https://github.com/strongloop/loopback-datasource-juggler/blob/27c6279d6ce84d624457658d843967edbfd4ba61/lib/geo.js#L12) does a non-recursive search...

As a result, dao.js's find function never triggers because `near` evaluates to false...

So the question is: should this be supported?  This is a valid mongo query:
```
// fixed filter with GeoJSON
db.getCollection('Church').find({
            "$and" : [ 
                {
                    "location" : {
                        "$near" : {
                            "$geometry" : {
                                "coordinates" : [ 
                                    -118.34821, 
                                    33.816154
                                ],
                            "type" : "Point"
                            }
                        }
                    }
                }, 
                {
                    "denominationId" : {
                        "$in" : [ 
                            ObjectId("579e9eb6870c068d7293c7cf")
                        ]
                    }
                }
            ]
        }).limit(5)
```

How else should I represent that if not with an `and`?

**Comment by etsuo** [comment]
This issue is also reported here: https://github.com/strongloop/loopback-datasource-juggler/issues/931

**Comment by etsuo** [comment]
For what it's worth, I have a working fix on my fork here: https://github.com/etsuo/loopback-connector-mongodb

If it's wanted, I'll open a PR, but I need guidance on a couple things:

1. The patch spans two projects: loopback-datasource-juggler and loopback-connector-mongodb. The latter depends on the former to work and the former breaks the latter... so, how do you guys normally go about that?

2. I searched through the various connectors to make sure than none of them implement the `buildNearFilter` function... the reason why is that the current nearFilter function in geo.js (juggler) returns a string for a key. Since the patch recurses through there `where` object, it needs to pass on a key array that informs the `buildNearFilter` of the MongoDB connector so that it can properly replace the nested key with a GeoJSON object instead of a GeoPoint. Am I right in my assessment that none of the other connectors are currently implementing `buildNearFilter`?

**Comment by etsuo** [comment]
Also added `maxDistance` support... which was reported as not working in #252.

**Comment by 0candy** [comment]
You can create the PR in the respective repo. Then put in the description or add a comment to cross link the two issues and specify which one needs to be merged first or is dependent on the other. Thanks!

**Comment by etsuo** [comment]
@0candy PR opened

**Comment by ebarault** [comment]
hi, could you check if these PR fix your issue ?
strongloop/loopback-datasource-juggler#1216
strongloop/loopback-connector-mongodb#322
