### ISSUE TITLE
`include` filter with `{scope: {limit: ...}}` produces wrong query

### ISSUE THREAD

**Issue by etsuo** [strongloop/loopback-connector-mongodb#274]
Consider the following filter applied to a model (e.g., `Member`):

```
{
  "include": [
    {
      "relation": "organization"
    },
    {
      "relation": "events",
      "scope": {
        "skip": 0,
        "limit": 1
      }
    }
  ],
  "where": {
    "location": {
      "near": {
        "lat": 34.8159142,
        "lng": -119.34852959999999
      }
    }
  },
  "limit": 5,
  "skip": 0
}
```

Member `belongsTo` Organization, so each member returned has a single Organization record. That works fine.

Member `hasMany` Events. Here's where the problem arises. If I remove the `limit` condition under `scope` for the `events` relation, each Member has every event. That's way too much data to pull across the wire. The goal (though it's not reflected here) is to get the event that's happening next for each Member (something like `gte:now` and `limit:1` sorted from least to greatest date). If, however, I include the limit filter, the following MongoDB query is generated:

```
{
    "ns" : "db.Event",
    "query" : {
        "find" : "Event",
        "filter" : {
            "memberId" : {
                "$in" : [ 
                    ObjectId("57a62ca0d011bf1a43cf423f"), 
                    ObjectId("57a62ca0d011bf1a43cf423b"), 
                    ObjectId("57a62ca0d011bf1a43cf4234"), 
                    ObjectId("57a62ca0d011bf1a43cf4235"), 
                    ObjectId("57a62ca0d011bf1a43cf4239")
                ]
            }
        },
        "sort" : {
            "_id" : 1
        },
        "limit" : 1
    }
}
```

The filter is asking for 1 Event per Member.  I.e., each Member should have exactly 1 or 0 Events in the `find` result. 

Instead, however, one member has an event, because the events returned by the above MongoDB query are limited as a whole to 1 document rather than being 1 document per member.

It seems to me that there should be a separate query for Events limited to 1 result each per Member.

Am I misunderstanding how filters work, or is a bug?

**Comment by jannyHou** [comment]
@etsuo I am trying to reproduce your problem, could you fork https://github.com/strongloop/loopback-sandbox and replace with your sample code?
Thanks.

One important thing I want to know is do you have a through model for the `hasMany` relation? And where did you get the Mongodb query? Did you get it from `DEBUG=*mongodb` or other debug info?

**Comment by phra** [comment]
@etsuo do you have solved this issue in some way?

@jannyHou do you have reproduced successfully the problem?

**Comment by hopduong** [comment]
@etsuo @jannyHou I don't know if you guys had resolved this issue, but now I meet this in my project. Could you guys please give your solution?
