### ISSUE TITLE
Extended operators does not work with updateAttributes()

### ISSUE THREAD

**Issue by perkd** [strongloop/loopback-connector-mongodb#281]
Works fine with updateAll() but not updateAttributes(), for example:

`anInstance.updateAttributes({name: 'abc', '$inc': { count: 1 }}, { allowExtendedOperators: true }, callback);`

Seems that the extended operators are filtered/removed before reaching the mongo connector?

**Comment by habbes** [comment]
Well it worked for, but the `instance` passed to the callback seems to be that of the document before modification and not the updated document. So the document in the database gets update, but the instance you get back in the callback doesn't reflect this.

**Comment by habbes** [comment]
This seems to be because, they're passing an empty options `{}` to the `"findAndModify"` command on line 1027 of `mongodb.js`. I'm not sure why they chose to implement it this way. On the other hand, they seem to specify `{..., new:true}` for the `updateOrCreate` method (line 527). So I suppose that's what would need to be done to return an updated instance. More on that in the [MongoDb docs](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/)

**Comment by habbes** [comment]
I just noticed the calling `instance.updateAttributes` does not seem to return the result from the database in the callback, it seems to be returning the current instance, which could be different from the one in the db... I think this needs to be fixed, it doesn't help to return the same instance when we just called an update.

**Comment by habbes** [comment]
The result object passed to the callbback from the `updateAttributes` in the connector code is not the same one you get in the callback from the model's `instance.updateAttributes` method...

**Comment by superkhau** [comment]
Can you provide a sample for us to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report

**Comment by jannyHou** [comment]
@habbes any update for the sample code? you can fork https://github.com/strongloop/loopback-sandbox and replace with your code? Thanks.

**Comment by phra** [comment]
@perkd @habbes can you provide the sample code in order to help fixing this problem? thanks.

**Comment by michaelfreund** [comment]
@superkhau this issue is still relevant and unfixed. how can we proceed here?

**Comment by michaelfreund** [comment]
https://github.com/strongloop/loopback-connector-mongodb/issues/157

**Comment by michaelfreund** [comment]
#157

**Comment by jannyHou** [comment]
@michaelfreund is this issue the same as #157 ? I see a fix pr checked in for #157. Does it help?

**Comment by superkhau** [comment]
@michaelfreund Can you verify if https://github.com/strongloop/loopback-datasource-juggler/pull/979 fixes your issue?

If not, we can proceed by getting someone to provide a sample repo to reproduce (or better yet a PR to review so we can land the fix).

**Comment by mediastuttgart** [comment]
@superkhau using latest versions for all dependencies on LB2

```
loopback 2.38.2
loopback-boot 2.24.0
loopback-component-explorer 2.7.0
loopback-connector-mongodb 1.18.1
loopback-datasource-juggler 2.54.1
loopback-remote-routing 1.4.0
```

the following code will return the old instance instead of the updated one

```js

post.updateAttributes({
	$inc: { like_count: 1 }
}, function (err, instance) {
	console.log(instance); ///> old instance
});
```

datasource for mongodb has `allowExtendedOperators` set to `true`
