### ISSUE TITLE
idInjection: ValidationError The instance is not valid. Details: `id` can't be set 

### ISSUE THREAD

**Issue by bachirelkhoury** [strongloop/loopback-connector-mongodb#282]
I'm getting this new problem when creating an entity and manually setting its id.

I have created a small test project demonstrating the problem here:
https://github.com/bachirelkhoury/loopback-idinjection-issue

Given I have an entity called group:

```
{
  "name": "group",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    }
  },
  "validations": [],
  "relations": {
  },
  "acls": [],
  "methods": {}
}

```

which I'm creating and setting it's id to 'a00000000000000000000000'

I'm getting this error:

```
/Volumes/HardDrive/Users/rtistique/LimpidLogic/2_Projects/Brave_Gordon/Brave/Development/brave-api/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });

ValidationError: The `group` instance is not valid. Details: `id` can't be set (value: a00000000000000000000000).,ValidationError: The `group` instance is not valid. Details: `id` 
can't be set (value: a00000000000000000000001).
```

Been stuck on this all day.

**Comment by BoLaMN** [comment]
seems to be https://github.com/strongloop/loopback-datasource-juggler/commit/8935b978f33f7cf4dd88454762d26cb78aac3e87

**Comment by jannyHou** [comment]
Thank you @BoLaMN that pr does change the default behaviour of modelInstance creation, and @bachirelkhoury In loopback 3.x defaultly we don't allow users to set id to avoid security issues. 
If you need to set your id, the quickest way is add '"forceId": false' in your model.json file.

Please check our doc for more details:
http://loopback.io/doc/en/lb3/3.0-Release-Notes.html

**Comment by jannyHou** [comment]
I am closing this issue now since solution already provided in https://github.com/strongloop/loopback-connector-mongodb/issues/282#issuecomment-252053853
Feel free to reopen it if you still have problem.
