### ISSUE TITLE
Cannot filter document with value contain "(" or ")"

### ISSUE THREAD

**Issue by huytbt** [strongloop/loopback-connector-mongodb#286]
I have document
```
{
    "name": "This is example (Abc)"
    ...
}
```
I cannot filter it by `?filter[where][name][like]=This is example (Abc)`
I just filter it by `?filter[where][name][like]=This is example`
How to filter with `(Abc)`?

Thank!

**Comment by jannyHou** [comment]
@huytbt Could you provide me a repo to reproduce your problem?
You can fork https://github.com/strongloop/loopback-sandbox and replace with your code.
Thanks.

i tried on my local, the filter with `()` works fine..see pic:
![screen shot 2016-10-05 at 5 38 11 pm](https://cloud.githubusercontent.com/assets/12554153/19132623/85181d50-8b22-11e6-8010-97df7063d54f.png)

**Comment by huytbt** [comment]
Ok @jannyHou
Thanks
