### ISSUE TITLE
buildSort is not being used in .all

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-connector-mongodb#300]
We should use the `buildSort` method instead of handling the `order` inline in the `.all` method.

**Comment by smartmouse** [comment]
How would you suggest the change should be?

**Comment by fabien** [comment]
Yes, it's better code re-use and easier to maintain this way. Just replacing it with a call to `buildSort` will be fine.

**Comment by ssh24** [comment]
Fixed in: https://github.com/strongloop/loopback-connector-mongodb/pull/376
