### ISSUE TITLE
Query with near and maxDistance won't work on MongoDB 2.x

### ISSUE THREAD

**Issue by balanza** [strongloop/loopback-connector-mongodb#312]
Hi,

it seems it's actually impossible to perform a query over a MongoDB version 2.x if `filter` contains both `near` and `maxDistance` for a field. 

A trivial use case would be to retrieve all point-of-interest in a given area, thus quite a common task. 

The problem is the following: the connector is actually composing this query in the `buildNearFilter` function:

```
coordinates_field: {
    $near: {
       $geometry: {
         coordinates: [40.5634, 12.4543],
         type: 'Point',
       },
      $maxDistance: 0.5
    }
};
```

On the other hand, MongoDB 2.x doesn't recognise this structure and prefers the following:
```
coordinates_field: {
     $near:  [40.5634, 12.4543],
     $maxDistance: 0.5
};
```

I don't actually know if this connector aims to be compatible with older versions of MongoDB. If yes, this is an issue it should be addressed as it impedes some operations. If no, then this isn't a issue at all.

**Comment by 0candy** [comment]
Closing this as a dup. Please see https://github.com/strongloop/loopback-connector-mongodb/issues/252
