### ISSUE TITLE
GeoPoint Field Type - Issue when updating data

### ISSUE THREAD

**Issue by mnaveenriaz** [strongloop/loopback-connector-mongodb#318]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
In a MongoDB Collection with field "GeoPoint", 
GeoPoint field gets generated correctly when a new document is created. 
The format is {"coordinates": [0,0], "type": "Point"}

But when updating the document, the geopoint field is generated as { "lat": 0, "lng": 0}

### Recommended Fix

File to be updated:
~/lib/mongodb.js

Section to be fixed:
/*!
 * Convert JSON to database-appropriate format
 *
 * @param {String} model The model name
 * @param {Object} data The JSON data to convert
 */
MongoDB.prototype.toDatabase = function (model, data) {
  if (this.settings.enableGeoIndexing !== true) {
    return data;
  }

  var props = this._models[model].properties;

  for (var p in props) {
    var prop = props[p];
    if (data[p] && prop && prop.type && prop.type.name === 'GeoPoint') {
      data[p] = {
        coordinates: [data[p].lng, data[p].lat],
        type: 'Point'
      };
    }
    
    // Code added to fix PATCH of GeoPoint Fields
    // Start of Fix
    if (data["$set"] && data["$set"][p] && prop && prop.type && prop.type.name === 'GeoPoint') {
      data["$set"][p] = {
        coordinates: [data["$set"][p].lng, data["$set"][p].lat],
        type: 'Point'
      };
    }
    // End of Fix
  }

  return data;
};

### Expected result
{"coordinates": [0,0], "type": "Point"}

### Actual result (if bug)
{ "lat": 0, "lng": 0}

### Additional information (Node.js version, LoopBack version, etc)
loopback: "3.0.0"
loopback-boot: "2.6.5"
loopback-component-explorer: "2.4.0"
loopback-connector-mongodb: "1.17.0"
mongodb: "2.2.11"
node: "7.2.0"

**Comment by dhmlau** [comment]
@mnaveenriaz, would you like to submit a PR?
