### ISSUE TITLE
Connection fails: MongoError: no valid replicaset members found

### ISSUE THREAD

**Issue by mike-aungsan** [strongloop/loopback-connector-mongodb#319]
- [X] Bug

Cannot connect to mongodb service with replica set. I can connect with native driver tho.

    "database": "abc",
    "username": "abc_rw",
    "password": "password",
    "url": "mongodb://10.0.0.138:7407,10.0.0.139:7407,10.0.0.140:7407/ekg?replicaSet=mongo7407&poolSize=25&autoReconnect=true&reconnectTries=100&reconnectInterval=3000&connectTimeoutMS=30000&socketTimeoutMS=30000&maxPoolSize=25&w=majority&wtimeoutMS=3000",

Connection fails: MongoError: no valid replicaset members found
It will be retried for the next request.

C:\webserver\node_modules\mongodb\lib\mongo_client.js:210
          throw err
          ^
MongoError: no valid replicaset members found
    at Timeout._onTimeout (C:\webserver\node_modules\mongodb-core\lib\topologies\replset.js:642
:33)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)

### Additional information (Node.js version, LoopBack version, etc)

npm  3.10.9
node  v7.2.0
+-- loopback-connector-mongodb@1.15.2
+-- mongodb@2.2.6

**Comment by smartmouse** [comment]
Thank you for trying out,  I do not think this is a bug, replicaSets are not supported yet. This should be a feature.

**Comment by codymwalker** [comment]
Seeing this same issue on Node 6.x, which is listed as compatible:
```
[exec] ├─┬ loopback-connector-mongodb@1.18.3 
     [exec] │ ├── async@1.5.2 
     [exec] │ ├─┬ loopback-connector@2.7.7 
     [exec] │ │ ├── async@1.5.2 
     [exec] │ │ └─┬ msgpack5@3.4.1 
     [exec] │ │   └── bl@1.2.0 
     [exec] │ └─┬ mongodb@2.2.24 
     [exec] │   ├── es6-promise@3.2.1 
     [exec] │   ├─┬ mongodb-core@2.1.8 
     [exec] │   │ ├── bson@1.0.4 
     [exec] │   │ └─┬ require_optional@1.0.0 
     [exec] │   │   └── semver@5.3.0 
```

**Comment by raymondfeng** [comment]
Based on our investigation, the issue is caused by mongodb@2.x. See:

- https://github.com/Automattic/mongoose/issues/4596
- https://jira.mongodb.org/browse/NODE-816?jql=text%20~%20%22MongoError%3A%20no%20primary%20found%20in%20replicaset%22

Before we have a fix from the driver, maybe we should set the dependency to `mongodb@~2.1.21`.

**Comment by janpansa** [comment]
I am having the same issue trying to connect to mongodb Atlas from loopback-connector-mongodb ? Any fixes for this ?

**Comment by sguilly** [comment]
'mongo atlas' works fine with 1.18.1
but  authentication fail with 3.x.x

ERROR - authentication fail
ERROR - err { MongoError: authentication fail
    at Function.MongoError.create (/storage/s3pweb/bitbucket/s3pweb-api-server/node_modules/mongodb-core/lib/error.js:31:11)
    at /storage/s3pweb/bitbucket/s3pweb-api-server/node_modules/mongodb-core/lib/topologies/replset.js:1245:38
    at /storage/s3pweb/bitbucket/s3pweb-api-server/node_modules/mongodb-core/lib/connection/pool.js:760:7
    at /storage/s3pweb/bitbucket/s3pweb-api-server/node_modules/mongodb-core/lib/connection/pool.js:736:20
    at /storage/s3pweb/bitbucket/s3pweb-api-server/node_modules/mongodb-core/lib/auth/scram.js:196:18
    at /storage/s3pweb/bitbucket/s3pweb-api-server/node_modules/mongodb-core/lib/connection/pool.js:469:18
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoError',
  message: 'authentication fail',
  errors:
   [ { name: 'xxxx.mongodb.net:27017',
       err: [Object] } ] }
