### ISSUE TITLE
upsert not works when the model contains shared key

### ISSUE THREAD

**Issue by desmondgong** [strongloop/loopback-connector-mongodb#321]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)
According to the following logs, it should be a limitation of the connector in LoopBack for MongoDB.
For the `upsert` (UpdateOrInsert) action, LoopBack only supports single primary key, but the query `findAndModify` in MongoDB driver must require the shard key.
>upsert: {"sourceId":"user12345","targetId":"entity12345","action":"comment","score":20,"orgId":"org0","id":"d96b4ee0-c65f-11e6-87f2-7915f453596b"}
  loopback:connector:mongodb updateOrCreate +7ms score { id: 'd96b4ee0-c65f-11e6-87f2-7915f453596b',
  sourceId: 'user12345',
  targetId: 'entity12345',
  action: 'comment',
  score: 20,
  orgId: 'org0' }
  loopback:connector:mongodb MongoDB: model=score command=findAndModify +1ms **[ { _id: 'd96b4ee0-c65f-11e6-87f2-7915f453596b' },
  [ [ '_id', 'asc' ] ],
  { '$set': 
     { sourceId: 'user12345',
       targetId: 'entity12345',
       action: 'comment',
       score: 20,
       orgId: 'org0' } },
  { upsert: true, new: true },**
  [Function] ]
  loopback:connector:mongodb Error:  +259ms { **[MongoError: query for sharded findAndModify must have shardkey]**
  name: 'MongoError',
  message: 'query for sharded findAndModify must have shardkey',
  ok: 0,
  errmsg: 'query for sharded findAndModify must have shardkey',
  code: 61 }

### Link to sample repo to reproduce issue (if bug)
Private repo from IBM, can not expose here.

### Additional information (Node.js version, LoopBack version, etc)
Node.JS: 4.5.0
LoopBack: 2.36.0

**Comment by smartmouse** [comment]
Hi, I **do not** think sharded collections are supported by loopback-connector-mongodb yet.
that will be a feature-request.

<img width="838" alt="screen shot 2017-02-03 at 7 55 32 pm" src="https://cloud.githubusercontent.com/assets/4519627/22614090/13e63a48-ea4c-11e6-8889-e8566f581c15.png">
 but from the documentation of mongodb, if it is a normal collection, the findAndModify should work fine.

**Comment by jonathan-casarrubias** [comment]
@jannyHou @loay @b-admike @virkt25 @dhmlau @shimks @nitro404 @ssh24 I'm also presenting this problem when using the instance.save() in a sharded environment.

![image](https://user-images.githubusercontent.com/1533239/40987682-d52c2190-68ae-11e8-9646-c1e3127082c5.png)

The argument flow is an instance of a Flow Model, therefore at that point already presents the mongodb shard key which is "scenarioId".

IT seems that the .save() method is removing the shard key and then I get the following message

```sh
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoError: Query for sharded findAndModify must contain the shard key
```

**Comment by jonathan-casarrubias** [comment]
For anyone interested, I was able to find the issue.

The problem is that some loopback methods are internally using the findAndModify method from the nodejs mongodb driver. The problem is that in a sharded environment, the shard key must be provided within the query, the problem is that loopback is only using the document id within the query portion, therefore generating this issue.

https://github.com/strongloop/loopback-connector-mongodb/blob/2d2999e37710b47b131b7632f88e75537e4698d4/lib/mongodb.js#L1456

I was a able to work around by creating my own service to use it instead of loopback methods.

![image](https://user-images.githubusercontent.com/1533239/44105092-37e20442-9fb6-11e8-8def-603f026cb567.png)
