### ISSUE TITLE
optimizedFindOrCreate does not return mongodb error

### ISSUE THREAD

**Issue by jamesjjk** [strongloop/loopback-connector-mongodb#326]
- [X] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

- OptimizedFindOrCreate fails to return a mongodb error. FindOrCreate can easily produce a duplicate key error in a mongo environment with many read/writes, as there is a problem with atomic mongo findAndUpdate/Update functions https://jira.mongodb.org/browse/SERVER-14322

- Secondly you should release v1.18 as a release version as it fixes #296 

You can reproduce the error by returning an error directly in the mongodb  OptimizedFindOrCreate method (see code below). Model.FindOrCreate will only receive null objects. 

This is critical for those whom face a serious mongodb bug where duplicate key errors are an issue in parallel updates, as the official guidelines state the client side should re run the procedure for X number of times until mongodb accepts.

```javascript
this.collection(model).findOneAndUpdate(
    query,
    { $setOnInsert: data },
    { projection: filter.fields, sort: sort, upsert: true },
    function(err, result) {
      if (self.debug) {
        debug('findOrCreate.callback', model, filter, err, result);
      }
      /** RETURN AN ERROR AS TEST **/
      return callback(Error('some error'));
      if (err) {
        return callback(err);
      }
```

### Additional information (Node.js version, LoopBack version, etc)
Node v6+
loopback 2.37.0
loopback-connector-mongodb 1.18.0

**Comment by jamesjjk** [comment]
Further investigation reveals that in the datasource-juggler dao.js the error is not handled properly. This requires to be updated. The error is overwritten:

See line dao.js#L1047 the findOrCreateCallback callback should check for the error before proceeding. As notifyobserver callback overwrites with null on success. L1049 should include : if (err) return cb(err);

```javascript
function _findOrCreate(query, data, currentInstance) {
    var modelName = self.modelName;
    function findOrCreateCallback(err, data, created) {
      console.log(!!err); //INSERT HERE: if (err) { return cb(err); }
      var context = {
        Model: Model,
        data: data,
        isNewInstance: created,
        hookState: hookState,
        options: options,
      };
      Model.notifyObserversOf('loaded', context, function(err) {
        if (err) return cb(err);

        var obj, Model = self.lookupModel(data);
```

**Comment by superkhau** [comment]
@jamesjjk Would you like to contribute a PR instead?

**Comment by jamesjjk** [comment]
@superkhau Sure but the problem is in the datasource-juggler (doa.js) project. I raised a ticket for you and your colleagues, error is in multiple branches. 
https://github.com/strongloop/loopback-datasource-juggler/issues/1223

In fact the problem I have outlined here is that there is a real error problem with mongodb and the findOneAndUpdate method, in-fact any update method that uses"upsert" is not atomic. 

This should according to mongo be dealt with by the client. I think their own node native driver should be doing this. But they seem reluctant to want to fix a major issue. 

I don't mind committing a PR for datasource juggler, but maybe the project owner should add the one line to fix this and run the test, as its across different branches.

**Comment by superkhau** [comment]
>In fact the problem I have outlined here is that there is a real error problem with mongodb and the findOneAndUpdate method, in-fact any update method that uses"upsert" is not atomic.
>
>This should according to mongo be dealt with by the client. I think their own node native driver should be doing this. But they seem reluctant to want to fix a major issue.

Sounds like some good can kicking there.

>I don't mind committing a PR for datasource juggler, but maybe the project owner should add the one line to fix this and run the test, as its across different branches.

@jamesjjk Feel free to submit the PR for that one liner and we can discuss there. Our CI will take care of the downstream dependency checks from Juggler PRs across all connectors. Ping me in that PR for review.

**Comment by ssh24** [comment]
Closing this issue as the upstream issue with callback returning the error if caught was fixed in Juggler's dao. https://github.com/strongloop/loopback-datasource-juggler/pull/1270

Feel free to reopen if needed.
