### ISSUE TITLE
`strictObjectIDCoercion` setting at property level

### ISSUE THREAD

**Issue by jmimi** [strongloop/loopback-connector-mongodb#328]
### Feature request

When a property is an id and we save it as string in db, the connector handles it as `ObjectID` according to [this](https://github.com/strongloop/loopback-connector-mongodb/blob/eff65e052d17537d82796658e0db15d09003cf0a/lib/mongodb.js#L1390).

I think the `strictObjectIDCoercion` settings should be for properties too.
Assume we have :

```
 "someId": {
      "type": "String"
    },
 "anotherId": {
      "type": "String"
    }
```
I want the connector handles `someId` as an id but not for `anotherId`.
The `strictObjectIDCoercion` settings is for model and causes connector handles them in same way.
But if I have `strictObjectIDCoercion` for properties too, I could define how the connector handles them like below:

```
 "someId": {
      "type": "String",
      "strictObjectIDCoercion": true
    },
 "anotherId": {
      "type": "String"
    }
```

### Link to related issues
[here](https://github.com/strongloop/loopback/issues/3102)
[there](https://github.com/strongloop/loopback-connector-mongodb/issues/327)

**Comment by fabien** [comment]
AFAIK we cannot properly declare the following right now:

```
 "someId": {
      "type": "ObjectID"
    },
 "anotherId": {
      "type": "String"
    }
```

If we could, then it would have been handled correctly as it is. You could do the following (in code, not JSON), which does work as intended:

```
Model.defineProperty('someId', { type: db.ObjectID });
```

My solution would be to make sure we can declare custom types as strings in the JSON config.

@bajtos do you know if custom data types can be declared?

**Comment by jmimi** [comment]
@fabien It could be helpful to define in json too.

One way is too implement `strictObjectIDCoercion` for properties too.

The another one is something like this to be implemented :

```
"someId": {
      "type": "Object",
      "mongodb": {
          "type": "ObjectID"
       }
    },
 "anotherId": {
      "type": "String"
    }
```

**Comment by bajtos** [comment]
> > My solution would be to make sure we can declare custom types as strings in the JSON config.

> do you know if custom data types can be declared?

I believe it's possible, as long as the custom data type is registered with Juggler/LoopBack's registry of types. See e.g. how `GeoPoint` is registered [here](https://github.com/strongloop/loopback-datasource-juggler/blob/ae07480f4574ca656cd90f76169e4695c208497d/lib/types.js#L68).

**Comment by bajtos** [comment]
IIRC, the root cause if this problem is that relations don't update the type of the foreign key based on the type of the `id` property they are referencing, especially when the `id` property is automatically injected by the connector. If relations were updating the type of the foreign key, then such properties should be defined as ObjectID when using MongoDB.

**Comment by fabien** [comment]
@bajtos yes, this sounds correct. The problem is that the definition was never specified to be an ObjectID. The same goes for correct MongoDB indexes for foreign keys btw.
