### ISSUE TITLE
1.18.0 breaks app

### ISSUE THREAD

**Issue by barocsi** [strongloop/loopback-connector-mongodb#332]
Just upgraded from 1.17.0 to 1.18.0 breaks when using 
var context = LoopBackContext.getCurrentContext();
var user = context.get('currentUser');

context is simply null.

```
[..]
"loopback": "^3.0.0",
    "loopback-boot": "^2.6.5",
    "loopback-component-explorer": "^4.0.0",
    "loopback-component-passport": "^1.6.0",
    "loopback-component-storage": "^1.5.1",
    "loopback-connector-mongodb": "^1.18.0",
    "loopback-context": "^1.0.0",
    "loopback-datasource-juggler": "^2.47.0",
    "loopback-ds-readonly-mixin": "^1.0.0",
    "moment": "^2.10.6",
    "mongodb": "^2.2.5",
[..]
```

**Comment by wyltsi** [comment]
I also have problems with this version when trying to get user roles for authentication. It seems to have something to do with filters. Basic find() and findOne() seem to work fine but when using filters the queries always return null.

**Comment by cojack** [comment]
I have ever worst situation, app stop to returns any results.

**Comment by smartmouse** [comment]
Hmmm.  did you check the documentation for loopback 3 migration?

https://loopback.io/doc/en/lb3/Migrating-to-3.0.html#using-current-context-in-version-30

It mentions something about the using  CurrentContext() being removed, . please take a look at the link above and see if the information is helpful. Thanks

![screen shot 2017-01-30 at 11 56 53 am](https://cloud.githubusercontent.com/assets/4519627/22432616/7caefe50-e6e3-11e6-87ab-150a60a74218.png)

**Comment by barocsi** [comment]
Sure thanks, I am aware of that, but implementing that method they invented is huge amount of work for a legacy code, and I am pretty sure that the new context replacement options propagation method BY HAND is not the future for loopback in that form, therefore I would not invest the time to maintain that big change for now.

Thanks for bringing it up tho.

**Comment by lazzyms** [comment]
Hey @barocsi , I am having the same issue and yes I removed use of current-context , but still the context is null.
