### ISSUE TITLE
[MongoDB connector] Add standard info to README

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-connector-mongodb#334]
The README doesn't have the standard sections and info that other connector READMEs, e.g. "Installation" and "Configuration".  See the [MySQL connector README](https://github.com/strongloop/loopback-connector-mysql/blob/master/README.md) as an example to use as a template.

**Comment by smartmouse** [comment]
@crandmck  Installation, Configuration , Creating DataSources, Type Mapping - Loopback to MongodbDB Data Types are the main ones.
Question to you: Where you do get the information for the Type Mapping? Is it extracted from the connector unit testcases from the connector? Or you went through the creation of different data types or by inspecting the code directly yourself?

**Comment by crandmck** [comment]
> Where do you get the information for the Type Mapping? 

@smartmouse For other connectors, the developer typically provided this info.  I don't think we ever documented for the Mongo connector, at least that I could find.  So, indeed, you may have to inspect the tests and/or code.

**Comment by smartmouse** [comment]
Information Gathering:
For the connection properties for mongodb: 
http://mongodb.github.io/node-mongodb-native/core/driver/reference/connecting/connection-settings/

**Comment by smartmouse** [comment]
Inspecting mongo.js  and try to look at unit test, does not seem to give enough information on
the  Type Mapping.  SME to rescue.

**Comment by smartmouse** [comment]
All fixes were merged.
