### ISSUE TITLE
How to execute raw mongo queries with this connector?

### ISSUE THREAD

**Issue by vivek1729** [strongloop/loopback-connector-mongodb#336]
I am trying to run raw mongo queries from loopback using this connector. My steps are as follows:

     mongo_db = app.models.Books.dataSource.connector.db;
     HubCollection = mongo_db.collection('HubAncestors');
     HunCollection.find({})
     .then(function(data){console.log(data)});

I get the following error -

`"HubCollection.find(...).then is not a function"`

I don't know at all where the issue is. I tried some other commands like `findOne` or `count` or `distinct` and it seems to be working. Can someone please explain what the issue is here. I need to use the `aggregate` command to later on so it's important that I am able to execute raw mongo queries. Also, the connector provides `find and findOne` methods on the Model but I want to use the native query functions defined on Mongo Collections. Any help is deeply appreciated.

Current config - 
`loopback": "^2.22.0","loopback-connector-mongodb": "^3.0.0"`

**Comment by smartmouse** [comment]
Not sure if this informationn helps

http://stackoverflow.com/questions/30673606/mongodb-aggregation-on-loopback

http://loopback.io/doc/en/lb2/Executing-native-SQL.html

**Comment by vivek1729** [comment]
Thanks @smartmouse. That helped me to start off in the right direction
