### ISSUE TITLE
Add missing info from old docs to README

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-connector-mongodb#340]
Information in https://docs.strongloop.com/display/LB1/MongoDB+connector (e.g. on replica set configuration) is missing from README.  Once these features are tested and confirmed, need to add it back to the README.

In particular, AFAIK, these three sections are still relevant and should be added to the README:
- [Replica set configuration](https://docs.strongloop.com/display/LB1/MongoDB+connector#MongoDBconnector-Replicasetconfiguration)
- [About MongoDB _id field](https://docs.strongloop.com/display/LB1/MongoDB+connector#MongoDBconnector-AboutMongoDB_idfield)
- [Query with logical operators](https://docs.strongloop.com/display/LB1/MongoDB+connector#MongoDBconnector-Querywithlogicaloperators(sincev1.2.3)) - I'm not sure if "v 1.2.3" refers to MongoDB or LoopBack?)

FYI @smartmouse

**Comment by crandmck** [comment]
I assume that we still need to add this info to the docs, but need to confirm.  @smartmouse @kjdelisle Who can do that?

For future reference I'm copying the relevant sections below...
---

### Replica set configuration
The LoopBack MongoDB connector supports the replica set configuration using the MongoDB connection string URI format.  For example, here is a snippet for the data source configuration:
```
{    “connector": “mongodb”,    
     “url”: "mongodb://example1.com,example2.com,example3.com/?readPreference=secondary"
}
```

### About MongoDB _id field

MongoDB uses a specific ID field with BSON ObjectID type, named `_id`.
The MongoDB connector does not expose the MongoDB _id field, to be consistent with other connectors. Instead, it is transparently mapped to the id field, which is declared by default in the model if you do not define any id.

To access the _id property, you must define it explicitly as your model ID, along with its type; For example:
```
var ds = app.dataSources.db;MyModel = ds.createModel('mymodel', {    _id: { type: ds.ObjectID, id: true }});
```

### Query with logical operators (since v1.2.3)

MongoDB supports query with logical operators such as $and, $or, and $nor. See http://docs.mongodb.org/manual/reference/operator/query-logical/ for more information.
To use the logical operators with LoopBack's query filter, you can use where clause as follows:
```
// Find posts that have title = 'My Post' and content = 'Hello'
Post.find({where: {and: [{title: 'My Post'}, {content: 'Hello'}]}}, function (err, posts) {
...
});
 
// Find posts that either have title = 'My Post' or content = 'Hello'
Post.find({where: {or: [{title: 'My Post'}, {content: 'Hello1'}]}}, function (err, posts) {
...
});
 
// Find posts that neither have title = 'My Post1' nor content = 'Hello1'
Post.find({where: {nor: [{title: 'My Post1'}, {content: 'Hello1'}]}}, function (err, posts) {
...
});
```

**Comment by dhmlau** [comment]
keeping it open for now.
