### ISSUE TITLE
Package `mongodb` updated to version `2.2.23`

### ISSUE THREAD

**Issue by vshushkov** [strongloop/loopback-connector-mongodb#344]
### Bug or feature request

- [x] Bug
- [ ] Feature request

### Description of feature (or steps to reproduce if bug)

Because of updating of `mongodb` package to version `2.2.23` a new installation of `loopback-connector-mongodb` is not working... Now `mongodb` check income options very strictly https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/mongo_client.js#L41 . So options like `url` or `debug` are triggers error...

A possible temporary solution is to lock `mongodb` version to `2.2.22`.

### Additional information (Node.js version, LoopBack version, etc)

Node.js -- 6.5.0
NPM -- 4.0.5

**Comment by azatoth** [comment]
Filed upstream at https://jira.mongodb.org/browse/NODE-934

**Comment by nachiket-p** [comment]
**For a quick solution:**
add "mongodb": "2.2.22" to your project's package.json, 
so NPM should resolve 2.2.22 instead of loopback-connector-mongodb's dependency "mongodb": "^2.2.21",

**Comment by jannyHou** [comment]
Thank you all for reporting the problem and providing solution. We will take a look ASAP. The bug fails all test case and affect lots of users.

**Comment by jannyHou** [comment]
Related pr in `mongodb`: https://github.com/mongodb/node-mongodb-native/commit/39102e11d6c905986b0971a49ace2afb770d87b2#diff-af7f90364fd34f588f43f92c13a92ab6R29

**Comment by hyperd** [comment]
Thanks!. This saved my day

**Comment by jannyHou** [comment]
We released loopback-connector-mongodb@3.0.1 and loopback-connector-mongodb@1.18.1 to fix it. Please update your connector and hope that will solve your problem.

**Comment by dhmlau** [comment]
I've verified with loopback-connector-mongodb@3.0.1 and it's working.  Closing this issue.
