### ISSUE TITLE
Filtering embedded array objects not working

### ISSUE THREAD

**Issue by kerwynrg** [strongloop/loopback-connector-mongodb#357]
- [x] Bug

I have data stored like this

Collection

```
{
    "_id" : ObjectId("<id>"),
    "finished" : false,
    "stagesDone" : [],
    "stagesToDo" : [ 
        {
            "phaseId" : "<id>",
            "name" : "Stage 1",
            "parentPhases" : [],
            "order" : 1
        }, 
        {
            "phaseId" : "<id>",
            "name" : "Stage 2",
            "parentPhases" : [],
            "order" : 1
        }, 
        {
            "phaseId" : "<id>",
            "name" : "Stage 3",
            "parentPhases" : [ 
                "5682f27471f5739818e8fabf"
            ],
            "order" : 2
        }, 
        {
            "phaseId" : "<id>",
            "name" : "Stage 4",
            "parentPhases" : [ 
                "5682f20471f5739818e8fabe", 
                "5682f27471f5739818e8fabf"
            ],
            "order" : 2
        }
    ]
}
```

```javascript
Collection.find({
  where: {
    finished: false,
    'stagesToDo.stageId': data.stageId // This is not working
  }
}, function(err, orderDetailJobs) {
  // Some code
});
```

It should query by object attribute in array, in version 1.17.0 it does but in ~1.18.0 it doesn't
I don't see any doc preventing those type of filter.

I had to downgrade to 1.17.0 because it broke my app when I applied some new features and I realized this connector upgraded and that happened.

**Comment by vkatsar** [comment]
Same issue... i had to downgrade to 1.17.0

**Comment by dhmlau** [comment]
@kerwynrg , @vkatsar , Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

Is `stagesToDo` a LB model or just the property?

**Comment by joneldiablo** [comment]
hi there!!!!
I have a little problem filtering  by an array field, using this as example, if "stagesToDo" would be the root, my requirement is filter by "parentPhases"
something like 
```
where:{parentPhases:{in:["5682f20471f5739818e8fabe"]}}
```
something like that, but not working o.O

**Comment by RunnableWeb** [comment]
@joneldiablo use **inq** operator instead of **in** - this is a loopback specific
