### ISSUE TITLE
Implement PersistedModel.getId and .setId when transposing to _id

### ISSUE THREAD

**Issue by mazesoul** [strongloop/loopback-connector-mongodb#358]
### Bug or feature request

- [ ] Bug
- [x] Feature request

### Description of feature (or steps to reproduce if bug)

When using a compound id on a model, only one of the properties gets converted to `_id`. 

### Expected result

Ideally, the connector would use [PersistedModel.getId](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-getid) and [PersistedModel.setId](https://apidocs.strongloop.com/loopback/#persistedmodel-prototype-setid) to allow different models to produce different `_id`. 

For example, I have a group that contains a set of codes and these codes are unique to their group only. I'd like to be able to set my _id to this:

```
_id: { group: 'group1', code: 'mycode'},
```

Again, there are lots of ways but if I could just rely on the connector using getId and setId as per the PersistedModel documentation, it would be much easier than using 'before save' or 'persist' or any other complex series of events.

### Additional information (Node.js version, LoopBack version, etc)

- loopback-connector-mongodb:  1.17.0

**Comment by dhmlau** [comment]
@mazesoul , it seems to be a duplicate of https://github.com/strongloop/loopback-datasource-juggler/issues/121.  If you agree, we can close this issue and continue to discussion there.

**Comment by mazesoul** [comment]
@dhmlau Hi, I believe these are closely related in terms of my end goal. That said, getId and setId could be implemented regardless of the need for composite ids. An example would be a concatenated string id that doesn't expose its prefix. e.g.: External id => "A123", Internal id => "myprefix_A123". 

This is useful when records exists in predetermined buckets.

I don't mind closing this but it seems like the two issues, although related, target two different features.

**Comment by dhmlau** [comment]
@mazesoul  fair enough.  Let's keep it separate then.  Thanks.
