### ISSUE TITLE
Filter on level 2 properties

### ISSUE THREAD

**Issue by maxaleks** [strongloop/loopback-connector-mongodb#359]
Hi. I have 2 models with "hasMany" relation and I try to make filter by array of objects.

Models:

**Application for a job:**
```
{
    "name": "application",
    "plural": "applications",
    "base": "PersistedModel",
    "idInjection": true,
    "options": {
        "validateUpsert": true
    },
    "properties": {
        "jobId": {
            "type": "string",
            "required": true
        },
        "staffId": {
            "type": "string",
            "required": true
        }
    },
    "validations": [],
    "relations": {},
    "acls": [],
    "methods": {}
}
```

**Job:**
```
{
    "name": "job",
    "plural": "jobs",
    "base": "PersistedModel",
    "idInjection": true,
    "options": {
        "validateUpsert": true
    },
    "properties": {
        "title": {
            "type": "string",
            "required": true
        }
    },
    "validations": [],
    "relations": {
        "applications": {
            "type": "hasMany",
            "model": "application",
            "foreignKey": "jobId",
            "primaryKey": "id"
        }
    },
    "acls": [],
    "methods": {}
}
```

**Staff:**
```
{
    "name": "staff",
    "plural": "staff",
    "base": "User",
    "idInjection": true,
    "options": {
        "validateUpsert": true
    },
    "properties": {
        "firstname": {
            "type": "string",
            "required": true
        },
        "lastname": {
            "type": "string",
            "required": true
        },
        "email": {
            "type": "string",
            "required": true
        }
    },
    "validations": [],
    "relations": {
        "applications": {
            "type": "hasMany",
            "model": "application",
            "foreignKey": "staffId",
            "primaryKey": "id"
        }
    },
    "acls": [],
    "methods": {}
}
```

If the user's id (staffId) is in the applications array I need to not show for user this job.

**Example:** We have array of jobs with applications
```
[
  {
    id: 1,
    title: "Job 1",
    applications: [
      {
        jobId: 1,
        staffId: 1
      },
      {
        jobId: 1,
        staffId: 2
      }
    ] 
  },
  { 
    id: 2,
    title: "Job 2",
    applications: [
      {
        jobId: 2,
        staffId: 1
      }
    ] 
  }
]
```

If user's id (staffId) is 2 then user sees only "Job 2".

I tried something like this:
`/jobs?filter[include][applications]&filter[where not][applications][elemMatch][staffId]=2`
or
`/jobs?filter[include][applications]&filter[where][applications.staffId][neq]=2`

But it doesn't work.

Is there a way to do this?

**Comment by ssh24** [comment]
@maxaleks Not sure why on your example set of jobs with applications you have `staffId` as a field even when the relation only has `jobId` as a FK

**Comment by maxaleks** [comment]
@ssh24 Do you want to see the Staff model? I think that it doesn't matter

**Comment by ssh24** [comment]
@maxaleks Please specify all the required reproduction steps, so that we can reproduce it.

**Comment by maxaleks** [comment]
@ssh24 I've updated comment with Staff model. Check please

**Comment by maxaleks** [comment]
@ssh24 Is there any progress on this issue?

**Comment by ssh24** [comment]
@maxaleks Sorry for the delay. I will look into reproducing this issue today.

**Comment by ssh24** [comment]
@maxaleks I was going through the steps you have specified. You can do something like this programmatically to actually find the `jobId` of an user who has not applied to that job yet.

Sample code:
```javascript
Application.find({'where': {'staffId': 2}}, function(err, applications) {
  if (err) return err;
  var idsNotShown = applications.map(function(res) {
    return res.jobId;
  });
  Job.find({'where': {'id': {'nin': idsNotShown}}}, function(err, jobs) {
    if (err) return err;
    console.log('Jobs for user id 2' + JSON.stringify(jobs));
  });
});
```

**_What does the code do?_** 
It queries all the application with the desired `staffId` and gets back a list of applications that user has applied to. Upon the retrieval, we map it to another array with only the `jobId`. **This jobId is the list of the jobs that user has applied to.**
Then it queries all the job where the job id is *not in* the list of jobs the user has applied to and returns that result back.

Hopefully this answered your question. Please feel free to close this issue if it fixes your problem.

**Comment by ssh24** [comment]
Hi @maxaleks, did my response above solve your question?

**Comment by maxaleks** [comment]
Hi @ssh24 
Thanks for your feedback
I do as you suggested in your solution. I just thought that there is an easier way
If there is no way to filter by the second level property in one query then the issue is closed

**Comment by ssh24** [comment]
@maxaleks Yes currently we do not have that embedded into our explorer to query such nested properties. You can create remote method similar to what I stated above and in that way you could accomplish this.

Closing this issue as the question is resolved. Feel free to reopen it if needed in the future. :)
