### ISSUE TITLE
Connection closed

### ISSUE THREAD

**Issue by edcoffin** [strongloop/loopback-connector-mongodb#36]
Attempting to grab a large data set from mongodb via REST API [ get : http://localhost:3000/api/someModel ] - should return a roughly 8mb string of JSON. This causes an error in mongodb connection pool, for which I'm not sure why --

```
{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "parseError occured",
    "stack": "Error: parseError occured\n    at null.<anonymous> (/Users/Eric/Code/spry/vbox/projects/loopback/poleApp/server/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:192:34)\n    at EventEmitter.emit (events.js:98:17)\n    at Socket.<anonymous> (/Users/Eric/Code/spry/vbox/projects/loopback/poleApp/server/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/connection/connection.js:410:20)\n    at Socket.EventEmitter.emit (events.js:95:17)\n    at Socket.<anonymous> (_stream_readable.js:745:14)\n    at Socket.EventEmitter.emit (events.js:92:17)\n    at emitReadable_ (_stream_readable.js:407:10)\n    at emitReadable (_stream_readable.js:403:5)\n    at readableAddChunk (_stream_readable.js:165:9)\n    at Socket.Readable.push (_stream_readable.js:127:10)"
  }
}
```

The problem is the node.js server stays responsive, but I can no longer query the mongodb -- there's actually no error posted to the console. Any ideas? 

loopback-connector-mongodb version: "1.3.0",
Loopback-connector version : 1.0.0

**Comment by raymondfeng** [comment]
Can you try the 1.7.0 of loopback-connector-mongodb. It uses 2.x version of mongodb driver now.

**Comment by dhmlau** [comment]
@edcoffin , as @raymondfeng suggested, please try with the latest version of `loopback-connector-mongodb`.  Feel free to reopen this issue if this problem still exists.  Thanks.
