### ISSUE TITLE
Document `strictObjectIDCoercion` flag

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-connector-mongodb#371]
# Description/Steps to reproduce

We should document the `strictObjectIDCoersion` flag for this connector which is applicable per model, so that our users do not run into issues such as #363 or #327.

# Expected result

N/A

# Additional information

N/A

**Comment by ssh24** [comment]
Related to https://github.com/strongloop-internal/scrum-apex/issues/146. Closing this.
