### ISSUE TITLE
Duplicate id and _id when update document 

### ISSUE THREAD

**Issue by hoangtrongphuc** [strongloop/loopback-connector-mongodb#372]
# Description/Steps to reproduce
When I get record from mongo database, I have id property. If I update document by replaceById, record have id and _id property in database

# Expected result
Only _id property in database

# Additional information

**Comment by ssh24** [comment]
@hoangtrongphuc Not sure what the issue you are running into here. If you get some record from the mongo database with a `find` call, and update some document with `replaceById` with one of the ids you got from find, it works as expected. Here is a sample code:

**model-definition.json**
```json
{
  "name": "Employee",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "number"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mongoDs;
  var Employee = app.models.Employee;

  db.automigrate(function(err) {
    if (err) throw err;
    Employee.create([{name: 'Sakib', age: 1}, {name: 'Joy', age: 2}],
    function(err, result) {
      if (err) throw err;
      console.log('\nCreated instance: ' + util.inspect(result, 4));

      Employee.find(function(err, result) {
        if (err) throw err;
        console.log('\nFound instance: ' + util.inspect(result, 4));
        var id1 = result[0].id;

        Employee.replaceById(id1, {name: 'Sakib-updated', age: 12}, function(err, result) {
          if (err) throw err;
          console.log('\nReplace by id: ' + util.inspect(result, 4));

          Employee.find(function(err, result) {
            if (err) throw err;
            console.log('\nFound instance: ' + util.inspect(result, 4));
          });
        });
      });
    });
  });
};
```

**output**
```bash
sakibs-mac:mongodb-46 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Created instance: [ { name: 'Sakib', age: 1, id: 5940418a2ce9a359922ec6c4 },
  { name: 'Joy', age: 2, id: 5940418a2ce9a359922ec6c5 } ]

Found instance: [ { name: 'Sakib', age: 1, id: 5940418a2ce9a359922ec6c4 },
  { name: 'Joy', age: 2, id: 5940418a2ce9a359922ec6c5 } ]

Replace by id: { name: 'Sakib-updated', age: 12, id: 5940418a2ce9a359922ec6c4 }

Found instance: [ { name: 'Sakib-updated', age: 12, id: 5940418a2ce9a359922ec6c4 },
  { name: 'Joy', age: 2, id: 5940418a2ce9a359922ec6c5 } ]
```

**database output**
```bash
> db.Employee.find();
{ "_id" : ObjectId("5940418a2ce9a359922ec6c4"), "name" : "Sakib-updated", "age" : 12 }
{ "_id" : ObjectId("5940418a2ce9a359922ec6c5"), "name" : "Joy", "age" : 2 }
```

Hopefully this will help you with your question.

**Comment by hoangtrongphuc** [comment]
I replaceById with result record which returned from DB directly.
This code
`Employee.replaceById(id1, result, function(err, result) {
       
        });`

**Comment by ssh24** [comment]
> I replaceById with result record which returned from DB directly.
Note this code: 
Employee.replaceById(id1, result, function(err, result) {});

@hoangtrongphuc What you did there is replace the instance where the id matches `id1` with all the instances you got back from a `find` operation.

**Comment by hoangtrongphuc** [comment]
Sry for my bad. 
"result" is record returned from findOne method of loopback.
I use "result" directly in replaceById.

**Comment by ssh24** [comment]
@hoangtrongphuc I am not sure why would you used the result you get from `findOne` to replace an instance of the same id. There is no purpose of that, however, it should still work. Here is the code snippet:
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mongoDs;
  var Employee = app.models.Employee;

  var employees = [{name: 'Sakib', age: 11},
  {name: 'Joy', age: 22},
  {name: 'Foo', age: 33}];

  db.automigrate(function(err, result) {
    if (err) throw err;
    Employee.create(employees, function(err, result) {
      if (err) throw err;
      console.log('\nCreated employees: ' + util.inspect(result, 4));

      Employee.findOne(function(err, result) {
        if (err) throw err;
        console.log('\nFound one employee: ' + util.inspect(result, 4));

        var id = result.id;
        Employee.replaceById(id, result, function(err, result) {
          if (err) throw err;
          console.log('\nReplace by id employee: ' + util.inspect(result, 4));

          Employee.find(function(err, result) {
            if (err) throw err;
            console.log('\nFind employees: ' + util.inspect(result, 4));
          });
        });
      });
    });
  });
};
```
**output**
```bash
sakibs-mac:mongodb-372 ssh$ node .
Web server listening at: http://0.0.0.0:3000
Browse your REST API at http://0.0.0.0:3000/explorer

Created employees: [ { name: 'Sakib', age: 11, id: 59414b87a819eda764502dda },
  { name: 'Joy', age: 22, id: 59414b87a819eda764502ddb },
  { name: 'Foo', age: 33, id: 59414b87a819eda764502ddc } ]

Found one employee: { name: 'Sakib', age: 11, id: 59414b87a819eda764502dda }

Replace by id employee: { name: 'Sakib', age: 11, id: 59414b87a819eda764502dda }

Find employees: [ { name: 'Sakib', age: 11, id: 59414b87a819eda764502dda },
  { name: 'Joy', age: 22, id: 59414b87a819eda764502ddb },
  { name: 'Foo', age: 33, id: 59414b87a819eda764502ddc } ]
```

**Comment by ssh24** [comment]
Closing this issue as resolved. Feel free to reopen if needed.

**Comment by pierreclr** [comment]
Is this resolved ? I still have this problem on loopback  3.8

**Comment by alzab** [comment]
I think I'm also seeing this issue, but in a slightly different context - for example: if I PATCH a model, i.e. at /api/Model/<id>, I can pass a value for "id" in the request JSON, as long as it's the same as <id>, and doing so will add a redundant "id" field to the stored model aside from the actual _id. It seems as though this specific case should simply be ignored (i.e. we already have the actual "_id" stored)?

Perhaps I'm missing something obvious? Apologies if so!

**Comment by chris08002** [comment]
@alzab When I try to update the title of an existing document `_id: "xy"` with `model.upsert({id: "xy", title: "test"})` the resulting object looks like `{_id: "xy", title: "test", id: "xy"}`, so the `id` is redundant. Is this the same behaviour as you describe? It doesn't happen when I do a PUT with the api explorer.

**Comment by luncht1me** [comment]
I'm having this issue currently with PATCH / Upsert .

I simply have a .findById() pulling my document to my website, then when I .upsert() the instance (which hits the api via PATCH), I get "id" field in my database for that document.

**Comment by aitorllj93** [comment]
Same as other people,
Running PATCH with id field creates a new "id" field on mongo
