### ISSUE TITLE
connection parameters not working

### ISSUE THREAD

**Issue by yatingodse** [strongloop/loopback-connector-mongodb#375]
HI ,
I am using loopback 3.0 and mongodb 3.3.4
I am facing particular issue regarding the parameters , when i tried to pass the following parameters in the connection string it did not worked and throws error as **Not supported**
Parameters used are
minPoolSize
maxIdleTimeMS
waitQueueMultiple
waitQueueTimeoutMS

I can not find any documentation that this parameters are not supported.
Can any one confirm on this ?

**Comment by dhmlau** [comment]
@yatingodse , we're using the mongodb node module, so their connection settings options can be found here: http://mongodb.github.io/node-mongodb-native/2.2/reference/connecting/connection-settings/

**Comment by dhmlau** [comment]
@yatingodse , I believe your questions have been answered.  Closing this issue.  Thanks.

**Comment by yatingodse** [comment]
Yes , Thanks 
I checked in Node Native drivers the functionality i needed is not available in the drivers itself.
