### ISSUE TITLE
Need to install loopback connector on Linux machine where we dont have Internet connection

### ISSUE THREAD

**Issue by gobisankaran** [strongloop/loopback-connector-mongodb#384]
I need to install loopback-connector-mongodb on linux redhat server which is not having Internet connection, could you please suggest the steps to do that?
# Description/Steps to reproduce

# Expected result

# Additional information

**Comment by ssh24** [comment]
You can download the `.zip` file from the [connector repo](https://github.com/strongloop/loopback-connector-mongodb) and ftp it to the linux machine.

**Comment by dhmlau** [comment]
After downloading the zip file, you can run `npm install <tarball file>`.  For details, please refer to the [npm documentation ](https://docs.npmjs.com/cli/install).

We believe your question has been answered.  Closing this issue.  Feel free to reopen if the problem still exists.  Thanks.
