### ISSUE TITLE
this framework sucks

### ISSUE THREAD

**Issue by reduxdj** [strongloop/loopback-connector-mongodb#385]
# Description/Steps to reproduce

# Expected result

# Additional information

**Comment by reduxdj** [comment]
This connector is the absolute worst. Why, it's so unfortunate, I feel like writing a 10,000 word essay why this is such an unfortunate terrible design of breaking queries, on multiple fields. I inherited this eco-system and I am on a rapid pace to pull out this strongFAIL framework as soon as I can. The problem with a system that tries to do "everything" is that it fails at it's missions. 

I can't believe IBM bought this company. I can't believe along the way you convinced yourselves that trying to make a DB connector to them All was the way to go. Instead, you leave me pulling out my hair to try to do the most simple MongoDB queries with multiple fields.
👿 👿 👿 👿 👿 👿 👿 👿 👿 👿 👿 👿 👿 👿

**Comment by sakesun** [comment]
FWIW, loopback-connector-postgresql is terrible also.

**Comment by kjdelisle** [comment]
If you have concerns about the current design of loopback or its connectors, I would strongly encourage you to leave your feedback in the [loopback-next](https://github.com/strongloop/loopback-next) repository instead, so that you can help influence the design of the next major version.
