### ISSUE TITLE
Support of property as id AND keep the auto generated _id internaly

### ISSUE THREAD

**Issue by mpoiriert** [strongloop/loopback-connector-mongodb#391]
I have a use case that a document structure should look like this:

```
{
  "_id" : ObjectId("59b329d85aea1a1d3b0f28ac"),
  "productId": "3552b8f0-94d8-11e7-961f-957a461a54c2"
}
```

I want to manipulate the document by the productId (ex: GET /products/3552b8f0-94d8-11e7-961f-957a461a54c2)

The _id property should be generated by mongo and hidden by the client.

If I am setting the productId: { id: true }

It will work has expected for the client but internally the document will be store like this:

```
{
  "_id" : "3552b8f0-94d8-11e7-961f-957a461a54c2"
}
```
I look around and I think a lot of issue would be solve by changing the mongodb.js and removing all the attribute name swapping from the configure id to "_id" and using the model id column instead of "_id".

If someone want to have the current behaviour he should specify a column name as "_id".

The also the issue of foreign keys that I didn't check.

There is advantage to keep the ObjectID for the _id value it's why I want both behaviour.

IMHO the ORM/ODM/API should be the less bounded possible to the persistence engine under. Right now the Client API is bounded to the persistence layer under it.

**Comment by ninoguba** [comment]
I think you just need to set "idInjection": false in your model's json.

**Comment by mpoiriert** [comment]
This create a "fake" id expose to the user base on the property I define as the id but in mongo it's creating a _id property. I need both. I need the _id generated by mongo that is never use and the "customId" that is use for the endpoint and everything.
