### ISSUE TITLE
Id of related model is not converted to an ObjectID when using the "gt" operator

### ISSUE THREAD

**Issue by luxigo** [strongloop/loopback-connector-mongodb#395]
Using comparison operators with a model object Id in a where clause works fine:
```where: {id: {gt: '58e7dc2d0d48ca5ff62362e3'}}```

However an empty result is returned when trying to to use comparison operators with a related model object id in a where clause:
```where: {someId: {gt: '58e7dc2d0d48ca5ff62362e3'}}```

**Comment by luxigo** [comment]
Huh sorry it works with another model...

Any idea about how to spot the problem ?

**Comment by luxigo** [comment]
Looks like it works with "belongsTo" but not with "hasOne"

**Comment by bugdanov** [comment]
It appears that the id of the related model of a hasOne relation is converted to a string when using the "gt" operator with it (note the single quotes):

```loopback:connector:mongodb MongoDB: model=myModel command=find [ { someId: { '$gt': '59d8df203d162a00d46f8ace' } },```

Things are fine when using gt with the model id (its value is unquoted):
 ```loopback:connector:mongodb MongoDB: model=myModel command=find [ { _id: { '$gt': 59d8df203d162a00d46f8ace } }, ```

**Comment by luxigo** [comment]
Ok it has to do with objectId coercion, you can use ObjectId() server side but when using the loopback-sdk-angular you cannot do nothing (yet) but write a remote method to work around it.
