### ISSUE TITLE
Update to eslint 4

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-mongodb#408]
Description:

The eslint in this repo is too old and causes lots of conflict when coding in es6 style, http://loopback.io/doc/en/contrib/style-guide.html

Upgrade to 
```
"eslint": "^4.13.1",
"eslint-config-loopback": "^10.0.0",
```

And get CI pass.

**Comment by dhmlau** [comment]
with the current version of eslint, is the CI failing?
