### ISSUE TITLE
Critical breaking change with connector urls in version 3.4.0

### ISSUE THREAD

**Issue by nitro404** [strongloop/loopback-connector-mongodb#412]
# Description/Steps to reproduce

After updating from version 3.3.1 to 3.4.0 and attempting to run my Loopback API with an attached Mongo database using this connector, a MongoError is raised with the message:

> MongoError: database name must be a string

No configuration settings have been changed, so I believe this is an issue with something that may have been overlooked with the latest update to version 3 of the MongoDB module. It seems to work fine when you split the connection up into its individual components (ie. host, port, database, etc.) but if you just give a url string it fails.

# Link to reproduction sandbox

https://github.com/nitro404/loopback-mongodb-connector-sandbox

# Expected result

API should boot successfully without any errors.

**Comment by raymondfeng** [comment]
@nitro404 Thank you for catching it. Can you verify that https://github.com/strongloop/loopback-connector-mongodb/pull/413 fixes the issue?

**Comment by nitro404** [comment]
@raymondfeng No worries! After manually swapping out the node module, it does indeed seem to work. Thank you so much for following up on this so quickly!

**Comment by jdschreck** [comment]
Version 3.4.1 does not seem to be able to connect to our database still.

**Comment by jdschreck** [comment]
Dumping the options going into connectHandler in mongo_client.js, it looks like

options.user = ""
options.password = ""

but there is now an auth member of options:

options.auth.user ='thecorrectuserid'
options.auth.password='thecorrectpassword'

but the authenticate function is being called with the empty ones.

**Comment by jdschreck** [comment]
I tracked this down to a place in our code that was erroneously passing a blank userid and password to the app.dataSource command.  I believe this is inconsistent with the mysql connector.  There it seemed that the url was overriding whatever information was provided in individually specified fields.  This code works for 3.3.0 but not for 3.4.1, so something definitely changed in the precedence.

**Comment by kjdelisle** [comment]
cc @raymondfeng @nitro404
