### ISSUE TITLE
Add case insensitive indexes support

### ISSUE THREAD

**Issue by angfal** [strongloop/loopback-connector-mongodb#414]
# Description

MongoDB allows to create and search by case insensitive indexes. The problem to support this feature it's required to execute separate "collation" function for a MongoDB cursor which is hidden by loopback and no way to receive access to it. As the result, no a reasonable way somehow wrap loopback functions to use such functionality via loopback.

Ideally, it would be great to add the support of this parameter for loopback MongoDB connector. For example using filter:
```
Model.find({
    where: {...}, 
    collation: {
        locale : <locale>,
        strength : <strength>
    }
});

// mongodb.js:
MongoDB.prototype.all = function all(model, filter, options, callback) {
    ...
    function processResponse(err, cursor) {
        ...
       if (filter.collation) {
           cursor.collation(filter.collation)
       }
        ...
    }
}
```

or using options (to not corrupt filter schema which common for all datasource)
```
Model.find({where: {...}}, {
    collation: {
        locale : <locale>,
        strength : <strength>
    }
});
```

Links:
- https://docs.mongodb.com/manual/core/index-case-insensitive

**Comment by kjdelisle** [comment]
@angfal Pull requests are welcome. My experience with mongodb is somewhat limited, though your 2nd proposal sounds solid to me. If you're willing to make a PR with test coverage, I'll review it and help you land it. :)

**Comment by angfal** [comment]
@kjdelisle Great! I will make the required fixes

**Comment by angfal** [comment]
Please, somebody review my pr

**Comment by angfal** [comment]
Additional info in the PR

**Comment by barocsi** [comment]
ok so how to use it within a mongodb query?

**Comment by ryan-open** [comment]
@barocsi https://github.com/strongloop/loopback-connector-mongodb/blob/260733d21e6d9cf73947c3dc08a53e650f37f766/test/mongodb.test.js#L2714
