### ISSUE TITLE
Losing context data

### ISSUE THREAD

**Issue by pbalan** [strongloop/loopback-connector-mongodb#421]
# Description/Steps to reproduce
I wrote a loopback component and all my tests are working with memory db.
However, when I change datasource to mongodb, I do not see the context data in operation hook.

1. clone the repo below.
2. npm test
3. git checkout test-mongo
4. npm test

# Link to reproduction sandbox
https://github.com/pbalan/component-reproduce-error.git

Master Branch: runs with memory connector.           **TEST PASS**
<img width="662" alt="screen shot 2018-03-07 at 20 56 27" src="https://user-images.githubusercontent.com/3174988/37093409-3500d04e-224a-11e8-9574-4abf899b9517.png">

test-mongo Branch: runs with mongodb connector. **TEST FAIL**
<img width="1213" alt="screen shot 2018-03-07 at 20 57 06" src="https://user-images.githubusercontent.com/3174988/37093420-3d331f9c-224a-11e8-809c-fa7085056fba.png">

[Error thrown in source](https://github.com/pbalan/component-reproduce-error/blob/test-mongo/common/models/Model.Brand.js#L153-L154)

# Expected result
**TEST PASS**

# Additional information

  node -e 'console.log(process.platform, process.arch, process.versions.node)': **darwin x64 8.9.4**
  npm ls --prod --depth 0 | grep loopback **loopback-connector-mongodb@3.4.1**

**Comment by pbalan** [comment]
@raymondfeng @bajtos Any solution to this yet?

**Comment by bajtos** [comment]
@pbalan I am afraid the link https://github.com/pbalan/component-reproduce-error.git returns 404 to me. Is your repository perhaps private? Could you please make it public or at least grant me and my colleagues read access?

**Comment by pbalan** [comment]
@bajtos Sorry for the late response. I resolved this issue as it was not related to loopback context but appeared prima-facie.
I resolved the issue related to loopback-context on single model using local object previously to avoid loopback-context altogether.

However, I again stumbled on the same problem today. Am trying to get loopback context inside middleware. @matt-landers [solution](https://github.com/strongloop/loopback/issues/1495#issuecomment-346957597) doesn't work for me on
loopback@3.18.2.
loopback-connector-mongodb@3.4.1

**Comment by pbalan** [comment]
Previously, I had implemented a before delete and after delete operation hook through hookstate.
The solution to the above specific problem was to override remote method.

```
const deleteById = Model.deleteById;

    Model.deleteById = (id, cb) => {
      Model.updateAll({id: id}, {
        deletedAt: new Date(),
        deletedBy: cb.accessToken.userId,
      }, cb);
    };
```

**Comment by bajtos** [comment]
@pbalan sorry, I have no idea how to reproduce the problem you are experiencing, therefore I am not able to help you.

However, I noticed a suspicious thing in your code example - you are treating `cb` as an `options` object. I think the following code should work better for you:

```ts
Model.deleteById = (id, options, cb) => {
  Model.updateAll({id: id}, {
    deletedAt: new Date(),
    deletedBy: options.accessToken.userId,
  }, cb);
};
```
