### ISSUE TITLE
Connection fails: MongoError: Authentication failed.

### ISSUE THREAD

**Issue by michaelerobertsjr** [strongloop/loopback-connector-mongodb#422]
# Description/Steps to reproduce

Add loopback connector to project:

```
$ npm install loopback-connector-mongodb
```

# Expected result

Ability to connect to mongodb instances using latest `^3.4.1`

Instead the breaking changes from the mongodb.client causes:

`Connection fails: MongoError: Authentication failed.`

Issue: [412](https://github.com/strongloop/loopback-connector-mongodb/issues/412) **IS NOT RESOLVED** for me and probably needs to be re-opened.

**Comment by raymondfeng** [comment]
@michaelerobertsjr How do you pass in user/password (1 or 2)?

1. `{user: 'u', password: 'p'}`
2. `{auth: {user: 'u', password: 'p'}}`

**Comment by jura-b** [comment]
From what I've experience, it seems like you always need a mongo user to connect to mongo server.

Leaving username and password empty will fail the authentication even you haven't setup any mongo user.
