### ISSUE TITLE
MongoClient 3.0 initializes wrong database!!!

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-connector-mongodb#423]
# Description/Steps to reproduce
**Critical Bug from transition to MongoDB 3.0 Client**
According to documentation of [MongoDB connector](http://loopback.io/doc/en/lb3/MongoDB-connector.html#setting-the-url-property-in-datasourcejson), when providing a `url` it overrides the other settings provided in the JSON configuration.

However this is not the case after the upgrade to MongoClient 3.0.
Providing this config:
```json
{
    "host": "localhost",
    "port": 27017,
    "url": "mongodb://localhost/test-db-1",
    "database": "production-db-1",
    "password": "",
    "name": "mongoDs",
    "user": "",
    "connector": "mongodb"
  }
```
It should use the `url` property and connect to `test-db-1` database as it used to in earlier versions. However right now, it initializes the provided `database` entry: `production-eu-1`.
We found out because we used the `url` property to override database connection for our testing environments... and **it used production!!!**

This is due to [Line 228](https://github.com/strongloop/loopback-connector-mongodb/blob/4e489c2436a4a661bdd7175cd5089d17fc1b528a/lib/mongodb.js#L228) where the MongoClient initializes the db with priority of provided `database` option first instead of ul

# Expected result
It should use the overridden `url` connection string along with its database there.

# Additional information

linux x64 9.8.0
loopback-connector-mongodb@3.4.1

**Comment by dhmlau** [comment]
Closing it as PR #424 has landed.
