### ISSUE TITLE
Connector not managing and closing mongodb connections

### ISSUE THREAD

**Issue by jocelynk** [strongloop/loopback-connector-mongodb#429]
I am using Compose for MongoDB and facing an issue using the connector where connections are accumulating, but not being closed. Because of this issue, I have written a boot up script to explicitly close the connections after every execute of the datasource, but it still is not closing:

```
module.exports = function (app) {
  const connector = app.models.collection.getDataSource().connector;
  connector.observe('after execute', function(ctx, next) {
    app.dataSources.db.disconnect(next);
  });
}
```

I am initializing my mongo connection with only a maxPoolSize of 2, yet according to the Compose Team we are maxing out the 5000 connection limit.
```
let url = process.env.MONGO_CREDENTIALS? credentials['uri'] : process.env.MONGO_CONNECTION_URL;
url += "\u0026maxIdleTimeMS=300000\u0026maxPoolSize=2";
var dataSources = {
  mongo: {
    "url": url,
    "name": "mongo",
    "connector": "mongodb",
    "size": 2
  },
};
```
# Additional information

darwin x64 9.6.1
Using: 
npm info using npm@5.6.0
npm info using node@v9.6.1
├── loopback@3.18.3
├── loopback-boot@2.27.1
├── loopback-cascade-delete-mixin@2.0.0
├── loopback-component-explorer@5.3.0
├── loopback-component-storage@3.3.1
├── loopback-connector-mongodb@3.4.3
├── loopback-connector-rest@3.1.1
├── loopback-counts-mixin@1.0.1
├── loopback-datasource-juggler@3.16.0

**Comment by raymondfeng** [comment]
Mongodb connection pool is managed by the driver. Can you do some profile to see how many concurrent in-flight requests you have? If the DB is slow in responding, the number of open connections will grow.

But it's weird in your case as the `maxPoolSize` is set to 2 and the max number of connections should be only 2 unless you have multiple instances of the same datasource.

**Comment by raymondfeng** [comment]
If you have a mongodb datasource with `maxPoolSize` parameter in the url or `poolSize` in the config, I don't see why the client can go beyond that limit. 

See http://mongodb.github.io/node-mongodb-native/3.0/reference/connecting/connection-settings/

**Comment by raymondfeng** [comment]
@jocelynk My theory is that you have many developers (`D`) running multiple instances of the the same app (`A`) during development. Assuming each app has a datasource for mongodb with pool size of `S`, it will create `D * A * S` connections to compose hosted mongodb.

Please note the app is running and holding the connection pool during VSCode debug sessions.

We can check if `node-postgres` has an option to shrink the connection pool automatically by closing idle connections.

The `disconnect` function closes the connection pool and it should help.

**Comment by mhamann** [comment]
@jocelynk what about the mongodb server version? What does your Compose dashboard show?

**Comment by jocelynk** [comment]
@raymondfeng that would be great thanks. We have not noticed our connections maxing out on applications running on our clusters, so we have decided to explore this more at a later date.

@mhamann We are using MongoDB (3.2.18).

**Comment by raymondfeng** [comment]
You can set `idleTimeoutMillis` in the datasource so that idle connections are removed. If not set, the default value is `10 seconds`.

**Comment by alidavid0418** [comment]
@raymondfeng  I cannot find the `idleTimeoutMillis` option in the README doc.
Is it still available for MongoDB 4.0? The same goes for `poolSize`.
Thanks in advance.

**Comment by GeniusBrother** [comment]
@raymondfeng  I also cannot find idleTimeoutMillis options in node mongodb driver

**Comment by bala-fashiondx** [comment]
Is the issue fixed because I am also facing this issue , connections were increasing in mongodb . The connections were only closing after only the application stops .  please let me know , how can I implement **idleTimeoutMillis** in loopback-mongodb-connector.
