### ISSUE TITLE
Security issues with outdated dependency

### ISSUE THREAD

**Issue by franher** [strongloop/loopback-connector-mongodb#433]
# Description/Steps to reproduce

There is a security vulnerability in `"strong-globalize": "^3.1.0"` (see [Prototype Pollution](https://nodesecurity.io/advisories/612) for more details).

<img width="416" alt="prototype pollution vulnerability" src="https://user-images.githubusercontent.com/10708215/40607963-41b070a0-626a-11e8-89e9-ad42d33e64b0.png">

To reproduce it set up a project with latest loopback-connector-mongodb (v3.4.3) as dependency and run `nsp`over it:

```bash
$> npm init
$> npm i --save loopback-connector-mongodb
$> npx nsp -- check
```

The vulnerability comes from `strong-globalize@3.3.0 > g11n-pipeline@2.0.5 >  swagger-client@3.4.6 > deep-extend@0.4.2` . All the related packages with the issue have release a version fixing the vulnerability:

* https://github.com/unclechu/node-deep-extend/issues/41
* https://github.com/swagger-api/swagger-js/issues/1304
* https://github.com/IBM-Cloud/gp-js-client/issues/121

`strong-globalize@4.x` is released few days ago, so updating it here would fix the issue.

# Link to reproduction sandbox

Not apply for this issue.

# Expected result

Not security vulnerabilities after running `nsp` or `npm audit`.
 

# Additional information

* Result of `node -e 'console.log(process.platform, process.arch, process.versions.node)'`

```bash
darwin x64 8.11.2
```

* Result of `npm ls --prod --depth 0 | grep loopback`

```bash
├── loopback@3.19.1
├── loopback-boot@2.27.1
├── loopback-component-explorer@2.7.0
├── loopback-connector-mongodb@3.4.3
├── loopback-filters@1.0.0
├── loopback3-xtotalcount@0.1.2
```

**Comment by virkt25** [comment]
@franher Can you please try this again -- `npm i` for me installs `deep-extend@0.5.1` which is not vulnerable. `nsp` comes clean for me.

**Comment by franher** [comment]
@virkt25 You're right. Now, installing loopback-connector-mongodb v3.4.3 and v3.4.4 the security issue is out.

Thank you for your time.
