### ISSUE TITLE
   collection.aggregate not working 

### ISSUE THREAD

**Issue by kumarpsr** [strongloop/loopback-connector-mongodb#434]
ModelName.getDataSource().connector.connect(function(err, db) {
        var collection = db.collection('branch');
        collection.aggregate([{$unwind: '$flexmaster'}], function(err, data) {
            console.log(data);
          if (err) return callback(err);
          return callback(err, data);
        });
       
      });

aggregate method throws an exception on run time in version loopback-connector-mongodb 3.4.3, but  it was working fine on version loopback-connector-mongodb 1.18.1

**Exception Below**

E:\Loop\node_modules\mongodb\lib\utils.js:132
      throw err;
      ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at stringify (E:\Loop\node_modules\express\lib\response.js:1119:12)
    at ServerResponse.json (E:\Loop\node_modules\express\lib\response.js:260:14)
    at Object.sendBodyJson [as sendBody] (E:\Loop\node_modules\strong-remoting\lib\http-context.js:437:7)
    at HttpContext.done (E:\Loop\node_modules\strong-remoting\lib\http-context.js:578:24)
    at E:\Loop\node_modules\strong-remoting\lib\rest-adapter.js:539:11
    at E:\Loop\node_modules\async\dist\async.js:3888:9
    at E:\Loop\node_modules\async\dist\async.js:473:16
    at replenish (E:\Loop\node_modules\async\dist\async.js:1006:25)
    at iterateeCallback (E:\Loop\node_modules\async\dist\async.js:995:17)
    at E:\Loop\node_modules\async\dist\async.js:969:16
    at E:\Loop\node_modules\async\dist\async.js:3885:13
    at interceptInvocationErrors (E:\Loop\node_modules\strong-remoting\lib\remote-objects.js:721:22)
    at E:\Loop\node_modules\loopback-phase\node_modules\async\lib\async.js:154:25
    at E:\Loop\node_modules\loopback-phase\node_modules\async\lib\async.js:154:25
    at E:\Loop\node_modules\loopback-phase\node_modules\async\lib\async.js:154:25

**Comment by Eslem** [comment]
I think is not working because aggregation changed, now return a AggregationCursor.
To used as before:
```javascript

ModelName.getDataSource().connector.connect(function(err, db) {
  var collection = db.collection('branch');
  var cursor = collection.aggregate([{$unwind: '$flexmaster'}]);
  cursor.get(function(err, data) {
    console.log(data);
    if (err) return callback(err);
    return callback(err, data);
  })
});
```

**Comment by ducl13** [comment]
This pattern worked for me.

    var collection = ModelName.getDataSource().connector.collection("myCollection");
    collection.aggregate(
      [
        ...
      ],
      function(err, cursor) {
        if (err) {
          ...
        } else {
          cursor.on("data", function(doc) {
            // doc contains whatever you project in the aggregate call
            ...
          });

          cursor.once("end", function() {
          });
        }
      }
    );

It was based on this: http://mongodb.github.io/node-mongodb-native/2.0/tutorials/streams/ (section Aggregation Cursor as a Stream).

It seems to work asynchronously.    I have multiple aggregate calls that I wanted to combine. I had to string them together using async waterfall. (https://caolan.github.io/async/docs.html#waterfall)
