### ISSUE TITLE
Don't output null values in JSON - don't store NULL values by default

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-connector-mongodb#44]
It's a waste of bandwidth, and non-standard behavior (which probably is the result of BSON handling null, whereas JSON doesn't). Aparently NULL values are indeed inserted into the MongoDB documents.

An option to disable this somehow (on the input as well as output side of things) seems to be in order.

**Comment by smartmouse** [comment]
@fabien yes, storing NULL in mongodb will consume diskspace and RAM.  Some people uses NULL  deliberately and they have their specific reasons. 
To add an option will be an enhancement for considerations and prioritization by product owner.  But thank you for your time to provide good feedback.
