### ISSUE TITLE
Field '_id' missing when using filter.fields

### ISSUE THREAD

**Issue by tachylatus** [strongloop/loopback-connector-mongodb#440]
# Description/Steps to reproduce
1. Create a model with an `_id` property used as id, and some instances.
2. Get all instances using the filter `{"fields": {"_id": true}}`.
3. Observe that the returned objects are empty. The `_id` field is missing from the results.

# Link to reproduction sandbox

No link.

# Expected result
```
[
  {
    "_id": "558b0ab053f37833ca7cd4f9"
  },
  {
    "_id": "558b0ab053f37833ca7cd4fa"
  }
]
```

# Actual result
```
[
  {},
  {}
]
```

# Additional information
See pull request #439
win32 x64 8.11.1
loopback-connector-mongodb@3.4.4

**Comment by boltonomous** [comment]
Experiencing similar issues.  This has rendered us unable to take advantage of filter.fields in many cases.
