### ISSUE TITLE
Get the custom collection name

### ISSUE THREAD

**Issue by char781227** [strongloop/loopback-connector-mongodb#446]
Hello everyone, 

Currently, I came across a problem. I have a MongoDB model with a [custom collection name](https://loopback.io/doc/en/lb2/Model-definition-JSON-file.html#data-source-specific-options) in his definition JSON file and I would like to know if it's possible to get this name in his .js file.

I tried with model.modelName but it gives the default collection name, not the custom...

Thanks a lot!

**Comment by char781227** [comment]
I resolved this myself... 

Solution : 
MyModel.definition.settings.mongodb.collection

**Comment by dhmlau** [comment]
Glad to hear.  Closing this issue as resolved.  Thanks!
