### ISSUE TITLE
Deprecation warnings about collection APIs

### ISSUE THREAD

**Issue by b3rew** [strongloop/loopback-connector-mongodb#455]
# Description/Steps to reproduce
I am gettiing DeprecationWarning message when i try to insert data into my model
 
`(node:13177) DeprecationWarning: collection.insert is deprecated. Use insertOne, insertMany or bulkWrite instead.`

Mongo: v3.6.3
Nodejs : v8.11.2
loopback: v3.22.1
loopback-connector-mongodb: v3.6.0

**Comment by PhilippeCorreges** [comment]
Same here.

**Comment by ServisionFrontend** [comment]
Same here. my use "Repository" create method 
![image](https://user-images.githubusercontent.com/20966741/44832280-d8426a00-ac5c-11e8-8702-a69c0edcfb58.png)

**Comment by suisun2015** [comment]
How can I fix this caution? Thanks

**Comment by matteo-pennisi** [comment]
+1

**Comment by janiscp** [comment]
+1

**Comment by virkt25** [comment]
Would anyone be interested in submitting a PR for this? The task would involve checking to ensure the API between the deprecated / current API is the same and if not make the necessary code changes. Ensure the current test suite passes. 

See https://github.com/strongloop/loopback-connector-mongodb/pull/450/files for an example PR that changed the deprecated `count` to `countDocuments`.

**Comment by Yaty** [comment]
@virkt25 I'll look into this tonight :)

**Comment by Yaty** [comment]
OK for remove, see PR #461 .
insert, findAndModify, save and update seems to need more work than just updating the command :)
I'll see what I can do.

**Comment by virkt25** [comment]
Fixed by #461 and released in version 3.7.0

**Comment by virkt25** [comment]
Special thanks to @Yaty for the PR to update the underlying driver calls! 🙇 🎉
