### ISSUE TITLE
How to create MongoDB entry with "NumberDecimal" Format i.e Decimal128 Data Type

### ISSUE THREAD

**Issue by gobisankaran** [strongloop/loopback-connector-mongodb#457]
# Description/Steps to reproduce
Clarification on NumberDecimal creation with MongoDB using Strongloop

I have created a simple Model in which I want to Insert a NumberDecimal datatype
When I try to create a model with Decimal128 it says "Swagger: skipping unknown type "Decimal128"."

Can you please help me to insert a sample value which should create a entry in MongoDB database with datatype "NumberDecimal i.e Decimal128" and retrieve in the same format?

Is it supported right now with loopback connector?

My sample model file looks like below
{
  "name": "DTM",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "NumDec": {
      "type": "Decimal128"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

Thanks in Advance.

Regards,
Gobi S.

# Link to reproduction sandbox

# Expected result

# Additional information

**Comment by virkt25** [comment]
The type should just be `number` as MongoDB doesn't have the concept of a `DECIMAL128` AFAIK.

**Comment by gobisankaran** [comment]
Basically My sample model looks like this
{
  "name": "Decimal",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "NumDec": {
      "type": "object",
      "mongoIIB": {
        "dataType": "Decimal128"
      }
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}

I want to insert a data into MongoDB as ""NumberDecimal" Data type.

If I use the above model it is inserting the value as either Integer or Double. I need to insert object as "NumberDecimal" i.e Decimal128 DataType.

Please refer this link for NumberDecimal Datatype : https://docs.mongodb.com/manual/core/shell-types/

**Comment by virkt25** [comment]
LoopBack doesn't have a `decimal128` type. Here's a list of supported types in LoopBack: https://loopback.io/doc/en/lb3/LoopBack-types.html 

This connector at this time does not have support for `dataType: decimal` which is present in `sql` connectors.

**Comment by raymondfeng** [comment]
A few steps need to happen
1. Check if mongodb driver accepts and coerces strings to decimal 128
2. Depending on the outcome of 1, decide if `string` is good enough for JS/REST. If not, a custom Type needs to be defined (see https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L20 as an example)
3. Check if swagger generates the correct type for the UI

**Comment by dhmlau** [comment]
@raymondfeng , according to [this link](https://github.com/mongodb/specifications/blob/master/source/bson-decimal128/decimal128.rst#qa), does that mean mongodb driver accepts and coerces strings to decimal 128?

**Comment by jannyHou** [comment]
The mongodb driver exports a [`Decimal128`](https://github.com/mongodb/node-mongodb-native/blob/7298c76e2a1b1b2e37a211860f35f84fad5a4c3b/docs/reference/content/tutorials/crud.md#specify-a-data-type) type that could convert a string to decimal128 number. 

I am going to do this:
- the value from request should be a string
- add a `decimal128` type check in [`toDatabase`](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L406-L428)
- import `Decimal128` from driver, do the string -> number conversion

**Comment by dhmlau** [comment]
@jannyHou , just want to make sure I understand what's your next step.  Are you going to make some code change to make the connector to support Decimal128 or to try out the behavior of the mongodb driver on this type?

**Comment by jannyHou** [comment]
@dhmlau I can add the support of Decimal128 type on connector side, but I am not sure what to do on the strong-remoting side to make sure the value passed to connector is a string.

**Comment by jannyHou** [comment]
@dhmlau I think it should be something like the data-mapping-properties:
https://loopback.io/doc/en/lb3/Model-definition-JSON-file.html#data-mapping-properties


When define the property, you specify the `type` as 'string' and `mongodb.dataType` as `decimal128`.

I updated the next step accordingly https://github.com/strongloop/loopback-connector-mongodb/issues/457#issuecomment-427165345

**Comment by jannyHou** [comment]
FYI I created a PR to support decimal 128: https://github.com/strongloop/loopback-connector-mongodb/pull/475

The type is supported from mongodb@3.4.x, and I need to upgrade my local environment to continue the PR.

**Comment by bajtos** [comment]
FYI: I would like LoopBack to eventually provide Decimal as a first-class type supported by all connectors, see https://github.com/strongloop/loopback-next/issues/1902

**Comment by SandeepVanama** [comment]
The Number Decimal (MongoDB data type Decimal128) is working for root level elements defined in model JSON file however it doesn't seem to be working for nested elements defined in model JSON file. 
Can this be fixed?

I have tested with loopback-connector-mongodb@3.9.1 using IBM IIB V10 tool.

**Comment by dhmlau** [comment]
@jannyHou , could you please take a look? Thanks.

**Comment by jannyHou** [comment]
@dhmlau I am going to support:

- Travers the `data` in the create method and do string --> decimal conversion for nested property
- Travers the `filter` in function `buildWhere` and do string --> decimal conversion for nested condition.


Started a PR for it, still in progress.
https://github.com/strongloop/loopback-connector-mongodb/pull/483

**Comment by SandeepVanama** [comment]
@Dhmlau, I do not have hands on working on loopback code, However I can test and confirm the changes working or not with the help of IBM Integration Bus V10.0.0.13 which internally uses loopback connectors to connect to Mongo DB.

**Comment by jannyHou** [comment]
Update: 
https://github.com/strongloop/loopback-connector-mongodb/pull/483 team is reviewing the PR. there is one test failure, I am fixing it.

**Comment by jannyHou** [comment]
@SandeepVanama The feature to create nested decimal property is release in 3.9.2, you can test it now.

Please read the document to learn how to define the nested property, the json file you post above doesn't define them in the correct way.

https://github.com/strongloop/loopback-connector-mongodb/blob/3.x/docs/decimal128.md

**Comment by SandeepVanama** [comment]
@jannyHou Thank you for the fix.!! 

I have updated the model JSON file as per the above link and could see the Number Decimal fields inserted as expected in both root and nested elements with loopback-connector-mongodb@3.9.2.

**Comment by dhmlau** [comment]
Closing as resolved.

**Comment by SandeepVanama** [comment]
Hello members, today while testing I have noticed an issue with NumberDecimal data type not working for the elements of an array defined under an object schema. 

Could you someone help with the issue? Please find the link below, I have opened this as new issue.

https://github.com/strongloop/loopback-connector-mongodb/issues/492

Thank you in advance!!

**Comment by ZStoneDPM** [comment]
I found this method to work best in 2019.

`const mongodb = require('mongodb');
const Decimal128 = mongodb.Decimal128;.

 const newProduct = {
    name: req.body.name,
    description: req.body.description,
    price: Decimal128.fromString(req.body.price), // store this as 128bit decimal in MongoDB
    image: req.body.image
  };
`
https://mongodb.github.io/node-mongodb-native/3.2/api/Decimal128.html
