### ISSUE TITLE
Projection fields in find and optimizedFindOrCreate must be object

### ISSUE THREAD

**Issue by mitsos1os** [strongloop/loopback-connector-mongodb#459]
# Description/Steps to reproduce

When given a fields selection object during `find` or `findOrCreate`, loopback converts it to an **array** of included fields and passes it to MongoDB library. But MongoDb library according to [find spec](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#find) and *although deprecated* [findAndModify](http://mongodb.github.io/node-mongodb-native/3.1/api/Collection.html#findAndModify) need a `projection` property that is an **object** and not an array.
However MongoDB library itself checks for provided array and converts it into an object but only in `find` methods of `collection.js` I guess since `findAndModify` is deprecated they did not bother adding this there.

In order to reproduce the problem, we need to use the  [optimizedFindOrCreate](https://github.com/strongloop/loopback-connector-mongodb/blob/ee24cd08b8ccc32711264831c71b1da628df357b/lib/mongodb.js#L1833) of Mongodb connector by setting the option `enableOptimizedFindOrCreate` to `true`  in MongoDB connector settings.
After that, issue a `findOrCreate` from a model that also includes a projection filter. The filter won't work

# Expected result

The arguments should be provided in the expected format of MongoDB driver. The current situation results in not getting any fields back, if you provide the projection document in a `findOrCreate` operation

# Additional information

linux x64 10.8.0
loopback-connector-mongodb@3.6.0

**Comment by dhmlau** [comment]
Moving it to `In Progress` as PR #460 is up.

**Comment by dhmlau** [comment]
PR #460 has landed.  Closing this issue as resolved.
@mitsos1os , thanks again for your contribution!
