### ISSUE TITLE
Composite ID component stored in database as _id

### ISSUE THREAD

**Issue by adamRenny** [strongloop/loopback-connector-mongodb#46]
When storing entries into the database using composite IDs, it appears that one of the composite IDs is used as the internal `_id` property.

This is creating an issue with having composite IDs used in a many-to-many relationship manner.

This is accomplished by building a model entity with a foreign key to two other model entities, along with a 3rd ID as its own. It appears to use the first item of the composite id definition as defined by the LDL is used for the `_id`.

**Comment by raymondfeng** [comment]
The composite id support is fairly weak at the moment. We need to enhance it across connectors.

**Comment by AlmaasAre** [comment]
+1

**Comment by Freundschaft** [comment]
is this still a problem? in my setup its not working properly

**Comment by PhanindraKumar** [comment]
+1

**Comment by jmereaux** [comment]
Any update on this topic please? Thanks

**Comment by ssh24** [comment]
Duplicate to https://github.com/strongloop/loopback-connector-mongodb/issues/358.

Currently, we do not have good support of composite id's in the mongodb connector. I have added it as a feature in our backlog.

Closing this issue. Feel free to reopen if needed.

**Comment by aravindatcts** [comment]
Is this feature implemented ?
