### ISSUE TITLE
Perfomance issues with count() since 3.6

### ISSUE THREAD

**Issue by Clement134** [strongloop/loopback-connector-mongodb#464]
# Description
There is performance issues since the version 3.6, especially with the count command.
Indeed, this version replace the count command by **countDocuments**, which one use an aggregate query. In the case of counting documents without filter this is less efficient than the old query.

Like explained in the mongo specification ([count API details](
https://github.com/mongodb/specifications/blob/master/source/crud/crud.rst#count-api-details)), perhaps we can use **estimatedDocumentCount** if there is no filter and **countDocuments** if there is a filter.
​
# Steps to reproduce
- Perform a count query with loopback-connector-mongodb@3.6
- Perform a count query with loopback-connector-mongodb@3.5
- Compare execution time ofthe two queries

**Comment by virkt25** [comment]
@Clement134 thanks for reporting this issue. Can you share the kind of performance difference you are seeing between the two connector versions?

Would you like to submit a PR for this as I see that you've already started work on it. All contributions are welcome :)

**Comment by Clement134** [comment]
Hello @virkt25,

Indeed, I am already working on a fix.
Here is a little benchmark on the following test case: count without filter on collection with 500 elements.

Version  | ops/sec
------------ | -------------
3.5.0 | 5,820
3.6.0 | 1,758
3.7.0 | 1,771
PR | 6,029

So with the solution suggested we can go back to approximately the same performances as in the version 3.5.0, without the deprecation warnings.

**Comment by 3z3qu13l** [comment]
Hello guys,
Is it solved with version 3.8.0 ?

**Comment by virkt25** [comment]
Yes, the fix was released in `3.8.0`.

cc: @Clement134 Can you confirm / close this issue.

**Comment by Clement134** [comment]
@3z3qu13l This issue is fixed with version 3.8.0.
