### ISSUE TITLE
Add mention to "authSource" in Creating a MongoDB data source

### ISSUE THREAD

**Issue by auguster** [strongloop/loopback-connector-mongodb#468]
Hello,

I used the mongo's docker image to instantiate a DB with authentification using `MONGO_INITDB_ROOT_USERNAME` and `MONGO_INITDB_ROOT_PASSWORD`. When using this, you have to provide the authentification db using `--authenticationDatabase` (in the docker mongo client). This attributes is used in mongodb connector under the name `authSource`, it took me a while to figure this out, so I think it should be mentioned in the section "Creating a MongoDB data source".

The default `authSource` (or `authenticationDatabase`) is "admin" by the way.

Source: https://docs.mongodb.com/manual/core/authentication/#authentication-methods

Best regards,

**Comment by dhmlau** [comment]
@auguster, thanks for the info.  Would you like to submit a PR?

**Comment by auguster** [comment]
> @auguster, thanks for the info. Would you like to submit a PR?

Done ;)
