### ISSUE TITLE
Embedded model binary properties not converting to Buffer when retrieving from database

### ISSUE THREAD

**Issue by ntsekouras** [strongloop/loopback-connector-mongodb#470]
# Description
When we retrieve data from the database and we have a `buffer` property in an embedded model, the value of the property is an empty Buffer.

# Steps to reproduce
1.  Define a model with an embedded model which has a property with `buffer` type.
2.  Save in the database a document from the above model.
3.  Fetch from database the inserted document and observe that the Buffer properties of the embedded models are empty Buffers.

# Link to reproduction sandbox
[embedded-buffer branch](https://github.com/ntsekouras/loopback-connector-mongodb/tree/embedded-buffer)
You have to run the regression.js file in root folder.

# Expected result
```
{ 
	myMetadata: { 
		title: 'demo title',
		innerBuffer: { 
			imageId: 'IMG_ID_INNER',
			rawImage: <Buffer ff d8 ff e0 00 10 4a 46 49>
		}
	},
	embeddedWithBuffer: {
		imageId: 'IMG_ID',
		rawImage: <Buffer ff d8 ff e0 00 10 4a 46 49>
	},
	id: 5baa2b4ba1182749d49d8d75 
}
```

# Actual result
```
{ 
	myMetadata: { 
		title: 'demo title',
		innerBuffer: { 
			imageId: 'IMG_ID_INNER',
			rawImage: <Buffer  >
		}
	},
	embeddedWithBuffer: {
		imageId: 'IMG_ID',
		rawImage: <Buffer  >
	},
	id: 5baa2b4ba1182749d49d8d75 
}
```

# Additional information
linux x64 10.4.0
loopback-connector-mongodb@3.8.0 /home/nik/Dev/loopback/loopback-connector-mongodb
├── loopback-connector@4.5.1

**Comment by jannyHou** [comment]
Closing it since PR merged. Thank you again for the contribution!
