### ISSUE TITLE
Get mongodb connector to new semver-major version

### ISSUE THREAD

**Issue by dhmlau** [strongloop/loopback-connector-mongodb#476]
Due to the 2 breaking changes introduced in PR https://github.com/strongloop/loopback-connector-mongodb/pull/462 and https://github.com/strongloop/loopback-connector-mongodb/pull/417, here is what we are going to do:
- [x] Get non-breaking changes PRs landed and release a new semver-minor / patch version (whichever applies), it includes:
   - [x] support decimal128, https://github.com/strongloop/loopback-connector-mongodb/pull/475
- [x] Land the PRs with breaking changes and release a new semver-major version
   - [x] #417 
   - [x] #462 
- [x] Update `available-connectors.json` in `loopback-workspace` to use this new major version when adding a new datasource to LB applications
   - https://github.com/strongloop/loopback-workspace/blob/master/available-connectors.json

cc @jannyHou @b-admike

**Comment by jannyHou** [comment]
closing since all tasks are done.
