### ISSUE TITLE
Update the mongodb version on node 6 windows

### ISSUE THREAD

**Issue by jannyHou** [strongloop/loopback-connector-mongodb#485]
# Description/Steps to reproduce

The node 6 windows vm is still using mongodb@3.2, which does not support a bunch of 3.4(and above) features.

Acceptance cretiria:

- [ ] Update mongodb database to 3.4 for the CI windows vm.

**Comment by dhmlau** [comment]
@jannyHou , sorry if I have forgotten the outcome of our discussion.. what needs to be done in order to update the mongodb version for windows?

**Comment by jannyHou** [comment]
@dhmlau Currently windows CI is failing. So we need to 

- Find the corresponding setup script for that windows vm in the CI repository
- Update mongodb database to 3.4

**Comment by dhmlau** [comment]
Closing as done.
