### ISSUE TITLE
Get Mongo error when port is larger then 65535

### ISSUE THREAD

**Issue by TopGunBasten** [strongloop/loopback-connector-mongodb#487]
I create new compose mongo service in IBM bluemix, the port in url is large than 65535, once I launch my application
get the error as below:
Cannot initialize connector "MongoDB": Invalid port (larger than 65535) with hostname

**Comment by jannyHou** [comment]
Hi @TopGunBasten which version of `loopback-connector-mongodb` are you using?

**Comment by TopGunBasten** [comment]
The version is 3.9.2

**Comment by TopGunBasten** [comment]
I think that's a real defect of cloud service
