### ISSUE TITLE
mongodb transaction support?

### ISSUE THREAD

**Issue by melote** [strongloop/loopback-connector-mongodb#489]
mongodb has multiple-documents transaction feature since version 4.0, how dose this project support or how do we use transaction api with loopback? thanks!

**Comment by dhmlau** [comment]
@raymondfeng, could you please help with this question?  Thanks.

**Comment by chi-tran** [comment]
Any update on this issue?

**Comment by webocs** [comment]
is anyone working on this? is it possible in the near future?

**Comment by melote** [comment]
Hello, guys, I wrote some codes to resolve this problem temporarily
```
function Transaction(Model) {
  this.Model = Model;
  this.isInTransation = false;
}

Transaction.prototype.start = function() {
  let self = this;
  let connector = self.Model.getDataSource().connector;
  if (connector.name !== 'mongodb') {
    throw new tools.createError(500, 'Only support mongodb database transaction');
  }
  else {
    if (!self.isInTransation) {
      self.session = connector.client.startSession();
      self.session.startTransaction();
      self.isInTransation = true;
    }
  }
};

Transaction.prototype.commit = async function() {
  let self = this;
  if (self.isInTransation) {
    await self.session.commitTransaction();
    self.session.endSession();
    self.isInTransation = false;
  }
};

Transaction.prototype.rollback = async function() {
  let self = this;
  if (self.isInTransation) {
    await self.session.abortTransaction();
    self.session.endSession();
    self.isInTransation = false;
  }
};

module.exports = Transaction;
```
The usage as following:
```
let transaction = new Transction(Model);
tranaction.start();
try {
// do something
await transction.commit();
// callback()
}
catch (e) {
await transction.rollback();
// callback()
}
```

**Comment by webocs** [comment]
Looks good, I've been thinking about doing something like that.  I'm not sure if trying to add this to the connector is worth it. I can't find a roadmap, so I'm not sure if this is getting ditched when LB4 comes out and LB3's LTS ends

**Comment by dhmlau** [comment]
@melote @webocs, please feel free to submit a PR for adding the transaction support.  Currently, the connectors are shared by LB3 and LB4.  

cc @raymondfeng

**Comment by chi-tran** [comment]
I understand starting the transaction. But how do I update a collection with a reference to the transaction object?

I updated a collection after the transaction started, but it is already committed.

**Comment by hoangleanhtu** [comment]
Hi,

Should we pass options [here](https://github.com/strongloop/loopback-connector-mongodb/blob/master/lib/mongodb.js#L573) to allow attach [session](https://mongodb.github.io/node-mongodb-native/3.2/api/Collection.html#insertOne):

```
  this.execute(modelName, 'insertOne', data, Object.assign({safe: true}, options), function(err, result) {
```

So in LoopBack 4, we can easily propagate transaction:

```
const session = dataSource.connector.client.startSession();
session.startTransaction();

userRepository.create(user, {session});

await session.commitTransaction();
session.endSession();
```

We also have to create collection before running operations.

**Comment by hoangleanhtu** [comment]
I implemented one as above suggestion [hoangleanhtu/loopback-connector-mongodb](https://github.com/hoangleanhtu/loopback-connector-mongodb).

@transactional decorator in this [library](https://www.npmjs.com/package/loopback4-spring#transaction-on-mongodb-replica-set) supports MongoDB as well:

```typescript
// Import here...
import {transactional} from "loopback4-spring";
 
export class UserService {
 
    constructor(
        @repository(UserRepository)
        private userRepository: UserRepository,
        @repository(CustomerRepository)
        private customerRepository: CustomerRepository
    ) {
    }
 
    @transactional()
    async create(
        user: User,
        customer: Customer,
        throwError: boolean,
        options?: Object // Options is populated by @transactional
    ): Promise<{user: User, customer: Customer}> {
 
        // Must pass options to propagate transaction
        await this.userRepository.create(user, options);
        await this.customerRepository.create(customer, options);
 
        if (throwError) {
            throw new Error('Error after create user & customer. Transaction is rollback.')
        }
 
        return {user, customer};
    }
}
```

**Comment by TranDinhKhang** [comment]
Hello, will we have an official release of this?

**Comment by melGO44** [comment]
Any update or workaround for this in loopback 4 ?

**Comment by MrShadow50** [comment]
> with a reference to

@melochale did you raise the PR for loopback3

**Comment by MrShadow50** [comment]
> Hello, guys, I wrote some codes to resolve this problem temporarily
> 
> ```
> function Transaction(Model) {
>   this.Model = Model;
>   this.isInTransation = false;
> }
> 
> Transaction.prototype.start = function() {
>   let self = this;
>   let connector = self.Model.getDataSource().connector;
>   if (connector.name !== 'mongodb') {
>     throw new tools.createError(500, 'Only support mongodb database transaction');
>   }
>   else {
>     if (!self.isInTransation) {
>       self.session = connector.client.startSession();
>       self.session.startTransaction();
>       self.isInTransation = true;
>     } 
>     return self.session;
>   }
> };
> 
> Transaction.prototype.commit = async function() {
>   let self = this;
>   if (self.isInTransation) {
>     await self.session.commitTransaction();
>     self.session.endSession();
>     self.isInTransation = false;
>   }
> };
> 
> Transaction.prototype.rollback = async function() {
>   let self = this;
>   if (self.isInTransation) {
>     await self.session.abortTransaction();
>     self.session.endSession();
>     self.isInTransation = false;
>   }
> 
> };
> 
> module.exports = Transaction;
> ```
> 
> The usage as following:
> 
> ```
> let transaction = new Transaction(Model);
> let session = tranaction.start();
> try {
>   // do something with session collection not the LOOPBACK MODEL,
>   // like session.collection('<CollectionName>').insertOne()
>   await transction.commit();
> // callback()
> }
> catch (e) {
>   await transction.rollback();
>   // callback()
> }
> ```


@melochale did you raise the PR for loopback3
