### ISSUE TITLE
"near" filter results are not of type PersistedModel

### ISSUE THREAD

**Issue by Indrego** [strongloop/loopback-connector-mongodb#490]
When calling `find` with a `near` `where` clause, the response appears to be converted to JSON with a `[__cachedrelations]` array that corresponds to any `included` relationships. However, any instance methods on the model are no longer accessible resulting in errors such as:

```
    [ 'TypeError: r.someFn is not a function',
      '    at results.map.r (~/src/proj/server/models/mymodel.js:130:22)',
      '    at Array.map (<anonymous>)',
      ... ]
```

# Description/Steps to reproduce

Using `loopback 3.24.1` with `loopback-connector-mongodb 3.9.2` (this error does not exist with the`memdb` connector), create a simple model with a GeoPoint property and add a prototype method:

```
MyModel.prototype.someFn = function() {
  return this;
};
```

Now call find with a near clause, and attempt to call `someFn` on the results:

```
let filter = {
  where: {
    geoPoint: {
      near: { lat: 1, lng: 1 }
    }
  }
}
MyModel.find(filter, function(err, results) {
  if (err) {
    return cb(err);
  } else {
    return cb(null, results.map(r => r.someFn()));
  }
});
```

# Expected result

The instance methods are accessible.

# Additional information

Here are the object properties before and after calling `new MyModel`:

`find` response:
```
[ 'geoPoint',
  'id',
  'modifiedAt',
  '__cachedRelations',
  'constructor',
  '__defineGetter__',
  '__defineSetter__',
  'hasOwnProperty',
  '__lookupGetter__',
  '__lookupSetter__',
  'isPrototypeOf',
  'propertyIsEnumerable',
  'toString',
  'valueOf',
  '__proto__',
  'toLocaleString' ]
```
Proper model:
```
[ '__cachedRelations',
  '__data',
  '__dataSource',
  '__strict',
  '__persisted',
  '__unknownProperties',
  'constructor',
  'geoPoint',
  '$geoPoint',
  'id',
  '$id',
  'someFn',
  'save',
  'isNewRecord',
  'getConnector',
  'destroy',
  'delete',
  'remove',
  'setAttribute',
  'updateAttribute',
  'setAttributes',
  'unsetAttribute',
  'replaceAttributes',
  'patchAttributes',
  'updateAttributes',
  'reload',
  '_scopeMeta',
  'createdAt',
  '$createdAt',
  'modifiedAt',
  '$modifiedAt',
  '__findById__somerelation',
  '__destroyById__somerelation',
  '__updateById__somerelation',
  '__exists__somerelation',
  '__link__somerelation',
  '__unlink__somerelation',
  'somerelation',
  '__get__somerelation',
  '__create__somerelation',
  '__delete__somerelation',
  '__update__somerelation',
  '__findOne__somerelation',
  '__count__somerelation',
  ... ]
```

I attempted to work around this by reinstantiating the model via `r = new MyModel(r)`, but noticed that nested relations are still broken. Hopefully this may provide some insight into the proper fix.

**Comment by b-admike** [comment]
@Indrego Thank you for the detailed issue description. We've fixed this recently in juggler. Can you try updating your dependencies and use the new release of juggler (i.e. `loopback-datasource-juggler@4.5.4`)?
