### ISSUE TITLE
MongoDB aggregation on Loopback

### ISSUE THREAD

**Issue by techaks** [strongloop/loopback-connector-mongodb#494]

**Comment by dhmlau** [comment]
@techaks , could you please provide some information on the question / issue that you have? Thanks.

**Comment by techaks** [comment]
I have not found any source.. how to use mongodb aggregate in loopback 4

**Comment by dhmlau** [comment]
@techaks , could you please take a look at https://github.com/strongloop/loopback-next/issues/2021?  There was some discussion on mongodb aggregate and someone had a solution that seems to be working.
