### ISSUE TITLE
How to escape special characters in Passwords to connect to MongoDB

### ISSUE THREAD

**Issue by arukris-cdw** [strongloop/loopback-connector-mongodb#499]
Hi Team, 

I am trying to connect to mongodb using loopback-connector-mongodb. When I start my loopback application, it throws the below error. My password will have characters like !$@ etc.. 

I tried to encode this characters like using %40 for @, %21 for ! and %24 for $. If my password has only @ character, the application is able to recognize %40 and start, but it throws the below error if my passwords has $ or ! . One of my service account has all these characters and I am having difficulties to start the application. Can you please let me know how to fix this problem. 

**Datasource:** 
{
    "quotesDS": {
    "host": "",
    "port": "",
    "url": "mongodb://<user>%40CORP.CDW.COM:<pwd>@host1,host2/QuotesDB?w=majority&wtimeoutMS=5000&replicaSet=RSDEV01&readPreference=primary&ssl=true&slaveOk=true&gssapiServiceName=mongodb&authMechanism=GSSAPI",
	"option": { "useNewUrlParser": true },
    "database": "QuotesDB",
    "name": "quotesDS",
    "connector": "mongodb",
    "replicaSet": "RSDEV01",
    "ssl": true
  }
}

**Error:**
C:\Projects\mongodb\mongocloud>node .
Connection fails: Error: Password contains an illegal unescaped character
It will be retried for the next request.
Connection fails: Error: Password contains an illegal unescaped character
It will be retried for the next request.
C:\Projects\mongodb\mongocloud\node_modules\loopback\lib\application.js:246
    throw err;
    ^

Error: **Cannot create data source "quotesDS": Cannot initialize connector "mongodb": Password contains an illegal unescaped character**
    at parseConnectionString (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\url_parser.js:298:13)
    at parseHandler (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\url_parser.js:129:14)
    at module.exports (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\url_parser.js:25:12)
    at deprecated (internal/util.js:47:15)
    at connect (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\operations\mongo_client_ops.js:188:3)
    at connectOp (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\operations\mongo_client_ops.js:292:3)
    at executeOperation (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\utils.js:420:24)
    at MongoClient.connect (C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\mongo_client.js:168:10)
    at MongoDB.connect (C:\Projects\mongodb\mongocloud\node_modules\loopback-connector-mongodb\lib\mongodb.js:294:62)
    at Object.initializeDataSource [as initialize] (C:\Projects\mongodb\mongocloud\node_modules\loopback-connector-mongodb\lib\mongodb.js:111:28)
    at DataSource.setup (C:\Projects\mongodb\mongocloud\node_modules\loopback-datasource-juggler\lib\datasource.js:352:19)
    at new DataSource (C:\Projects\mongodb\mongocloud\node_modules\loopback-datasource-juggler\lib\datasource.js:121:8)
    at Registry.createDataSource (C:\Projects\mongodb\mongocloud\node_modules\loopback\lib\registry.js:355:12)
    at dataSourcesFromConfig (C:\Projects\mongodb\mongocloud\node_modules\loopback\lib\application.js:440:19)
    at Function.app.dataSource (C:\Projects\mongodb\mongocloud\node_modules\loopback\lib\application.js:235:14)
    at C:\Projects\mongodb\mongocloud\node_modules\loopback-boot\lib\executor.js:191:9

**Comment by dhmlau** [comment]
Have you tried adding the option` useNewUrlParser: true` as suggested in this github issue
https://github.com/lmammino/mongo-uri-builder/issues/2#issuecomment-461749613?

**Comment by arukris-cdw** [comment]
@dhmlau , I already tried this option. Below is my datasource configuration and it doesn't seem to work. 
Please let me know if my configuration is correct?. 

Datasource:
{
"quotesDS": {
"host": "",
"port": "",
"url": "mongodb://%40CORP.CDW.COM:@Host1,host2/QuotesDB?w=majority&wtimeoutMS=5000&replicaSet=RSDEV01&readPreference=primary&ssl=true&slaveOk=true&gssapiServiceName=mongodb&authMechanism=GSSAPI",
**"option": { "useNewUrlParser": true },**
"database": "QuotesDB",
"name": "quotesDS",
"connector": "mongodb",
"replicaSet": "RSDEV01",
"ssl": true
}
}

**Comment by arukris-cdw** [comment]
@dhmlau , can you please review my datasource configuration posted on my last update and let me know your inputs.

**Comment by raymondfeng** [comment]
Is your password part of the `url`?

**Comment by arukris-cdw** [comment]
yes, my password is part of the url. it will be like below. 

Datasource:
{
"quotesDS": {
"host": "",
"port": "",
"url": "mongodb://%40CORP.CDW.COM:**pwd%21%24**@Host1,host2/QuotesDB?w=majority&wtimeoutMS=5000&replicaSet=RSDEV01&readPreference=primary&ssl=true&slaveOk=true&gssapiServiceName=mongodb&authMechanism=GSSAPI",
"option": { "useNewUrlParser": true },
"database": "QuotesDB",
"name": "quotesDS",
"connector": "mongodb",
"replicaSet": "RSDEV01",
"ssl": true
}
}

**Comment by dhmlau** [comment]
According to https://github.com/strongloop/loopback-connector-mongodb/issues/442#issuecomment-418320402, there's no need for `options`, i.e. 
```
"mongodb": {
      "url": "myDBurl",
      "name": "mongodb",
      "connector": "loopback-connector-mongodb",
      "useNewUrlParser":"true"
    }
```

You're right that when the password just contains `@`, it seems to be working fine.  I'm using a modified version of [this script](https://github.com/strongloop/loopback-connector-mongodb/blob/master/setup.sh) to set up my mongodb docker container.  One thing that I did differently from the example above is that I have `  "authSource": "admin",`. 

i.e. 
```
  "url": "mongodb://admin:%40abc@localhost:27017/testdb",
  "authSource": "admin",
```

When changing the password to `@abc!$`, it doesn't work with the following (with or without the `useNewUrlParser` flag):
```
  "url": "mongodb://admin:%40abc%21%24@localhost:27017/testdb",
  "authSource": "admin",
  "useNewUrlParser":"true"
```

I have my doubt whether I'm setting the password for the database correctly (somehow my Kitematic doesn't quite work).  I'd appreciate if you could give it a try on setting the `useNewUrlParser` the same way as the first snippet and let us know whether it works.  I can do some more digging if it doesn't work.  Thanks!

**Comment by arukris-cdw** [comment]
@dhmlau , Please find my observation below. 

when I used "useNewUrlParser":true in the DS configuration as you mentioned, the error was 

C:\Projects\mongodb\mongocloud\node_modules\mongodb\lib\operations\mongo_client_ops.js:474
      throw err;
      ^
MongoError: authentication fail

**Note:** I made sure the pwd is uriencoded and they are the correct ones. 
======================================
and if I remove the "useNewUrlParser":true from the DS  configuration, i get the usual error as before. 

Error: Cannot create data source "quotesDS": Cannot initialize connector "mongodb": Password contains an illegal unescaped character

thanks
Arun S.

**Comment by hacksparrow** [comment]
@arukris-cdw  You should encode the whole username or password, not just the special characters in them using percent-encoding - https://tools.ietf.org/html/rfc3986#section-2.1. 

Eg: `a!$@xyz` would become `%61%21%24%40%78%79%7A`.

Here is a function to generate percent encoded string:

```js
function percentEncode(string) {
  let encoded = '';
  string.split('').forEach(function(char) {
    encoded += '%' + char.charCodeAt(0).toString(16).toUpperCase();
  });
  return encoded;
}
```

**Comment by vitaly-t** [comment]
Without having to encode anything, using the generic [connection-string]:

```js
const ConnectionString = require('connection-string');

// connection string without user/password:
const connection = 'mongodb://Host1,host2/QuotesDB?w=majority&wtimeoutMS=5000&replicaSet=RSDEV01&readPreference=primary&ssl=true&slaveOk=true&gssapiServiceName=mongodb&authMechanism=GSSAPI';

// creating connection string, with defaults:
const cs = new ConnectionString(connection, {
    user: '@CORP.CDW.COM',
    password: 'pwd!$'
});

console.log(cs.toString());
// mongodb://%40CORP.CDW.COM:pwd!$@Host1,host2/QuotesDB?w=majority&wtimeoutMS=5000&replicaSet=RSDEV01&readPreference=primary&ssl=true&slaveOk=true&gssapiServiceName=mongodb&authMechanism=GSSAPI
```

[connection-string]:https://github.com/vitaly-t/connection-string

**Comment by dhmlau** [comment]
Closing as done. See PR #529
