### ISSUE TITLE
Remove unnecessary downstream builds from mongodb connector 

### ISSUE THREAD

**Issue by b-admike** [strongloop/loopback-connector-mongodb#509]
# Description/Steps to reproduce
Related to #503 

Right now in mongodb connector, we have some downstream builds that run and fail, but should not affect the build status for patches on the connector. We need to remove those downstream builds. On the same note, mongodb build on node 6.x and windows needs to have its mongodb version updated.

# Acceptance Criteria
- [x] Remove the following downstream builds from monogdb connector:
```
[cis-jenkins] downstream: bluemix-metering@develop Failed! (97bb9b3)
Details
[cis-jenkins] downstream: bluemix-service-broker@develop Failed! (97bb9b3)
Details
[cis-jenkins] downstream: plan-manager@develop Failed! (97bb9b3)
```
- [x] Update the mongodb version on Windows machine (using node 6.x) to the latest version

**Comment by dhmlau** [comment]
See example: https://github.com/strongloop/loopback-datasource-juggler/blob/master/package.json#L64-L70

**Comment by dhmlau** [comment]
> Remove the following downstream builds from monogdb connector

I've tested it with a test PR and verified that the downstreams were removed. 

> Update the mongodb version on Windows machine (using node 6.x) to the latest version

Since we've dropped the tests for Node.js 6, this is no longer needed. 

Closing this task as done.
