### ISSUE TITLE
include.test.js not imported (commented out) - fails

### ISSUE THREAD

**Issue by fabien** [strongloop/loopback-connector-mongodb#51]
For some reason, the include.test.js is commented out, and it turns out that some of these tests fail.

Also, common.batch.js doesn't run all tests, manipulation.test.js is missing for example (but will run fine when added).

**Comment by dhmlau** [comment]
@fabien, seems like `include.test.js` is not commented out.  Closing this..  Feel free to reopen this issue if you find this problem still exists.  Thanks.
