### ISSUE TITLE
Filter not working for string field

### ISSUE THREAD

**Issue by anjorinjnr** [strongloop/loopback-connector-mongodb#512]
I have a class that looks like this.
```
@model()
class SomeClass extends Entity {

   @property({
    type: "string"
  })
  title: string;

  @property({
    type: "string"
  })
  createdBy?: string;
}
```
I am using mongodb as the database.

`filter[where][title]=<value>` returns data

`filter[where][createdBy]=<value>` does not returns data 

Not sure what's going on with this particular field. Any idea?

**Comment by anjorinjnr** [comment]
Turns out if the value in the column is an id e.g '5cc67a80e46e13a0d6a87a80' it doesn't work but another value it works. Doesn't make any else. Who knows what's happening here?

**Comment by anjorinjnr** [comment]
Figured it out. It's coercing string with object format directly to objectid. It can be turned off by turning 
```
settings: {
    "strictObjectIDCoercion": true
  }
```

**Comment by burin-sapsiri** [comment]
Thanks.
It's helped me.
