### ISSUE TITLE
String should saved as objectId

### ISSUE THREAD

**Issue by imonildoshi** [strongloop/loopback-connector-mongodb#515]
While finding a String which is actually an objectId, loopback-connector-mongodb converts it to ObjectId and then finds, which is perfect.

But while inserting, if a string is a foreign key and not an Id, it is not converted to ObjectId

What do you recommend? should we convert all the properties of regex /^[0-9a-fA-F]{24}$/ to objectId and then save

**Comment by dhmlau** [comment]
@imonildoshi , saw your same question posted in https://github.com/strongloop/loopback-next/issues/2085#issuecomment-489632132.  Should we use that thread to continue to discussion? Thanks.

**Comment by imonildoshi** [comment]
Yes sure, let's do that

**Comment by dhmlau** [comment]
ok. let me close this issue then. Thanks.
