### ISSUE TITLE
CamelCase property names using Model json

### ISSUE THREAD

**Issue by arukris-cdw** [strongloop/loopback-connector-mongodb#520]
hi Team,

We have a requirement to camelCase all element names in json before writing to mongodb. Is there any property in datasources.json or modelconfig.json file that I can use to automatically apply camelcasing to all element names (using loopback connector mongodb) . 

This requirement came all of a sudden and I won't be able to revisit all our mappings again to change the element names to camelcase(around 1600 elements) , hence looking for any automatic settings available in loopback. 

eg:
{"MultipleShipToFlag": "N"} should be written to MongoDB as {"multipleShipToFlag" : "N"}

thanks
Arun S.

**Comment by arukris-cdw** [comment]
hi Team, 

Can anyone provide some guidance for my request. 

thanks
Arun S.

**Comment by raymondfeng** [comment]
Please check out https://loopback.io/doc/en/lb3/Connector-hooks.html#mongodb-connector.

**Comment by bajtos** [comment]
> We have a requirement to camelCase all element names in json before writing to mongodb

What is supposed to happen when you read the data from MongoDB and send it to HTTP clients? Do you want to convert them from `multipleShipToFlag` back to `MultipleShipToFlag`, or would you like to preserve the camel-case property names?

Also how are these properties defined in your Model JSON files? Conceptually, do you want to see camel-case (`multipleShipToFlag`) or PascalCase (`MultipleShipToFlag`) names when dealing with models in JavaScript?

Another thing to consider is validation. If your model definitions use PascalCase property names but are sending camelCase names over the wire, then these camelCase-named properties will be treated as free-form (additional) properties by LoopBack and no validation will be performed. E.g. we won't reject requests setting a numeric property "age" to a string value "just born".

Assuming that you want to preserve your REST API and keep using PascalCase there, but store data with camelCase-named properties, my recommendation would be to leverage [Operation hooks](https://loopback.io/doc/en/lb3/Operation-hooks.html):
- use `persist` hook to convert from PascalCase to camelCase just before data is sent to the database
- use `loaded` hook to convert from camelCase to PascalCase data loaded from the database

**Comment by arukris-cdw** [comment]
@bajtos , thanks for your feedback. 

will try the option to use persist hook to convert from PascalCase to camelCase and get back to you in case of any further queries.
