### ISSUE TITLE
Connected AWS DocumentDB via SSL, but returns EMPTY array

### ISSUE THREAD

**Issue by alidavid0418** [strongloop/loopback-connector-mongodb#538]
I'm building an app with `loopback 3.22.2` and `loopback-connector-mongodb 4.2.0`.
The current working mongodb version is **4.0.4**.
BTW, newly migrated AWS DocumentDB always returns nothing but empty array although the DB has been correctly migrated(I've confirmed that through mongod shell).
I understand DocumentDB is based on mongodb **3.6** schema, but is that a main reason for the current issue?
Please any help!
Thanks in advance.

**Comment by jsw** [comment]
@alidavid0418 Did you get it to work? I'm trying to determine if this connector is expected to work with DocumentDB.

**Comment by rporta** [comment]
Yes, but in my case the error was that the `useUnifiedTopology` option was
not available in version" loopback-connector-mongodb # ^ 4.2.0 ".
I solved it by adding this dependency in package.json

"loopback-connector-mongodb: git + https: //
github.com/strongloop/loopback-connector-mongodb.git#v5.1.0",

Hope you can solve it
