### ISSUE TITLE
Writing to MongoDB failing after mongodb dependency being upgraded

### ISSUE THREAD

**Issue by jbedzinskas** [strongloop/loopback-connector-mongodb#543]
After our custom service redeploy we started getting these errors while writing to MongoDB instance:
“Transaction numbers are only allowed on storage engines that support document-level locking” 

It was caused by mongodb dependency being automatically upgraded by npm to v3.3.0, which enables `retryWrites=true` by default. This leads loopback-mongodb-connector not working with Mongo DB 3.6 instances.

Workarounds:
- Add `retryWrites=false` flag manually to MongoDB connection string
- Lock mongodb dependency on 3.2.7 or older.
- Upgrade to MongoDB 4

darwin x64 12.6.0

**Comment by dhmlau** [comment]
@hacksparrow, I was looking at this briefly. The error @jbedzinskas  mentioned (not in this issue) is `Transaction numbers are only allowed on storage engines that support document-level locking`.  It seems to be a mongodb error. Found a few similar threads: 
https://jira.mongodb.org/browse/RUBY-1859
https://jira.mongodb.org/browse/RUBY-1853

@jbedzinskas suggested locking the `mongodb` dependency would fix the problem.  Could you please take a look what could be the best solution? Thanks!

**Comment by hacksparrow** [comment]
I am not in favor of locking the version `mongodb` dependency, especially considering MongoDB `4.0.x` has been out for a while now.

What we can do instead is introduce a new datasource property `retryWrites` which defaults to `true`. Users who want or need it to be `false` can simply set it to `false`. 

Thoughts @raymondfeng @bajtos?
