### ISSUE TITLE
Default sort order may impact performance on some queries

### ISSUE THREAD

**Issue by mihail-stanchev** [strongloop/loopback-connector-mongodb#55]
If a sort order is not specified a default one by _id is used. This may impact the performance of some queries where a sort is neither needed nor specified upfront. For example, using model.findOne results in the MongoDB connector calling db.collection.find(query).sort({_id:1}).limit(1)
If the sort part is skipped the result is returned almost immediately using the appropriate indices. However, having the sort in there causes the entire query to slow down. In my case there is only one record matching the given criteria and the sort is not needed.

Would you consider making the sort order explicit?

**Comment by raymondfeng** [comment]
Maybe we can make it controllable via a model/method level configuration property.

**Comment by mazesoul** [comment]
+1

**Comment by Ijmir** [comment]
+1

**Comment by thaiat** [comment]
+1

**Comment by SynerG** [comment]
+1 Please, fix this. Even if you create a specific index for your query, MongoDb cannot use the index because Loopback requests to order by `_id`, and the field is not included in the index. MongoDB docs explain it: https://docs.mongodb.org/manual/core/index-intersection/#index-intersection-and-sort

**Comment by sebastianhaas** [comment]
+1

**Comment by simonecogno** [comment]
+1

**Comment by 0101adm** [comment]
+1

**Comment by bidos** [comment]
+1

**Comment by sebastianhaas** [comment]
This is still relevant to me!

**Comment by sebastianhaas** [comment]
Don't!

**Comment by HugoPoi** [comment]
I loose one day because of this default sort operation on "_id". THE DEFAULT BEHAVIOR FOR MONGODB MUST BE NO SORT when no sort operation is specify !
Please merge  #177 !

**Comment by HugoPoi** [comment]
UP This issue is still relevant for 1.18.x and 3.x.

See 
https://github.com/strongloop/loopback-connector-mongodb/blob/c0c75f915ea54079e66c819e28036b7c7bf6f7d6/lib/mongodb.js#L729-L734
And
https://github.com/strongloop/loopback-connector-mongodb/blob/0041f217019c84983ba3eec39c0ac993807289fc/lib/mongodb.js#L849-L854

Can we re-open and merge https://github.com/strongloop/loopback-connector-mongodb/pull/177 ?

**Comment by sebastianhaas** [comment]
Don't

**Comment by dhmlau** [comment]
@strongloop/lb-next-dev , seems like this is a popular feature request, and a related PR ready (#177).  Want to initiate the discussion on how we're going to tackle it?

**Comment by jannyHou** [comment]
I think we can continue the discussion based on @raymondfeng 's suggestion in #177 
```
Two thoughts around the proposal:
    - Should we provide a configuration option at app/model level to control if order by id should be enforced?
    - We should support the same option for all connectors.
```
A global flag(app/model level) sounds good to me, considering one app could have multiple datasources/models, we can start with enabling the model level config.
And we can change [this line in #177 ](https://github.com/strongloop/loopback-connector-mongodb/pull/177/files#diff-567d120f151f51afa9605ebcf0f20106R685) to read the flag from `modelDefinition.settings`

Anyone interested to create a PR to continue the work in #177 ? I can help review and land it.

**Comment by dhmlau** [comment]
In evaluation whether we can work on it for July milestone

**Comment by HugoPoi** [comment]
@dhmlau @jannyHou I open PR #437 based on your suggestion and inspired by #177

**Comment by jannyHou** [comment]
Should be fixed by https://github.com/strongloop/loopback-connector-mongodb/pull/437, i am closing this issue. 
Feel free to reopen it if you still have the problem.
