### ISSUE TITLE
Cannot install latest version 5.2.0

### ISSUE THREAD

**Issue by nisajthani** [strongloop/loopback-connector-mongodb#554]
Greetings. I tried to update the loopback-connector-mongodb from ^4.2.0 to 5.2.0 with the following command
`npm install loopback-connector-mongodb --save`

The version 4.2.0 is installed instead. Is there a reason for this? I would like to know if it is better to stick to 4.2.0 since that is what npm is giving me.

**Comment by raymondfeng** [comment]
You need to run `npm install loopback-connector-mongodb@5.2.0 --save` as `5.2.0` is new major version over `4.2.0`.
