### ISSUE TITLE
TypeError: Cannot read property 'dbName' of null

### ISSUE THREAD

**Issue by ianhorrocks11** [strongloop/loopback-connector-mongodb#556]
TypeError: Cannot read property 'dbName' of null
    at /home/ianhorrocks/Escritorio/Proyecto/TFG/apiTfg/node_modules/loopback-connector-mongodb/lib/mongodb.js:310:17
    at parseHandler (/home/ianhorrocks/Escritorio/Proyecto/TFG/apiTfg/node_modules/mongodb/lib/url_parser.js:135:16)
    at QueryReqWrap.callback (/home/ianhorrocks/Escritorio/Proyecto/TFG/apiTfg/node_modules/mongodb/lib/url_parser.js:114:7)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:198:10)

- https://stackoverflow.com/tags/loopbackjs
- https://groups.google.com/forum/#!forum/loopbackjs
- https://gitter.im/strongloop/loopback

**Immediate support**

- https://strongloop.com/api-connect-faqs/
- https://strongloop.com/node-js/subscription-plans/

-->
I have this : 

{
  "db": {
    "host": "apitfg-bh6jr.mongodb.net",
    "port": 0,
    "url": "mongodb+srv://newUser:<password>@apitfg-bh6jr.mongodb.net/test?retryWrites=true&w=majority",
    "database": "apitfg",
    "password": "tfg123",
    "name": "db",
    "user": "newUser",
    "useNewUrlParser": true,
    "connector": "mongodb"
  }
}

**Comment by peeyush-es** [comment]
Don't put special character in your password, if you are using old mongodb
