### ISSUE TITLE
connect mongodb twice

### ISSUE THREAD

**Issue by hanyuzhou2006** [strongloop/loopback-connector-mongodb#558]
## Steps to reproduce

with loopback-datasource-juggle
```js
const db = new DataSource(...);
db.on('connected',()=>{console.log('connected')})
const testmodel = db.createModel(...)
testmodel.find();
```

## Current Behavior

connected twice
## Expected Behavior

connected  once
## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@hacksparrow, could you please take a look? Thanks.

**Comment by hacksparrow** [comment]
@hanyuzhou2006 can you share a basic app which reproduces this behavior?

**Comment by hanyuzhou2006** [comment]
> @hanyuzhou2006 can you share a basic app which reproduces this behavior?

https://github.com/hanyuzhou2006/test-loopback-connector-mongodb

![image](https://user-images.githubusercontent.com/9476099/71702522-e123ec80-2e0a-11ea-8cb8-043fa844e888.png)

**Comment by hacksparrow** [comment]
Thanks @hanyuzhou2006. `TestModel.find()` is causing the second trigger, investigating.

**Comment by hacksparrow** [comment]
In the meantime, you can do:

```js
mongodbSource.once('connected', () => {
  console.log('connected');
});
```

**Comment by hacksparrow** [comment]
Ok, so the second event is caused by `TestModel.find()` triggering a connect function while a connection process is already happening.

In real-world uses cases model method are triggered by events, so you won't face this problem. Even  setting a delay of 100 ms to `TestModel.find()` prevents the second event.

```js
setTimeout(function() {
  TestModel.find();
}, 100);
```
Having said that, use `mongodbSource.once('connected' ...` instead of `mongodbSource.on('connected' ...`

**Comment by hanyuzhou2006** [comment]
@hacksparrow 
I think the above usage is more common in object-oriented programming. As a DataSource object, it itself needs to maintain the state of its instance, rather than relying on external calls.
I think the implementation of loopback connectors may follow such rules.
Simple, fast and less usage.
