### ISSUE TITLE
with GeoPoint crash

### ISSUE THREAD

**Issue by hanyuzhou2006** [strongloop/loopback-connector-mongodb#559]
## Steps to reproduce

when i use GeoPoint type and the database exsists an incorrect  data , it will make a crash.

## Current Behavior

```js
{
"_id":"test1",
"position": {
  "coordinates": [
            121.0111427307129,
            30.99629874930975
        ],
    "type": "Point"
}
}
```
this data is ok
```
{
"_id":"test2",
"position": {
  "test":1
}
}
```
but when the test2 data in mongodb, i will get a crash

## Expected Behavior

get a data with original object, but not crash

Or get an error

## Related Issues

_See [Reporting Issues](http://loopback.io/doc/en/contrib/Reporting-issues.html) for more tips on writing good issues_

**Comment by dhmlau** [comment]
@hanyuzhou2006, could you please provide a sample application that can reproduce the problem? Also, could you please provide the LoopBack and `loopback-connector-mongodb` versions? Simply run `npm ls --depth=0` would do. Thanks!

**Comment by dhmlau** [comment]
@hacksparrow, when there's more info, could you please help with this? Thanks.

**Comment by hanyuzhou2006** [comment]
> @hanyuzhou2006, could you please provide a sample application that can reproduce the problem? Also, could you please provide the LoopBack and `loopback-connector-mongodb` versions? Simply run `npm ls --depth=0` would do. Thanks!

i only use loopback-connector-mongodb@^4.2.0 and loopback-datasource-juggler@^4.7.0。In correct usage(the mongodb datas is correct) it worked well。But when datas was unexpected, it crashed.

**Comment by hacksparrow** [comment]
@hanyuzhou2006 please share a minimal app reproducing this bug.
