### ISSUE TITLE
How can I use $inc

### ISSUE THREAD

**Issue by alexandrusavin** [strongloop/loopback-connector-mongodb#56]
If I try to use $inc in the data field of update method I get "The dollar ($) prefixed field '$inc' in '$inc' is not valid for storage.". When I dug deeper I found that the only operation that update method is supporting is "$set" (see mongodb.js:643:43). Am I wrong? Is there no way of incrementing fields using this connector?

**Comment by alexandrusavin** [comment]
@cpentra1 @jbbr this feature is in master now. To use you have to configure your ața source to enable extended operators (extendedOperators: true).

**Comment by arielmcm** [comment]
Enabling (allowExtendedOperators: true) worked for me.

**Comment by amitshahc** [comment]
> Enabling (allowExtendedOperators: true) worked for me.

This solved my issue in loopback 3.
