### ISSUE TITLE
npm test results in make eror ( even after ensuring mocha is installed.)

### ISSUE THREAD

**Issue by sreeroman** [strongloop/loopback-connector-mongodb#57]
Got the latest build and ran npm test. I am seeing some make errors posted below.

Build error 

./node_modules/.bin/mocha -G --timeout 10000 test/*.test.js
/bin/sh: ./node_modules/.bin/mocha: No such file or directory
make: *** [test] Error 127
npm ERR! Test failed.  See above for more details.

**Comment by raymondfeng** [comment]
Have you run `npm install`?

**Comment by raymondfeng** [comment]
I cannot reproduce this problem. Please reopen if you still see the issue.
