### ISSUE TITLE
$geowithin filter support

### ISSUE THREAD

**Issue by Jonibigoud** [strongloop/loopback-connector-mongodb#579]
## Suggestion

Could mongodb $geowithin filter  be implemented?

## Use Cases

$geowithin helps find points into polygons or multipolygons:
[https://docs.mongodb.com/manual/reference/operator/query/geoWithin/#op._S_geoWithin](url)

## Example

const polygon = { type:"Feature", geometry: { type: "Polygon", coordinates:[ some coordinates] } }
const locations = MyModel.find({geometry: {geoWithin: { $geometry: polygon.geometry }}}) 
## Acceptance criteria

TBD - will be filled by the team.

**Comment by Jonibigoud** [comment]
Could someone tell me how i could use the $geowithin filter in my API?

**Comment by mrbatista** [comment]
@Jonibigoud 

```js 
const filter = {
  where: {
    geometry: {
      geoWithin: {
        $geometry: [
          [0, 0],
          [100, 100],
       ],
      },
    },
  },
};`
