### ISSUE TITLE
Support for Timestamps Model option 

### ISSUE THREAD

**Issue by FMGordillo** [strongloop/loopback-connector-mongodb#603]
## Suggestion

A similar feature to [the mongoose one](https://mongoosejs.com/docs/guide.html#timestamps)

## Use Cases

Avoid manual manipulation of `createdAt` and `updatedAt`

## Examples

```
@model({timestamps: true})
export class Category extends Entity {
// ...
}
```

**Comment by dhmlau** [comment]
@raymondfeng @bajtos, do you think this would be better to be implemented as an extension? Thanks.

**Comment by bajtos** [comment]
Closing as a duplicate of https://github.com/strongloop/loopback-next/issues/1857: _Support auto-updated model properties "createdAt" and "updateAt"_
