### ISSUE TITLE
Custom collection name for model and base models

### ISSUE THREAD

**Issue by EugeneBabushkin** [strongloop/loopback-connector-mongodb#64]
Hello,

Unfortunately, I could not find a single example of how change collection name for models and base models (for example, AccessTokens).

Can you resolve my problem? Thanks.

**Comment by dinhanhhuy** [comment]
`" mongodb": {      
        "collection": "PostCollection"      
      },  
`
this is `dataSource` name or `connector` name? Currently, above link don't cotain any text `collection`
