### ISSUE TITLE
$setOnInsert for default model values

### ISSUE THREAD

**Issue by PuKoren** [strongloop/loopback-connector-mongodb#69]
When using default values in a model and creating/upserting a model instance without specifying these values, the mongodb connector stores the document as-is, and does not fetch the default values to use it with $setOnInsert.
http://docs.mongodb.org/manual/reference/operator/update/setOnInsert/#up._S_setOnInsert

Exemple:
My model defined as:
```json
{
  "name": "Device",
  "plural": "Devices",
  "base": "PersistedModel",
  "properties": {
    "deviceId": {
      "type": "string",
      "id": true,
      "required": true
    },
    "culture": {
      "type": "string"
    },
    "phoneNumber": {
      "type": "string"
    },
    "imei": {
      "type": "string"
    },
    "createdAt": {
      "type": "date"
    },
    "updatedAt": {
      "type": "date"
    }
  }
}
```
And using default value for createdAt with:  
```javascript
Device.definition.rawProperties.createdAt.default =
Device.definition.properties.createdAt.default = function() {
    return new Date();
};
```

And creating a model instance with:
```javascript
this.upsert({
			'deviceId': 'PHONE_UNIQUE_ID',
			'culture': 'EN_UK',
			'imei': 'UNIQUE_IMEI',
			'phoneNumber': '+44940395039',
			'updatedAt': new Date()
		});
```

The resulting data in the mongodb database is:
```json
{
    "_id": "PHONE_UNIQUE_ID",
    "culture": "EN_UK",
    "phoneNumber": "+44940395039",
    "imei": "UNIQUE_IMEI",
    "updatedAt": {
        "$date": "2014-11-26T13:53:43.783Z"
    }
}
```

As you can see, the createdAt value is missing. If I setup the memory connector, createdAt is here as expected.

**Comment by raymondfeng** [comment]
I think the issue should be generalized to `Model.create(data)` and `Model.upsert(data)` for all DBs. The question is that whether the `data` argument should be extended with default values for properties that are not present in the `data` object. The behavior is debatable. 

Can you open a new issue in https://github.com/strongloop/loopback-datasource-juggler? I'm closing this one as `$setOnInsert` is just the implementation detail. We need to agree on the api behavior first.
