### ISSUE TITLE
How to save file to gridfs?

### ISSUE THREAD

**Issue by makersu** [strongloop/loopback-connector-mongodb#73]
How to save file to gridfs as below for example?
Thank you very much.
```
def save(inputStream, contentType, originalFilename) {
		def inputFile = gridFS.createFile(inputStream)
		String extension = originalFilename.split('\\.')[-1]
		String gridFSFilename=inputFile.id.toString() + '.' + extension
		inputFile.setFilename(gridFSFilename)
		inputFile.save()
		return inputFile.filename
	}
```

**Comment by makersu** [comment]
When I try to run the sample,it returned:
```
TypeError: Cannot read property 'GridStore' of undefined 
```
So, I npm install mongodb and  var GridStore = require('mongodb').GridStore,then I got:
```
TypeError: Cannot read property 'w' of undefined
```
Any help will be appreciated.Thanks.

**Comment by makersu** [comment]
My solution:
```
var db = app.datasources.db.connector.db;
db.safe = {w: 1};

var gridStore = new GridStore(db, null, "w");
  gridStore.open(function(err, gridStore) {
  ...
...
```

**Comment by paulJordaan** [comment]
When trying this example with:

`var db = app.datasources.db.connector.db;`

It returns with with db as undefined. 

Any suggestions?

**Comment by superkhau** [comment]
Closing as resolved. @paulJordaan @makersu does `var db = app.myDataSource.connector.db;` work? Ping and I will reopen this issue if you still more information.
