### ISSUE TITLE
RangeError when querying using 'inq' and 'nin' operators using angular sdk

### ISSUE THREAD

**Issue by roomond** [strongloop/loopback-connector-mongodb#75]
Using a mongodb datasource, mongodb connector and angular sdk, queries using 'inq' and 'nin' fail with a RangeError message. Queries without these filters work fine. An example query:

<code>MyModel.find({ filter: { where: { myField: { inq: ['val1', 'val2', 'val3']}}}}).$promise</code> 

Fails with the error message:

<code>{"error": {"name":"RangeError", "status":500,"message":"attempt to write outside buffer bounds", "stack":"RangeError: attempt to write outside buffer bounds\n at Buffer.write (buffer.js:371:11)\n at packElement (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:877:60)\n at serializeObject (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:377:15)\n at Function.serializeWithBufferAndIndex (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:343:10)\n at BSON.serializeWithBufferAndIndex (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:1556:15)\n at QueryCommand.toBinary (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/commands/query_command.js:236:35)\n at Connection.write (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/connection/connection.js:265:37)\n at __executeQueryCommand (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/db.js:1721:16)\n at Db._executeQueryCommand (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/db.js:1871:7)\n at Cursor.nextObject (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:749:13)\n at Cursor.toArray (/home/rmd/workspace/qb/node_modules/loopback-connector-mongodb/node_modules/mongodb/lib/mongodb/cursor.js:168:10)"}
}</code>

Subsequent queries result in the connection being closed.

**Comment by mariohmol** [comment]
in my case i cant see this error.. but inq is not working anyway

**Comment by ssh24** [comment]
This is not an issue anymore. Closing this as a result. Feel free to reopen if needed.
