### ISSUE TITLE
how to use write concern

### ISSUE THREAD

**Issue by nkgupta1989** [strongloop/loopback-connector-mongodb#78]
Hi, This is how i am defining my mongo connection details:- in my loopback config file,
My mongo is a replica set.

"mongo": {
      "connector": "mongodb",
      "url": "mongodb://90.40.26.46,90.40.26.47/ugc-prod?readPreference=secondary"
},

Now I want to add the "write concern" true here, can anyone help me how to accomplish that?

**Comment by raymondfeng** [comment]
Write concern can be specified as part of the `url` per http://docs.mongodb.org/manual/reference/connection-string/
