### ISSUE TITLE
1.5.0 breaking JSON Schema documents

### ISSUE THREAD

**Issue by doublemarked** [strongloop/loopback-connector-mongodb#79]
The upgrade from 1.4.5 -> 1.5.0 prevents the creation of models that include JSON Schema documents that contain an embedded ``$ref``. For example (simplified),

```
{
   "name": "example",
   "type": "object",
   "properties": {
     "billing_address": { "$ref": "/definitions/address" },
     "shipping_address": {
       "allOf": [
         { "$ref": "/definitions/address" },
         { "properties":
           { "type": { "enum": [ "residential", "business" ] } },
           "required": ["type"]
         }
       ]
     }
   }
}
```
Attempting to create a Model with such a property included produces the error:
```
{ [MongoError: key $ref must not start with '$']
  name: 'MongoError',
  message: 'key $ref must not start with \'$\'' }
```

Is this something wrong with loopback-connector-mongodb? Is it produced by a deprecation in the mongo 2.0 driver?

**Comment by raymondfeng** [comment]
See http://docs.mongodb.org/manual/faq/developers/#faq-dollar-sign-escaping. It might be related to the mongodb driver upgrade.

**Comment by doublemarked** [comment]
I see. Very interesting. It's a bit surprising to me that it's requiring escaping of normal JSON data.

@raymondfeng - in your opinion, does this sort of escaping belong in library code (like ``loopback-connector-mongodb``) or does belong in the codebase that is consuming the data (such as my API)?

**Comment by raymondfeng** [comment]
@doublemarked I suggest you open an issue against the mongodb driver as it's a behavior change from 1.x to 2.x in the driver.

**Comment by doublemarked** [comment]
Ok, thank you for your feedback.
