### ISSUE TITLE
Property value `undefined` is converted to `null`

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-connector-mongodb#87]
When a model property defined in the model schema with the value `undefined` is persisted to MongoDB, the value is converted to `null`.

This is inconsistent with other connectors like MySQL, as they preserve `undefined` property values as `undefined.

The fix will IMO break backwards compatibility, thus it will need a new major version.

Test cases for `test/mongodb.test.js` to reproduce the problem. We may want to move these tests to the juggler's shared suite run by all connectors:

```js
it('create should preserve `undefined` fields', function(done) {
  PostWithStringId.create(
    { title: 'a-title', content: undefined },
    function(err, created) {
      if (err) return done(err);

      created.toObject().should.eql({
        id: created.id,
        title: 'a-title',
        content: undefined
      });

      PostWithStringId.findById(created.id, function(err, found) {
        if (err) return done(err);
        found.toObject().should.eql({
          id: created.id,
          title: 'a-title',
          content: undefined
        });
        done();
      });
    });
});

it('updateOrCreate should preserve `undefined` fields', function(done) {
  PostWithStringId.create(
    { title: 'a-title', content: undefined },
    function(err, instance) {
      if (err) return done(err);
      instance.toObject().should.eql({
        id: instance.id,
        title: 'a-title',
        content: undefined
      });

      PostWithStringId.updateOrCreate(
        { id: instance.id, title: 'updated title' },
        function(err, updated) {
          if (err) return done(err);
          updated.toObject().should.eql({
            id: instance.id,
            title: 'updated title',
            content: undefined
          });
          done();
        });
    });
});
```

@raymondfeng You have mentioned that we should strip `undefined` properties from the data. AFAIK, juggler's `lib/dao.js` is already doing that, see the method `removeUndefined` in `lib/utils.js`. This makes the problem even more puzzling.

**Comment by bajtos** [comment]
@raymondfeng thanks, I'll take a look. Do you agree it is a breaking change? Or is it only a bug in DAO's `create` implementation?

**Comment by raymondfeng** [comment]
I feel it's a bug in the DAO's `create` implementation. It's only exposed by the mongodb driver that coerces `undefined` to `null` if present.
