### ISSUE TITLE
Boolean fields always true sent to POST via REST

### ISSUE THREAD

**Issue by beat84** [strongloop/loopback-connector-mongodb#90]
Hi there,
I made a POST call to rest with jQuery like this:

```javascript
var obj = {};
obj.isFree = false;
obj.yob = 1981;
obj.name = "PlayerName";
$.post("/api/players?access_token="+getAccessToken(), obj, "json").done(function(result){
	...
}).fail(function(){
	...
});
```

but when I go through my DB the isFree field is set to `true`.

Here's my model:

```json
{
  "name": "player",
  "plural": "players",
  "base": "PersistedModel",
  "idInjection": true,
  "properties": {
    "name": {
      "type": "string",
      "required": true
    },
    "yob": {
      "type": "number"
    },
    "photo": {
      "type": "string"
    },
    "isFree": {
      "type": "boolean"
    }
  },
  "validations": [],
  "relations": {
    "playerRole": {
      "type": "hasOne",
      "model": "playerRole",
      "foreignKey": ""
    }
  },
  "acls": [
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$everyone",
      "permission": "DENY"
    },
    {
      "accessType": "*",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }
  ],
  "methods": []
}
```

Here the validation of the model in player.js:

```javascript
module.exports = function(Player) {
	Player.validatesUniquenessOf('name', { scopedTo: ['yob'] });
};
```

Here the final result my DB mongo:

```json
{
    "_id" : ObjectId("54d0e2f3074fbc9c97a6606f"),
    "name" : "PlayerName",
    "yob" : 1981,
    "photo" : null,
    "isFree" : true
}
```

I think this could be a bug in mongo connector.
Anyone with this issue?

**Comment by raymondfeng** [comment]
In your case, the `isFree` should have a `boolean` type instead of `number`. Please try with the following model def:
```json
"isFree": {
      "type": "boolean"
    }
```

**Comment by beat84** [comment]
Sorry about that, I edited the code with number to make it work, and I left it in question.
It was Boolean obviously, I'm going to fix the question.

**Comment by raymondfeng** [comment]
Can you capture the http request payload from your browser? I wants to make sure that the JSON object received by LoopBack is complying.

**Comment by beat84** [comment]
Here's the shots of the http request by developer tools in Chrome:

![chrome_dev_tools](https://cloud.githubusercontent.com/assets/869696/6037479/4dfcf2f4-ac54-11e4-8164-9648b314ab3d.png)
![chrome_dev_tools2](https://cloud.githubusercontent.com/assets/869696/6037487/51236fc6-ac54-11e4-88fa-43fe6c5fc3a1.png)


and here's the response:

```json
{"surname":"PlayerSurname","name":"PlayerName","nationalities":[{"code":"ITA","position":"0"}],"category":"euv","type":"combo","off":"ast","def":"p","height":177,"wing":190,"yob":1984,"tshirt":26,"salary":3000,"contractExpiration":0,"college":"","agency":"","mainAgent":"","countryAgent":"","isFree":true,"id":"54d1ddd0f61a006aa61f7623","role":"54cf4b422a71caa36b74852a"}
```

**Comment by raymondfeng** [comment]
Oh, the request was sent in `application/x-www-form-urlencoded` content type. In that case, the value of `isFree` might be captured as `"false"` and `"false"` is NOT falsy in JS. Can you try `application/json` while we try to find out the root cause?

**Comment by beat84** [comment]
Forcing the content type and using JSON.stringify for the object, it works properly.
Could be useful to have the possibility to translate the data server-side (I mean, the classical use of jQuery $.post with "json" as parameter)?
What do you think?

Thanks for the hint! ;)

**Comment by raymondfeng** [comment]
We'll consider to coerce `'false'` and `'true'` for boolean properties in the model class.
