### ISSUE TITLE
Loopback models and "date" property type issue. 

### ISSUE THREAD

**Issue by istinspring** [strongloop/loopback-connector-mongodb#93]
Hi massive, i'm pretty new in nodejs, so probably i just missed something.

There is model defined:

```
  "name": "landingUser",
  "base": "PersistedModel",
  "strict": false,
  "idInjection": false,
  "properties": {
    "email": {
      "type": "string",
      "required": true,
      "index": true
    },
    "created": {
      "type": "date"
    }
  },
...
```

I use AngularJS on front end to save record into mongo:

```
                var apiResponse = LandingUser.create({email: $scope.user.email});
                apiResponse.$promise.then(
                    function(value, responseHeaders) { // if success
```

And i want to save current time into database (like default=datetime.utcnow in SQLAlchemy) so a added this hook into model:

```
LandingUser.definition.properties.created.default = Date.now;
```

Date.now or Timestamp it does not matter, in both cases see:

```
{ "_id" : ObjectId("54d65c97be1c481a79552dd1"), "email" : "fdfjskj@gmail.com", "created" : 1423334551689 }
{ "_id" : ObjectId("54d65f4abe1c481a79552dd2"), "email" : "fdsfskhkhk@gmasdsad.com", "created" : 1423335242802 }
{ "_id" : ObjectId("54d65fb2be1c481a79552dd3"), "email" : "wewehqwkj@gmail.com", "created" : 1423335346493 }
{ "_id" : ObjectId("54d6600cbe1c481a79552dd4"), "email" : "dsdhsj@gmail.com", "created" : 1423335436174 }
``` 

It's not a dates it's just a numbers. I tried to google but with little success. After i even checked MongoDB driver docs (https://www.npmjs.com/package/mongodb#data-types) and tried to resolve using this:

```
    var mongo = require('mongodb');
    ....

    LandingUser.beforeCreate = function(next, data)
    {
        data.created = new mongo.Timestamp();
        next();
    };
```

Miracle happened i got ISODate() which is correct native representation of dates:

```
{ "_id" : ObjectId("54d670db32ad6cc826e610da"), "email" : "dsjdaskldjalk@fdskfjsh.com", "created" : ISODate("1999-12-31T17:00:00Z") }
```

Is it a bug or feature? Can loopback-connector-mongodb serialize objects to native mongodb format or i should handle this manually?

**Comment by istinspring** [comment]
https://github.com/strongloop/loopback-connector-mongodb/issues/69

there is similar question but no one respond.

**Comment by raymondfeng** [comment]
You should configure the default to a function that returns new Date() instead of Date.now(). The later is a number.

**Comment by istinspring** [comment]
Thank you! It works.

```
LandingUser.definition.properties.created.default = new Date();
....
{ "_id" : ObjectId("54d6844932ad6cc826e610e2"), "email" : "dsadkaksj@gmaildds.com", "created" : ISODate("1999-12-31T17:00:00Z") }
```
