### ISSUE TITLE
Default timeout value too low

### ISSUE THREAD

**Issue by seeker89** [strongloop/loopback-connector-mongodb#97]
Hi,

I am occasionally receiving "Connection fails: { [MongoError: no valid seed servers in list] name: 'MongoError', message: 'no valid seed servers in list' } " when instances bootup (app instances and mongo cluster are in different datacentres). Mongo is hosted at Compose.io

I suspect it's a timeout on the initial connection.

It would be nice to be able to give connection arguments directly to the driver through config.json

Pleas advise and many thanks!

**Comment by raymondfeng** [comment]
You should be able to configure the mongodb connector using 'url' property that takes a connection string with the timeout parameter.

**Comment by seeker89** [comment]
Thanks a lot, I missed that option !
