### ISSUE TITLE
MongoDB.prototype.buildWhere doesn't $ nested specs

### ISSUE THREAD

**Issue by srguiwiz** [strongloop/loopback-connector-mongodb#99]
It doesn't because it isn't fully correctly recursive.  Yet nested specs are needed to query embedded documents.  They almost work, with workarounds.

Workaround is at top level to use LoopBack syntax, at lower levels MongoDB syntax.  Solves many cases.

Suggested low cost fix:  Allow MongoDB syntax at any level.

Example given here.  To achieve MongoDB getting

```
find({"permissions":{$elemMatch:{"user":{$in:["one","other"]},"code":4}}})
```

had to have a where like

```
{"permissions":{elemMatch:{"user":{$in:["one","other"]},"code":4}}}
```

To be clear what is wrong with this picture:  Had to have $in because inq wouldn't be replaced.  But couldn't make it both $in and $elemMatch because that would have become $$elemMatch.

LoopBack syntax

```
{"permissions":{elemMatch:{"user":{inq:["one","other"]},"code":4}}}
```

would result in MongoDB dysfunctional

```
{"permissions":{$elemMatch:{"user":{inq:["one","other"]},"code":4}}}
```

A simple fix I'm going to send a pull request for will allow a "pure MongoDB" syntax.  Such as

```
{"permissions":{$elemMatch:{"user":{$in:["one","other"]},"code":4}}}
```

Seems much easier to implement than complete correct handling.

Some may appreciate the ability to "think and write MongoDB queries" all the way.

**Comment by srguiwiz** [comment]
pull request #100 has been opened

**Comment by fedebalderas** [comment]
Hi @srguiwiz any idea about why this query doesn't work?

I'm trying to do a query over  a property wihc is a Date type using **elemMatch** (sorry about my english). Take a look please (i've change a little my model for this example)

![screen shot 2016-05-26 at 11 13 01 am](https://cloud.githubusercontent.com/assets/5208431/15581924/19044dba-2334-11e6-92d3-ee61b9963167.png)

That is my model... So this query works fine:
![screen shot 2016-05-26 at 11 24 17 am](https://cloud.githubusercontent.com/assets/5208431/15581990/6cc3239a-2334-11e6-8c27-c3f8dbdf98e4.png)

But this doesn't work:
![screen shot 2016-05-26 at 11 26 22 am](https://cloud.githubusercontent.com/assets/5208431/15582085/d4782cec-2334-11e6-9935-c88c8e1dd81e.png)

Or this:
![screen shot 2016-05-26 at 11 26 59 am](https://cloud.githubusercontent.com/assets/5208431/15582107/f164bbb8-2334-11e6-9cf9-dde1f84a3fa0.png)

Any idea?

**Comment by ssh24** [comment]
You can use nested specs on the query itself without having to use mongoDB syntaxes.

Here is an sample code snippet:

**model-definition.js**
```json
{
  "name": "Bank",
  "base": "PersistedModel",
  "idInjection": true,
  "options": {
    "validateUpsert": true
  },
  "properties": {
    "id": {
      "type": "string",
      "required": true,
      "id": true
    },
    "name": {
      "type": "string"
    },
    "opens": {
      "type": "object"
    },
    "closes": {
      "type": "object"
    }
  },
  "validations": [],
  "relations": {},
  "acls": [],
  "methods": {}
}
```

**boot-script.js**
```js
'use strict';
var util = require('util');

module.exports = function(app) {
  var db = app.dataSources.mongoDs;
  var Bank = app.models.Bank;

  var data = [{
    id: '1',
    name: 'TD',
    opens: {
      monday: '7:00am',
      tuesday: '7:00am',
      wednesday: '7:00am',
    },
    closes: {
      monday: '7:00pm',
      tuesday: '7:00pm',
      wednesday: '7:00pm',
    },
  }, {
    id: '2',
    name: 'BMO',
    opens: {
      monday: '9:00am',
      tuesday: '7:00am',
      wednesday: '10:00am',
    },
    closes: {
      monday: '5:00pm',
      tuesday: '7:00pm',
      wednesday: '8:00pm',
    },
  }];

  db.automigrate(function(err) {
    if (err) throw err;
    console.log('\nAutomigrate complete');

    Bank.create(data, function(err, result) {
      if (err) throw err;
      console.log('\nCreated instance: ' + util.inspect(result, 4));

      Bank.find({where: {'opens.monday': '9:00am'}},
      function(err, result) {
        if (err) throw err;
        console.log('\nFind instance: ' + util.inspect(result, 4));
      });
    });
  });
};
```

The above query results in all the banks that opens on monday at 9:00am. 

Hopefully, this solves the issue. Closing this as a result. Feel free to reopen if needed.
